import {test,expect,type Page} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
async function ready(page:Page,bounded=false){await page.goto(`/browser/fixtures/bottom-cta.html${bounded?'?bounded=1':''}`);await expect(page.locator('[data-bottom-cta-panel]')).toHaveAttribute('data-placement','fixed');await page.evaluate(()=>document.fonts.ready);}
async function geometry(page:Page){return page.evaluate(()=>{const panel=document.querySelector('[data-bottom-cta-panel]')!,spacer=document.querySelector('[data-bottom-cta-spacer]')!,last=document.querySelector('[data-last-content]')!,container=panel.firstElementChild!,r=panel.getBoundingClientRect(),c=container.getBoundingClientRect();return {bottom:r.bottom,top:r.top,height:r.height,space:spacer.getBoundingClientRect().height,last:last.getBoundingClientRect().bottom,width:document.documentElement.scrollWidth,viewport:innerWidth,viewportHeight:innerHeight,innerWidth:c.width,center:(c.left+c.right)/2};});}
test('fixed CTA reserves actual wrapped accessory and font height, preserves last content, resize and modal layer',async({page},info)=>{
 await ready(page);const before=await geometry(page);expect(before.bottom).toBeCloseTo(before.viewportHeight,0);expect(before.space).toBeCloseTo(before.height,0);expect(before.innerWidth).toBeLessThanOrEqual(1200);expect(before.center).toBeCloseTo(before.viewport/2,0);
 await page.getByRole('button',{name:'안내 길이 변경'}).click();await expect.poll(async()=>(await geometry(page)).height).toBeGreaterThan(before.height);await expect.poll(async()=>Math.abs((await geometry(page)).space-(await geometry(page)).height)).toBeLessThan(1);
 await page.evaluate(()=>{document.querySelector<HTMLElement>('[data-bottom-cta-panel]')!.style.fontSize='24px';});await expect.poll(async()=>Math.abs((await geometry(page)).space-(await geometry(page)).height)).toBeLessThan(1);
 await page.setViewportSize({width:page.viewportSize()!.width,height:600});await expect.poll(async()=>(await geometry(page)).bottom).toBe(600);
 await page.evaluate(()=>window.scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'}));const end=await geometry(page);expect(end.last).toBeLessThanOrEqual(end.top+1);expect(end.width).toBeLessThanOrEqual(end.viewport);
 await page.getByRole('textbox',{name:'마지막 입력'}).focus();expect(await page.evaluate(()=>document.activeElement?.getAttribute('name'))).toBe('last');expect(await page.getByRole('textbox',{name:'마지막 입력'}).evaluate(node=>node.getBoundingClientRect().bottom)).toBeLessThanOrEqual((await geometry(page)).top-7);
 await page.getByRole('button',{name:'모달 열기'}).click();await expect(page.getByRole('dialog',{name:'겹침 확인'})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'모달 열기'})).toBeFocused();
 await page.evaluate(()=>window.scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'}));await page.screenshot({path:info.outputPath('bottom-cta.png')});
});
test('owned scroll frame protects focused last field while fixed panel height grows and loading retains edits',async({page})=>{
 await ready(page,true);const last=page.getByRole('textbox',{name:'마지막 입력'});await last.fill('수정한 끝');await last.focus();const input=await last.elementHandle();
 await page.evaluate(()=>document.querySelector<HTMLElement>('[data-bottom-cta-panel]')!.style.fontSize='30px');
 await expect.poll(async()=>(await last.evaluate(node=>node.getBoundingClientRect().bottom))-(await geometry(page)).top).toBeLessThanOrEqual(-7);await expect(last).toBeFocused();
 const body=page.locator('[data-bottom-cta-body]');expect(await body.evaluate(node=>node.scrollTop)).toBeGreaterThan(0);expect(await page.evaluate(()=>window.scrollY)).toBe(0);
 await page.getByRole('button',{name:'제출 처리 상태 변경'}).click();const submit=page.getByRole('button',{name:'신청 제출'});await expect(submit).toHaveAttribute('aria-busy','true');await submit.click({force:true});await expect(page.getByRole('status')).toBeEmpty();await expect(last).toHaveValue('수정한 끝');expect(await last.evaluate((node,old)=>node===old,input)).toBe(true);
 await page.getByRole('button',{name:'취소',exact:true}).click();await expect(page.getByRole('status')).toHaveText('취소했습니다. 입력 내용은 유지됩니다.');await page.getByRole('button',{name:'제출 처리 상태 변경'}).click();await submit.click();await expect(page.getByRole('status')).toHaveText('제출: 초안');
 expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
});
for(const bounded of [false,true])test(`padding and border only changes reserve border-box and protect focused content (${bounded?'owned scroll':'document'})`,async({page})=>{
 await ready(page,bounded);const last=page.getByRole('textbox',{name:'마지막 입력'});await last.focus();
 const original=await geometry(page);const contentHeight=await page.locator('[data-bottom-cta-panel] > .ds-container').evaluate(node=>node.getBoundingClientRect().height);
 await page.evaluate(()=>{const css=document.createElement('style');css.textContent='.ds-core .ds-bottom-cta.padding-only {padding-bottom:calc(60px + env(safe-area-inset-bottom,0px));} .ds-core .ds-bottom-cta.border-only {border-bottom:8px solid #475569;}';document.head.append(css);document.querySelector('[data-bottom-cta-panel]')!.classList.add('padding-only');});
 await expect.poll(async()=>Math.abs((await geometry(page)).space-(await geometry(page)).height)).toBeLessThan(1);expect((await geometry(page)).height).toBeCloseTo(original.height+40,0);
 expect(await page.locator('[data-bottom-cta-panel] > .ds-container').evaluate(node=>node.getBoundingClientRect().height)).toBeCloseTo(contentHeight,0);await expect(last).toBeFocused();
 await expect.poll(async()=>(await last.evaluate(node=>node.getBoundingClientRect().bottom))-(await geometry(page)).top).toBeLessThanOrEqual(-7);
 await page.evaluate(()=>document.querySelector('[data-bottom-cta-panel]')!.classList.add('border-only'));
 await expect.poll(async()=>Math.abs((await geometry(page)).space-(await geometry(page)).height)).toBeLessThan(1);expect((await geometry(page)).height).toBeCloseTo(original.height+48,0);await expect(last).toBeFocused();
 await expect.poll(async()=>(await last.evaluate(node=>node.getBoundingClientRect().bottom))-(await geometry(page)).top).toBeLessThanOrEqual(-7);
 if(bounded)await page.locator('[data-bottom-cta-body]').evaluate(node=>node.scrollTop=node.scrollHeight);else await page.evaluate(()=>window.scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'}));expect((await geometry(page)).last).toBeLessThanOrEqual((await geometry(page)).top+1);
});
test('gallery native validation and actions are real, folded docs and scoped consumer keep containment',async({page})=>{
 await page.goto('/#/components/bottom-cta');await expect(page.getByRole('heading',{level:1,name:'하단 작업 · BottomCTA'})).toBeVisible();const form=page.locator('#bottom-cta-demo');await form.getByRole('button',{name:'신청하기'}).click();await expect(form.getByRole('status')).toBeEmpty();await form.getByRole('textbox',{name:'신청 제목 (필수)',exact:true}).fill('검토안');await form.getByRole('button',{name:'신청하기'}).click();await expect(form.getByRole('status')).toHaveText('제출: 검토안');await form.getByRole('checkbox',{name:'제출 처리 중'}).check();await expect(form.getByRole('button',{name:'신청하기'})).toHaveAttribute('aria-disabled','true');await form.getByRole('button',{name:'신청하기'}).click({force:true});await expect(form.getByRole('status')).toHaveText('제출: 검토안');await form.getByRole('button',{name:'취소'}).click();await expect(form.getByRole('status')).toContainText('취소했습니다.');await expect(form.getByRole('textbox',{name:'신청 제목 (필수)',exact:true})).toHaveValue('검토안');
 expect(await page.locator('.component-detail details[open]').count()).toBe(0);expect(await page.locator('h1').count()).toBe(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);expect((await new AxeBuilder({page}).include('.component-detail').withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
});
