import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
const repo=fileURLToPath(new URL('../../../',import.meta.url)),evidence=process.env.CORE07_EVIDENCE_DIR;
assert.ok(evidence&&path.isAbsolute(evidence)&&!path.resolve(evidence).startsWith(path.resolve(repo)+path.sep)&&path.resolve(evidence)!==path.resolve(repo));
const sha=b=>createHash('sha256').update(b).digest('hex');
const core=path.join(repo,'packages/core'),manifest=JSON.parse(fs.readFileSync(path.join(core,'payload/manifest.json')));
function snapshot(dir,base=dir){const s=fs.lstatSync(dir,{bigint:true}),out=dir===base?{'.':{ino:String(s.ino),mtimeNs:String(s.mtimeNs),mode:String(s.mode)}}:{};for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name),st=fs.lstatSync(p,{bigint:true});out[path.relative(base,p)]={ino:String(st.ino),mtimeNs:String(st.mtimeNs),mode:String(st.mode),...(e.isFile()?{hash:sha(fs.readFileSync(p))}:{}),...(e.isSymbolicLink()?{link:fs.readlinkSync(p)}:{})};if(e.isDirectory())Object.assign(out,snapshot(p,base));}return out;}
function run(label,cmd,args,cwd){const before=snapshot(cwd),started=new Date().toISOString(),start=performance.now(),r=spawnSync(cmd,args,{cwd,encoding:'utf8',maxBuffer:16e6}),after=snapshot(cwd);fs.writeFileSync(path.join(evidence,`lint-source-${label}-${process.hrtime.bigint()}.json`),JSON.stringify({command:[cmd,...args],cwd,runtime:process.version,started,durationMs:performance.now()-start,exit:r.status,stdout:r.stdout,stderr:r.stderr,before,after},null,2));return {...r,before,after};}
function fixture(compiler=true){const host=fs.mkdtempSync(path.join(evidence,'lint-source-host-'));fs.writeFileSync(path.join(host,'package.json'),JSON.stringify({name:'core07-source',private:true,type:'module',devDependencies:{tailwindcss:'4.3.3'}}));if(compiler){const prepared=process.env.HANGYEOL_TEST_TAILWIND_ROOT;if(prepared){assert.ok(path.isAbsolute(prepared));assert.equal(fs.realpathSync(prepared),path.resolve(prepared),'prepared compiler must be physical');const metadata=JSON.parse(fs.readFileSync(path.join(prepared,'package.json')));assert.equal(metadata.name,'tailwindcss');assert.equal(metadata.version,'4.3.3');const target=path.join(host,'node_modules/tailwindcss');fs.cpSync(prepared,target,{recursive:true});assert.deepEqual(fs.readFileSync(path.join(target,'package.json')),fs.readFileSync(path.join(prepared,'package.json')));fs.writeFileSync(path.join(evidence,`lint-source-prepared-compiler-${process.hrtime.bigint()}.json`),JSON.stringify({mode:'explicit prepared physical dependency copy; not registry/cache portability',source:prepared,target,version:metadata.version},null,2));}else{const r=run('offline-compiler-prepare','npm',['install','--offline','--ignore-scripts'],host);assert.equal(r.status,0,r.stderr);}}const config={schemaVersion:1,sourceRoot:'ui/system',stylePath:'styles/theme.css',alias:'@hangyeol',installed:{}};for(const name of ['foundation/theme.css','lib/cn.ts','primitives/button.tsx','primitives/input.tsx','components/text-field.tsx']){const p=path.join(host,config.sourceRoot,name);fs.mkdirSync(path.dirname(p),{recursive:true});fs.copyFileSync(path.join(core,'payload/source',name),p);config.installed[config.sourceRoot+'/'+name]={hash:manifest.files[name].hash,version:manifest.version};}fs.mkdirSync(path.join(host,'styles'));fs.writeFileSync(path.join(host,config.stylePath),'@import "tailwindcss/theme.css";\n@import "tailwindcss/utilities.css";\n@import "../ui/system/foundation/theme.css";\n');fs.writeFileSync(path.join(host,'hangyeol.json'),JSON.stringify(config));fs.mkdirSync(path.join(host,'src'));fs.writeFileSync(path.join(host,'src/outside-sentinel.tsx'),'export const Out=()=> <div className="not-a-real-utility"/>;');return host;}
// The build supplies packed-relative common/safety imports; this is source-built,
// not physical installed acceptance (the separate installed test supplies that).
function lint(host,args=[]){const wrapper=`import fs from 'node:fs';import {runLint} from ${JSON.stringify(pathToFileURL(path.join(core,'dist/tools/lint.mjs')).href)};const root=${JSON.stringify(core)};process.exitCode=await runLint(process.argv.slice(1),{root,pkg:JSON.parse(fs.readFileSync(root+'/package.json')),manifest:JSON.parse(fs.readFileSync(root+'/payload/manifest.json')),payloadRoot:root+'/payload'});`;return run('invoke',process.execPath,['--input-type=module','-e',wrapper,...args],host);}
test('nested reserved trees are excluded from consumer inspection',()=>{const host=fixture();for(const name of ['node_modules','.git','.hangyeol-backups','.hangyeol-transactions']){const dir=path.join(host,'ui/system',name,'nested');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bad.tsx'),'export const Bad=()=> <div className="hangyeol-not-a-real-utility"/>;');}const r=lint(host);assert.equal(r.status,0,r.stderr);assert.equal(JSON.parse(r.stdout).coverage.sourceFiles,4);assert.deepEqual(r.after,r.before);});
test('valid compiler marker classes bare named and variant-used pass without unknown waiver',()=>{const host=fixture(),file=path.join(host,'ui/system/markers.tsx');for(const classes of ['group peer','group/card peer/field','group group-hover:flex peer peer-focus:block','group/card group-hover/card:flex peer/field peer-focus/field:block']){fs.writeFileSync(file,`export const View=()=> <div className="${classes}"/>;`);const r=lint(host);assert.equal(r.status,0,r.stderr);assert.deepEqual(r.after,r.before);}fs.writeFileSync(file,'export const Bad=()=> <div className="group-invalid peer-invalid"/>;');const bad=lint(host);assert.equal(bad.status,1);assert.ok(JSON.parse(bad.stdout).diagnostics.some(d=>d.rule==='core/unknown-class'));});
test('logical literal left operands cannot hide unknown classes',()=>{const host=fixture();const file=path.join(host,'ui/system/logical.tsx');for(const expr of ["'hangyeol-not-a-real-utility' || 'flex'","'hangyeol-not-a-real-utility' ?? 'flex'","cn('hangyeol-not-a-real-utility' || 'flex')"]){fs.writeFileSync(file,`export const View=()=> <div className={${expr}}/>;`);const r=lint(host);assert.equal(r.status,1,r.stderr);assert.ok(JSON.parse(r.stdout).diagnostics.some(d=>d.rule==='core/unknown-class'&&d.file==='ui/system/logical.tsx'&&d.line===1));assert.deepEqual(r.after,r.before);}});
test('lint activates consumer configured sourceRoot and passes editable local Button/TextField without writing host',()=>{const host=fixture(),r=lint(host);assert.equal(r.status,0,r.stderr);const result=JSON.parse(r.stdout);assert.equal(result.sourceRoot,'ui/system');assert.equal(result.compiler.mode,'actual');assert.equal(result.coverage.sourceFiles,4);assert.deepEqual(result.diagnostics,[]);assert.deepEqual(r.after,r.before);});

test('source-built negative fixtures identify actual file/line/rule without writes or host config execution',()=>{
 const host=fixture(),dir=path.join(host,'ui/system/examples');fs.mkdirSync(dir);const file=path.join(dir,'case.tsx');fs.writeFileSync(path.join(host,'eslint.config.mjs'),"throw Error('HOST ESLINT MUST NOT EXECUTE');");
 const cases=[['utility',"export const Bad=()=> <div className=\"p-[13px]\"/>;",'shadcn/no-arbitrary-values'],['unknown',"export const Bad=()=> <div className=\"hangyeol-not-a-real-utility\"/>;",'core/unknown-class'],['override',"import {Button} from '../primitives/button';\nexport const Bad=()=> <Button className=\"p-8 rounded-full\"/>;",'shadcn/no-restyle'],['alias-override',"import {TextField} from '@hangyeol/components/text-field';\nexport const Bad=()=> <TextField label=\"Name\" className=\"p-8\"/>;",'shadcn/no-restyle'],['raw-color',"export const Bad=()=> <div className=\"bg-red-600\"/>;",'shadcn/no-raw-colors'],['inline',"export const Bad=()=> <div style={{padding:13}}/>;",'shadcn/no-inline-styles']];
 for(const [label,code,rule] of cases){fs.writeFileSync(file,code);const r=lint(host);assert.equal(r.status,1,label+': '+r.stderr);const result=JSON.parse(r.stdout),d=result.diagnostics.find(d=>d.rule===rule);assert.ok(d,label+': '+r.stdout);assert.equal(d.file,'ui/system/examples/case.tsx');assert.equal(d.line,code.startsWith('import')?2:1);assert.match(r.stderr,new RegExp('ui/system/examples/case\\.tsx:'+d.line+':'));assert.deepEqual(r.after,r.before);}
});
test('source-built missing compiler is explicitly incomplete with no grammar unknown-class pass',()=>{const host=fixture(false),r=lint(host);assert.equal(r.status,2,r.stderr);const result=JSON.parse(r.stdout);assert.equal(result.compiler.mode,'unavailable');assert.equal(result.compiler.fallback,'none');assert.match(r.stderr,/no unknown-class pass claimed/);assert.deepEqual(r.after,r.before);});
test('configured dependency-tree scope is refused instead of certifying installed tools as editable UI',()=>{const host=fixture(),config=JSON.parse(fs.readFileSync(path.join(host,'hangyeol.json')));fs.mkdirSync(path.join(host,'node_modules/editable'));fs.writeFileSync(path.join(host,'node_modules/editable/view.tsx'),'export const View=()=> <div className="flex"/>;');config.sourceRoot='node_modules/editable';fs.writeFileSync(path.join(host,'hangyeol.json'),JSON.stringify(config));const r=lint(host);assert.equal(r.status,1,r.stdout+'\n'+r.stderr);assert.match(r.stderr,/reserved.*sourceRoot/i);assert.deepEqual(r.after,r.before);});
test('noncanonical configured alias imports cannot bypass component override recognition',()=>{const host=fixture();fs.mkdirSync(path.join(host,'ui/system/examples'));fs.writeFileSync(path.join(host,'ui/system/examples/alias.tsx'),"import {Button} from '@hangyeol/primitives/../primitives/button';\nexport const Bad=()=> <Button className=\"p-8\"/>;");const r=lint(host);assert.equal(r.status,1,r.stdout+'\n'+r.stderr);assert.match(r.stderr,/unsafe.*alias import/i);assert.deepEqual(r.after,r.before);});
test('semantic custom-property override retains the existing design-policy rejection',()=>{const host=fixture();fs.mkdirSync(path.join(host,'ui/system/examples'));fs.writeFileSync(path.join(host,'ui/system/examples/override.tsx'),"import {Button} from '../primitives/button';\nexport const Bad=()=> <Button style={{'--g-action':'var(--owner-color)'}}/>;");const r=lint(host);assert.equal(r.status,1,r.stdout+'\n'+r.stderr);const d=JSON.parse(r.stdout).diagnostics.find(d=>d.rule==='ds/no-unowned-custom-properties');assert.ok(d,r.stdout);assert.equal(d.file,'ui/system/examples/override.tsx');assert.equal(d.line,2);assert.deepEqual(r.after,r.before);});
test('source-built config traversal, symlink child, empty scan and relative outside imports fail read-only',()=>{const host=fixture(false),p=path.join(host,'hangyeol.json'),bytes=fs.readFileSync(p),config=JSON.parse(bytes);for(const sourceRoot of ['../escape','/absolute','ui\\escape','.','']){fs.writeFileSync(p,JSON.stringify({...config,sourceRoot}));const r=lint(host);assert.equal(r.status,1,r.stderr);assert.match(r.stderr,/unsafe|invalid/i);assert.deepEqual(r.after,r.before);}fs.mkdirSync(path.join(host,'empty'));fs.writeFileSync(p,JSON.stringify({...config,sourceRoot:'empty'}));const empty=lint(host);assert.equal(empty.status,1);assert.match(empty.stderr,/No TypeScript source files inspected/);assert.deepEqual(empty.after,empty.before);fs.writeFileSync(p,bytes);fs.mkdirSync(path.join(host,'ui/system/examples'));fs.writeFileSync(path.join(host,'ui/system/examples/outside.tsx'),"import {Out} from '../../../src/outside-sentinel'; export const View=()=> <Out/>;");const outside=lint(host);assert.equal(outside.status,1);assert.match(outside.stderr,/Import escapes sourceRoot/);assert.deepEqual(outside.after,outside.before);fs.symlinkSync(path.join(host,'missing'),path.join(host,'ui/system/link'));const link=lint(host);assert.equal(link.status,1);assert.match(link.stderr,/symlink/);assert.deepEqual(link.after,link.before);});
test('owner exception requires original template record and does not waive other rules or customization filenames',()=>{const host=fixture(),p=path.join(host,'ui/system/components/text-field.tsx'),original=fs.readFileSync(p,'utf8');fs.writeFileSync(p,original.replace('shrink-0 whitespace-nowrap','p-8'));const configFile=path.join(host,'hangyeol.json'),config=JSON.parse(fs.readFileSync(configFile));config.installed['ui/system/components/text-field.tsx'].hash='0'.repeat(64);fs.writeFileSync(configFile,JSON.stringify(config));const r=lint(host);assert.equal(r.status,1,r.stderr);assert.ok(JSON.parse(r.stdout).diagnostics.some(d=>d.rule==='shadcn/no-restyle'&&d.file.endsWith('/text-field.tsx')));assert.deepEqual(r.after,r.before);fs.writeFileSync(path.join(host,'ui/system/customization.tsx'),"import {Button} from './primitives/button'; export const Bad=()=> <Button className=\"p-8 bg-red-600\"/>;");const custom=lint(host);assert.equal(custom.status,1);for(const rule of ['shadcn/no-restyle','shadcn/no-raw-colors'])assert.ok(JSON.parse(custom.stdout).diagnostics.some(d=>d.rule===rule&&d.file==='ui/system/customization.tsx'));assert.deepEqual(custom.after,custom.before);});
test('editable consumer theme declarations extend semantic color/type recognition without raw palette waiver',()=>{const host=fixture(),theme=path.join(host,'ui/system/foundation/theme.css');fs.appendFileSync(theme,'\n@theme inline { --color-owner-surface: #123456; --text-owner-body: 1rem; }\n');fs.writeFileSync(path.join(host,'ui/system/local-theme.tsx'),'export const Local=()=> <div className="bg-owner-surface text-owner-body"/>;');const r=lint(host);assert.equal(r.status,0,r.stderr);const result=JSON.parse(r.stdout);assert.equal(result.compiler.mode,'actual');assert.deepEqual(result.diagnostics,[]);assert.deepEqual(r.after,r.before);fs.writeFileSync(path.join(host,'ui/system/local-theme.tsx'),'export const Bad=()=> <div className="bg-red-600"/>;');const negative=lint(host);assert.equal(negative.status,1);assert.ok(JSON.parse(negative.stdout).diagnostics.some(d=>d.rule==='shadcn/no-raw-colors'));assert.deepEqual(negative.after,negative.before);});
