import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';

const repo=fileURLToPath(new URL('../../../',import.meta.url)),evidence=process.env.CORE08_EVIDENCE_DIR;
assert.ok(evidence&&path.isAbsolute(evidence)&&!path.resolve(evidence).startsWith(path.resolve(repo)+path.sep)&&path.resolve(evidence)!==path.resolve(repo));
export const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
export function snapshot(dir,base=dir){const s=fs.lstatSync(dir,{bigint:true}),out={[path.relative(base,dir)||'.']:{inode:String(s.ino),mtimeNs:String(s.mtimeNs),mode:String(s.mode),...(s.isFile()?{hash:hash(fs.readFileSync(dir))}:{}),...(s.isSymbolicLink()?{link:fs.readlinkSync(dir)}:{})}};if(s.isDirectory())for(const e of fs.readdirSync(dir))Object.assign(out,snapshot(path.join(dir,e),base));return out;}
export function run(label,command,args,cwd,env=process.env){const before=snapshot(cwd),started=new Date().toISOString(),start=performance.now(),r=spawnSync(command,args,{cwd,env,encoding:'utf8',maxBuffer:16e6}),after=snapshot(cwd);fs.writeFileSync(path.join(evidence,`tokens-${label}-${process.hrtime.bigint()}.json`),JSON.stringify({argv:[command,...args],cwd,runtime:process.version,started,ended:new Date().toISOString(),durationMs:performance.now()-start,exit:r.status,stdout:r.stdout,stderr:r.stderr,before,after},null,2));return {...r,before,after};}
function fixture(){const host=fs.mkdtempSync(path.join(evidence,'tokens-source-host-'));fs.mkdirSync(path.join(host,'ui/system/foundation'),{recursive:true});fs.mkdirSync(path.join(host,'styles'));fs.copyFileSync(path.join(repo,'packages/ui/src/foundation/theme.css'),path.join(host,'ui/system/foundation/theme.css'));fs.writeFileSync(path.join(host,'styles/theme.css'),'@import "tailwindcss/theme.css";\n@import "tailwindcss/utilities.css";\n@import "../ui/system/foundation/theme.css";\n.sentinel { color: rebeccapurple; }\n');fs.writeFileSync(path.join(host,'gyeol.json'),JSON.stringify({schemaVersion:1,sourceRoot:'ui/system',stylePath:'styles/theme.css'}));return host;}
const packageRoot=process.env.CORE08_PACKAGE_ROOT;
assert.ok(packageRoot&&path.isAbsolute(packageRoot)&&path.resolve(packageRoot)!==path.resolve(repo)&&!path.resolve(packageRoot).startsWith(path.resolve(repo)+path.sep),'CORE08_PACKAGE_ROOT must point to the current scratch-built package outside the repository');
assert.equal(hash(fs.readFileSync(path.join(packageRoot,'dist/tools/token-policy.mjs'))),hash(fs.readFileSync(path.join(repo,'packages/core/src/tools/token-policy.mjs'))),'scratch token policy must match current canonical source; rebuild before source tests');
const bin=path.join(packageRoot,'bin/hangyeol.mjs');
test('repeat source-built add preserves minified owner config and unknown fields without writes/npm',()=>{const host=fs.mkdtempSync(path.join(evidence,'config-noop-')),manifest=JSON.parse(fs.readFileSync(path.join(packageRoot,'payload/manifest.json')));fs.writeFileSync(path.join(host,'package.json'),JSON.stringify({name:'config-source-host',private:true,type:'module',dependencies:{react:'19.2.0','react-dom':'19.2.0',...manifest.runtime},devDependencies:{vite:'7.3.6',...manifest.build,...manifest.types}}));for(const args of [['init'],['add','button']]){const r=run('config-prepare',bin,args,host);assert.equal(r.status,0,r.stderr);}const p=path.join(host,'gyeol.json'),config=JSON.parse(fs.readFileSync(p));config.tokens={source:'ui/custom.json',palette:'NotAPreset'};config.owner={nested:[3,{a:false}],statusOverride:'custom'};fs.writeFileSync(p,JSON.stringify(config));const r=run('config-noop-red',bin,['add','button'],host);assert.equal(r.status,0,r.stderr);assert.deepEqual(r.after,r.before);assert.deepEqual(JSON.parse(fs.readFileSync(p)),config);});
test('consumer validation reads configured actual semantic CSS and preserves bytes and metadata',()=>{const host=fixture(),r=run('activation',bin,['tokens','validate'],host);assert.equal(r.status,0,r.stderr);const report=JSON.parse(r.stdout);assert.equal(report.operation,'validate');assert.equal(report.sourceRoot,'ui/system');assert.ok(report.inputs.some(i=>i.path==='ui/system/foundation/theme.css'));assert.equal(report.schemes.light.roles['--g-surface'].value,'#FFFFFF');assert.equal(report.schemes.dark.roles['--g-surface'].value,'#1E293B');assert.deepEqual(r.after,r.before);});
test('five explicit preset palettes export both schemes to stdout without resetting actual consumer',()=>{const host=fixture(),catalog=run('presets-red',bin,['tokens','presets'],host);assert.equal(catalog.status,0,catalog.stderr);const presets=JSON.parse(catalog.stdout);assert.equal(presets.defaultPalette,'Indigo');assert.deepEqual(Object.keys(presets.palettes),['Indigo','Silver','Forest','Amber','Rose']);for(const preset of Object.keys(presets.palettes)){const r=run('preset-'+preset,bin,['tokens','export','--preset',preset,'--format','css'],host);assert.equal(r.status,0,r.stderr);assert.match(r.stdout,new RegExp('data-palette="'+preset+'"'));assert.match(r.stdout,/data-theme="dark"/);assert.deepEqual(r.after,r.before);}assert.deepEqual(catalog.after,catalog.before);});
test('five actual initialized CSS palettes match the canonical catalog in both schemes',()=>{const host=fixture(),catalog=JSON.parse(run('actual-catalog',bin,['tokens','presets'],host).stdout);let count=0;for(const palette of Object.keys(catalog.palettes)){const r=run('actual-palette-'+palette,bin,['tokens','validate','--palette',palette],host);assert.equal(r.status,0,r.stderr);const current=JSON.parse(r.stdout);for(const scheme of ['light','dark']){assert.equal(current.schemes[scheme].roles['--g-action'].value,catalog.palettes[palette][scheme]['--g-action'].value);count++;}assert.deepEqual(r.after,r.before);}assert.equal(count,10);});
test('typed semantic source connects custom replacement, aliases and units to actual configured CSS',()=>{const host=fixture(),theme=path.join(host,'ui/system/foundation/theme.css'),configFile=path.join(host,'gyeol.json'),config=JSON.parse(fs.readFileSync(configFile));const current=JSON.parse(run('read-current',bin,['tokens','validate'],host).stdout),palettes={Owner:{replacement:true,light:{},dark:{}}};for(const scheme of ['light','dark'])for(const [name,t] of Object.entries(current.schemes[scheme].roles))palettes.Owner[scheme][name]={$type:t.type,$value:t.sourceValue};for(const scheme of ['light','dark']){palettes.Owner[scheme]['--g-focus']={$type:'color',$value:'{--g-danger}'};palettes.Owner[scheme]['--spacing-owner']={$type:'dimension',$value:1.25,unit:'rem'};}fs.writeFileSync(theme,fs.readFileSync(theme,'utf8').replace(/--g-focus: [^;]+;/g,'--g-focus: var(--g-danger);')+'\n@theme { --spacing-owner: 1.25rem; }\n');const source='ui/system/foundation/tokens.json';fs.writeFileSync(path.join(host,source),JSON.stringify({schemaVersion:1,palettes}));fs.writeFileSync(configFile,JSON.stringify({...config,tokens:{source,palette:'Owner'}}));const r=run('typed-source-red',bin,['tokens','validate'],host);assert.equal(r.status,0,r.stderr);const report=JSON.parse(r.stdout);assert.ok(report.semanticSource,'validation must read the configured semantic source, not ignore it');assert.equal(report.semanticSource.path,source);assert.equal(report.semanticSource.palettes.Owner.light['--g-focus'].alias,'--g-danger');assert.equal(report.semanticSource.palettes.Owner.light['--spacing-owner'].value,'1.25rem');assert.equal(report.semanticSource.palettes.Owner.light['--spacing-owner'].unit,'rem');assert.deepEqual(r.after,r.before);});
test('existing CSS missing role, alias cycle, missing target and type mismatch fail read-only',()=>{const host=fixture(),theme=path.join(host,'ui/system/foundation/theme.css'),original=fs.readFileSync(theme,'utf8');const cases=[['missing',original.replace(/--g-surface: [^;]+;/g,''),/missing role --g-surface/],['cycle',original.replace(/--g-surface: [^;]+;/g,'--g-surface: var(--g-ink);').replace(/--g-ink: [^;]+;/g,'--g-ink: var(--g-surface);'),/alias cycle/],['target',original.replace(/--g-surface: [^;]+;/g,'--g-surface: var(--g-absent);'),/missing alias target/],['type',original.replace(/--g-surface: [^;]+;/g,'--g-surface: 14px;'),/type mismatch/]];assert.equal(cases.length,4);for(const [label,css,reason] of cases){fs.writeFileSync(theme,css);const r=run(label,bin,['tokens','validate'],host);assert.equal(r.status,1,r.stderr);assert.match(r.stderr,reason);assert.deepEqual(r.after,r.before);}});
test('inherited partial override re-resolves aliases against child values instead of flattening parent',()=>{const host=fixture(),theme=path.join(host,'ui/system/foundation/theme.css'),config=JSON.parse(fs.readFileSync(path.join(host,'gyeol.json'))),source='ui/system/foundation/tokens.json';const data={schemaVersion:1,palettes:{Parent:{extends:'Indigo',light:{'--g-focus':{$type:'color',$value:'{--g-danger}'}},dark:{'--g-focus':{$type:'color',$value:'{--g-danger}'}}},Child:{extends:'Parent',light:{'--g-danger':{$type:'color',$value:'rebeccapurple'}},dark:{'--g-danger':{$type:'color',$value:'oklch(80% 0.1 310)'}}}}};fs.writeFileSync(path.join(host,source),JSON.stringify(data));fs.writeFileSync(path.join(host,'gyeol.json'),JSON.stringify({...config,tokens:{source,palette:'Child'}}));fs.writeFileSync(theme,fs.readFileSync(theme,'utf8').replace(/--g-focus: [^;]+;/g,'--g-focus: var(--g-danger);').replace('--g-danger: #a3352a;','--g-danger: rebeccapurple;').replace('--g-danger: #ffa99d;','--g-danger: oklch(80% 0.1 310);'));const r=run('inherited-alias-red',bin,['tokens','validate'],host);assert.equal(r.status,0,r.stderr);assert.equal(JSON.parse(r.stdout).semanticSource.palettes.Child.light['--g-focus'].value,'rebeccapurple');assert.deepEqual(r.after,r.before);});
test('conditional semantic CSS is refused instead of pretending a computed cascade pass',()=>{const host=fixture();fs.appendFileSync(path.join(host,'ui/system/foundation/theme.css'),'\n@media (min-width: 800px) { [data-gyeol] { --g-surface: pink; } }\n');const r=run('conditional-red',bin,['tokens','validate'],host);assert.equal(r.status,1,r.stderr);assert.match(r.stderr,/unsupported.*conditional/i);assert.deepEqual(r.after,r.before);});
test('preset JSON re-resolves exported utility aliases and unknown selected palette never silently falls back',()=>{const host=fixture(),r=run('preset-parity-red',bin,['tokens','export','--preset','Indigo'],host);assert.equal(r.status,0,r.stderr);const report=JSON.parse(r.stdout);assert.equal(report.schemes.light.roles['--color-g-action'].value,report.schemes.light.roles['--g-action'].value);assert.deepEqual(r.after,r.before);});
test('unknown selected palette never silently falls back',()=>{const host=fixture();const bad=run('unknown-palette-red',bin,['tokens','validate','--palette','Absent'],host);assert.equal(bad.status,1,bad.stderr);assert.match(bad.stderr,/missing|unknown|not declared/i);assert.deepEqual(bad.after,bad.before);});
test('explicit export creates only requested safe output and identical export is strict noop',()=>{const host=fixture(),r=run('export-safe',bin,['tokens','export','--format','css','--output','exports/tokens.css'],host);assert.equal(r.status,0,r.stderr);const result=JSON.parse(r.stdout),output=path.join(host,result.output);assert.equal(result.hash,hash(fs.readFileSync(output)));const again=run('export-noop',bin,['tokens','export','--format','css','--output','exports/tokens.css'],host);assert.equal(again.status,0,again.stderr);assert.equal(JSON.parse(again.stdout).action,'noop');assert.deepEqual(again.after,again.before);fs.appendFileSync(output,'/* owner export edit */');const conflict=run('export-edited',bin,['tokens','export','--format','css','--output','exports/tokens.css'],host);assert.equal(conflict.status,1);assert.match(conflict.stderr,/conflict/);assert.deepEqual(conflict.after,conflict.before);const cases=['../escape','/absolute','bad\\path','exports/./bad.css','node_modules/tokens.css','gyeol.json','package.json','ui/system/new.css','styles/theme.css'];assert.equal(cases.length,9);for(const target of cases){const bad=run('export-unsafe',bin,['tokens','export','--output',target],host);assert.equal(bad.status,1,target);assert.deepEqual(bad.after,bad.before);}fs.symlinkSync(path.join(host,'absent'),path.join(host,'dangling'));const link=run('export-symlink',bin,['tokens','export','--output','dangling/tokens.css'],host);assert.equal(link.status,1);assert.match(link.stderr,/symlink/);assert.deepEqual(link.after,link.before);});
test('semantic missing role/type/cycle/missing target/parity and unsafe source failures are read-only',()=>{const host=fixture(),config=JSON.parse(fs.readFileSync(path.join(host,'gyeol.json'))),source='ui/system/foundation/tokens.json',sourceFile=path.join(host,source),values=JSON.parse(run('source-reference',bin,['tokens'],host).stdout),palette={replacement:true};for(const scheme of ['light','dark'])palette[scheme]=Object.fromEntries(Object.entries(values.schemes[scheme].roles).map(([name,t])=>[name,{$type:t.type,$value:t.sourceValue}]));fs.writeFileSync(path.join(host,'gyeol.json'),JSON.stringify({...config,tokens:{source,palette:'Owner'}}));const cases=[['missing',p=>delete p.light['--g-surface'],/missing role/],['type',p=>p.light['--g-surface'].$type='dimension',/type mismatch/],['cycle',p=>{p.light['--g-surface'].$value='{--g-ink}';p.light['--g-ink'].$value='{--g-surface}';},/alias cycle/],['target',p=>p.light['--g-surface'].$value='{--g-missing}',/missing alias target/],['parity',p=>p.light['--g-danger'].$value='pink',/parity mismatch/]];assert.equal(cases.length,5);for(const [label,change,reason]of cases){const p=structuredClone(palette);change(p);fs.writeFileSync(sourceFile,JSON.stringify({schemaVersion:1,palettes:{Owner:p}}));const r=run('semantic-negative-'+label,bin,['tokens','validate'],host);assert.equal(r.status,1);assert.match(r.stderr,reason);assert.deepEqual(r.after,r.before);}for(const target of ['../outside','/absolute','node_modules/tokens.json']){const r=run('unsafe-semantic',bin,['tokens','validate','--source',target],host);assert.equal(r.status,1);assert.deepEqual(r.after,r.before);}});

test('preset delta export preserves edited consumer neutral status aliases and custom roles in both formats',()=>{
 const host=fixture(),theme=path.join(host,'ui/system/foundation/theme.css');fs.writeFileSync(theme,fs.readFileSync(theme,'utf8').replace('--g-surface: #FFFFFF;','--g-surface: #123456;').replace('--g-surface: #1E293B;','--g-surface: #234567;').replace(/--g-danger: [^;]+;/g,'--g-danger: rebeccapurple;')+'\n[data-gyeol] { --g-owner-note: owner-note; }\n@theme inline { --color-owner-status: var(--g-danger); --spacing-owner: 1.25rem; }\n');
 const current=JSON.parse(run('delta-current',bin,['tokens'],host).stdout),catalog=JSON.parse(run('delta-catalog',bin,['tokens','presets'],host).stdout);let checked=0;
 for(const format of ['json','css']){const r=run('delta-'+format,bin,['tokens','export','--preset','Silver','--format',format],host);assert.equal(r.status,0,r.stderr);assert.deepEqual(r.after,r.before);
  let result;if(format==='json')result=JSON.parse(r.stdout);else{const output=path.join(host,'exports/silver.css');fs.mkdirSync(path.dirname(output));fs.writeFileSync(output,r.stdout);const config=path.join(host,'gyeol.json');fs.writeFileSync(config,JSON.stringify({schemaVersion:1,sourceRoot:'ui/system',stylePath:'exports/silver.css'}));const parsed=run('delta-css-parity',bin,['tokens','validate','--palette','Silver'],host);assert.equal(parsed.status,0,parsed.stderr);assert.deepEqual(parsed.after,parsed.before);result=JSON.parse(parsed.stdout);}
  for(const scheme of ['light','dark']){const roles=result.schemes[scheme].roles;for(const name of ['--g-surface','--g-danger','--g-owner-note','--spacing-owner','--color-owner-status'])assert.deepEqual(roles[name],current.schemes[scheme].roles[name]);assert.equal(roles['--g-action'].value,catalog.palettes.Silver[scheme]['--g-action'].value);assert.equal(roles['--color-g-action'].value,roles['--g-action'].value);assert.equal(roles['--color-g-surface'].value,roles['--g-surface'].value);assert.equal(roles['--color-owner-status'].alias,'--g-danger');checked++;}
 }
 assert.equal(checked,4);for(const scheme of ['light','dark'])for(const role of ['--g-surface','--g-danger','--g-action'])assert.ok(catalog.palettes.Silver[scheme][role]);
});

test('nested semantic CSS is rejected with actual source location before false semantic parity success',()=>{
 const host=fixture(),theme=path.join(host,'ui/system/foundation/theme.css'),configFile=path.join(host,'gyeol.json'),source='ui/system/foundation/tokens.json';fs.appendFileSync(theme,'\n.sentinel { &:hover { color: pink; } }\n');
 const plain=run('nested-unrelated-supported',bin,['tokens'],host);assert.equal(plain.status,0,plain.stderr);assert.deepEqual(plain.after,plain.before);const current=JSON.parse(plain.stdout),palette={replacement:true};for(const scheme of ['light','dark'])palette[scheme]=Object.fromEntries(Object.entries(current.schemes[scheme].roles).map(([name,t])=>[name,{$type:t.type,$value:t.sourceValue}]));fs.writeFileSync(path.join(host,source),JSON.stringify({schemaVersion:1,palettes:{Owner:palette}}));fs.writeFileSync(configFile,JSON.stringify({...JSON.parse(fs.readFileSync(configFile)),tokens:{source,palette:'Owner'}}));
 const paired=run('nested-parity-before',bin,['tokens'],host);assert.equal(paired.status,0,paired.stderr);assert.deepEqual(paired.after,paired.before);const original=fs.readFileSync(theme,'utf8');const cases=['[data-gyeol] { &[data-theme="dark"] { --g-surface: pink; } }','[data-gyeol] { @media (min-width: 10px) { --g-surface: pink; } }'];assert.equal(cases.length,2);
 for(const css of cases){fs.writeFileSync(theme,original+'\n'+css+'\n');const r=run('nested-semantic-rejection',bin,['tokens','validate'],host);assert.equal(r.status,1,r.stderr);assert.match(r.stderr,/ui\/system\/foundation\/theme\.css:\d+: unsupported semantic nesting/);assert.deepEqual(r.after,r.before);}
});
test('metadata-changing add retains original minified config backup bytes and updates required records',()=>{
 const host=fs.mkdtempSync(path.join(evidence,'config-backup-')),manifest=JSON.parse(fs.readFileSync(path.join(packageRoot,'payload/manifest.json')));fs.writeFileSync(path.join(host,'package.json'),JSON.stringify({name:'config-backup-host',private:true,type:'module',dependencies:{react:'19.2.0','react-dom':'19.2.0',...manifest.runtime},devDependencies:{vite:'7.3.6',...manifest.build,...manifest.types}}));for(const args of [['init'],['add','button']]){const r=run('metadata-prepare',bin,args,host);assert.equal(r.status,0,r.stderr);}
 const configFile=path.join(host,'gyeol.json'),config=JSON.parse(fs.readFileSync(configFile));config.owner={kept:['order',7]};config.tokens={source:'ui/owner.json',palette:'Custom'};const bytes=Buffer.from(JSON.stringify(config));fs.writeFileSync(configFile,bytes);const r=run('metadata-changing-add',bin,['add','input'],host);assert.equal(r.status,0,r.stderr);const updated=JSON.parse(fs.readFileSync(configFile));assert.deepEqual(updated.owner,config.owner);assert.deepEqual(updated.tokens,config.tokens);assert.ok(updated.components.includes('input'));assert.equal(updated.installed[updated.sourceRoot+'/primitives/input.tsx'].hash,manifest.files['primitives/input.tsx'].hash);assert.deepEqual(updated.installed[updated.sourceRoot+'/foundation/theme.css'],config.installed[config.sourceRoot+'/foundation/theme.css']);const paths=Object.keys(snapshot(path.join(host,'.gyeol-backups'))).filter(p=>p.endsWith('/gyeol.json'));const exact=paths.filter(p=>fs.readFileSync(path.join(host,'.gyeol-backups',p)).equals(bytes));assert.equal(exact.length,1);const repeated=run('metadata-changing-then-noop',bin,['add','input'],host);assert.equal(repeated.status,0,repeated.stderr);assert.deepEqual(repeated.after,repeated.before);
});
test('preset export keeps linked authored aliases when CSS has equal literal values',()=>{
 const host=fixture(),theme=path.join(host,'ui/system/foundation/theme.css');fs.writeFileSync(theme,fs.readFileSync(theme,'utf8').replace(/--g-danger: [^;]+;/g,'--g-danger: rebeccapurple;')+'\n@theme inline { --color-owner-status: rebeccapurple; }\n');const current=JSON.parse(run('linked-literal-current',bin,['tokens'],host).stdout),palette={replacement:true};for(const scheme of ['light','dark']){palette[scheme]=Object.fromEntries(Object.entries(current.schemes[scheme].roles).map(([name,t])=>[name,{$type:t.type,$value:t.sourceValue}]));palette[scheme]['--color-owner-status']={$type:'color',$value:'{--g-danger}'};}const source='ui/system/foundation/tokens.json';fs.writeFileSync(path.join(host,source),JSON.stringify({schemaVersion:1,palettes:{Owner:palette}}));const config=path.join(host,'gyeol.json');fs.writeFileSync(config,JSON.stringify({...JSON.parse(fs.readFileSync(config)),tokens:{source,palette:'Owner'}}));const before=snapshot(host);let checked=0;
 for(const args of [[],['--preset','Silver']]){const jsonResult=run('linked-alias-json',bin,['tokens','export',...args],host);assert.equal(jsonResult.status,0,jsonResult.stderr);assert.deepEqual(jsonResult.after,jsonResult.before);const exported=JSON.parse(jsonResult.stdout);for(const scheme of ['light','dark']){const role=exported.schemes[scheme].roles['--color-owner-status'];assert.equal(role.sourceValue,'{--g-danger}');assert.equal(role.alias,'--g-danger');assert.equal(role.value,'rebeccapurple');checked++;}const cssResult=run('linked-alias-css',bin,['tokens','export',...args,'--format','css'],host);assert.equal(cssResult.status,0,cssResult.stderr);assert.match(cssResult.stdout,/--color-owner-status: var\(--g-danger\);/);assert.deepEqual(cssResult.after,cssResult.before);
 const consumer=fs.mkdtempSync(path.join(evidence,'linked-export-consumer-'));fs.mkdirSync(path.join(consumer,'ui'));fs.writeFileSync(path.join(consumer,'gyeol.json'),JSON.stringify({schemaVersion:1,sourceRoot:'ui',stylePath:'export.css'}));fs.writeFileSync(path.join(consumer,'export.css'),cssResult.stdout.replace(/--g-danger: rebeccapurple;/g,'--g-danger: tomato;'));const propagated=run('linked-alias-danger-edit',bin,['tokens','validate','--palette',args.length?'Silver':'Owner'],consumer);assert.equal(propagated.status,0,propagated.stderr);for(const scheme of ['light','dark']){assert.equal(JSON.parse(propagated.stdout).schemes[scheme].roles['--color-owner-status'].value,'tomato');checked++;}assert.deepEqual(propagated.after,propagated.before);
 }assert.equal(checked,8);assert.deepEqual(snapshot(host),before);
});

test('prototype property names are unknown presets and cannot write exports',()=>{
 const cases=['constructor','__proto__'],observed=[];assert.equal(cases.length,2);
 for(const name of cases){const host=fixture(),target='exports/'+name+'.json',r=run('prototype-preset-'+name,bin,['tokens','export','--preset',name,'--output',target],host);observed.push({name,target,host,r});}
 for(const {name,target,host,r}of observed){assert.equal(r.status,1,name+' must be rejected as an unregistered preset');assert.match(r.stderr,new RegExp('Unknown preset '+name+'; no fallback'));assert.deepEqual(r.after,r.before);assert.equal(fs.existsSync(path.join(host,target)),false);}
});

test('scheme-specific linked aliases keep CSS meaning for both and dark-only exports',async()=>{
 const host=fixture(),theme=path.join(host,'ui/system/foundation/theme.css');fs.writeFileSync(theme,fs.readFileSync(theme,'utf8').replace(/--g-(danger|overlay): [^;]+;/g,'--g-$1: rebeccapurple;')+'\n@theme inline { --color-owner-status: rebeccapurple; }\n');const css=fs.readFileSync(theme,'utf8'),current=JSON.parse(run('scheme-current',bin,['tokens'],host).stdout),palette={replacement:true};for(const mode of ['light','dark']){palette[mode]=Object.fromEntries(Object.entries(current.schemes[mode].roles).map(([n,t])=>[n,{$type:t.type,$value:t.sourceValue}]));palette[mode]['--color-owner-status']={$type:'color',$value:mode==='light'?'{--g-danger}':'{--g-overlay}'};}const source='ui/system/foundation/tokens.json';fs.writeFileSync(path.join(host,source),JSON.stringify({schemaVersion:1,palettes:{Owner:palette}}));fs.writeFileSync(path.join(host,'gyeol.json'),JSON.stringify({...JSON.parse(fs.readFileSync(path.join(host,'gyeol.json'))),tokens:{source,palette:'Owner'}}));const original=snapshot(host),observed=[];
 const {default:postcss}=await import('postcss');
 for(const preset of [null,'Silver'])for(const scheme of [null,'dark']){const args=[...(preset?['--preset',preset]:[]),...(scheme?['--scheme',scheme]:[])],data=run('scheme-json',bin,['tokens','export',...args],host);assert.equal(data.status,0,data.stderr);assert.deepEqual(data.after,data.before);const output=JSON.parse(data.stdout);for(const mode of scheme?[scheme]:['light','dark'])assert.equal(output.schemes[mode].roles['--color-owner-status'].alias,mode==='light'?'--g-danger':'--g-overlay');const r=run('scheme-css',bin,['tokens','export',...args,'--format','css'],host);assert.equal(r.status,0,r.stderr);assert.deepEqual(r.after,r.before);const ast=postcss.parse(r.stdout);let edits=0;ast.walkRules(rule=>{if(rule.selector.includes('data-theme="dark"'))for(const d of rule.nodes??[])if(d.type==='decl'&&d.prop==='--g-overlay'){d.value='tomato';edits++;}});assert.equal(edits,1);const consumer=fs.mkdtempSync(path.join(evidence,'scheme-export-consumer-'));fs.mkdirSync(path.join(consumer,'ui'));fs.writeFileSync(path.join(consumer,'gyeol.json'),JSON.stringify({schemaVersion:1,sourceRoot:'ui',stylePath:'export.css'}));fs.writeFileSync(path.join(consumer,'export.css'),(scheme?css+'\n':'')+ast.toString());const result=run('scheme-overlay-edit',bin,['tokens','validate','--palette',preset??'Owner'],consumer);assert.equal(result.status,0,result.stderr);assert.deepEqual(result.after,result.before);observed.push({preset,scheme,css:r.stdout,roles:JSON.parse(result.stdout).schemes});}
 assert.equal(observed.length,4);for(const result of observed){assert.equal(result.roles.dark.roles['--color-owner-status'].value,'tomato','exported dark alias must follow overlay rather than light danger');if(!result.scheme)assert.equal(result.roles.light.roles['--color-owner-status'].value,'rebeccapurple');}
 const {compile}=await import('tailwindcss');const compiler=[];for(const result of observed){const out=(await compile(result.css+'\n@tailwind utilities;\n')).build(['text-owner-status']);assert.match(out,/\.text-owner-status/);assert.match(out,/color: var\(--(?:g-export-color-owner-status|g-overlay)\)/);compiler.push({preset:result.preset,scheme:result.scheme,css:out,hash:hash(Buffer.from(out))});}fs.writeFileSync(path.join(evidence,'scheme-source-compiler.json'),JSON.stringify({mode:'actual Tailwind compile/build, not browser cascade',version:JSON.parse(fs.readFileSync(path.join(repo,'node_modules/tailwindcss/package.json'))).version,compiler},null,2));assert.deepEqual(snapshot(host),original);
});

test('semantic selectors preserve compound structure and refuse descendant/combinator contexts read-only',()=>{
 const host=fixture(),theme=path.join(host,'ui/system/foundation/theme.css'),original=fs.readFileSync(theme,'utf8');const cases=['[data-gyeol] [data-theme="dark"]','[data-gyeol]\t[data-theme="dark"]','[data-gyeol]\n[data-theme="dark"]','[data-gyeol] > [data-theme="dark"]','[data-gyeol]+[data-theme="dark"]','[data-gyeol]~[data-theme="dark"]'],observed=[];assert.equal(cases.length,6);
 for(const selector of cases){fs.writeFileSync(theme,original+'\n'+selector+' { --g-surface: pink; }\n');observed.push({selector,r:run('selector-negative',bin,['tokens','validate'],host)});}
 for(const {selector,r}of observed){assert.equal(r.status,1,selector+' must not be misclassified as a compound root');assert.match(r.stderr,/ui\/system\/foundation\/theme\.css:\d+: unsupported semantic selector structure/);assert.deepEqual(r.after,r.before);}
 const positives=['[data-gyeol][data-theme="dark"]','[ data-gyeol ][ data-theme = "dark" ]','[data-gyeol][data-theme = dark]'];assert.equal(positives.length,3);for(const selector of positives){fs.writeFileSync(theme,original+'\n'+selector+' { --g-surface: pink; }\n.sentinel > .child { color: tomato; }\n.sentinel { &:hover { color: pink; } }\n');const r=run('selector-compound-positive',bin,['tokens'],host);assert.equal(r.status,0,r.stderr);assert.equal(JSON.parse(r.stdout).schemes.dark.roles['--g-surface'].value,'pink');assert.equal(JSON.parse(r.stdout).schemes.light.roles['--g-surface'].value,'#FFFFFF');assert.deepEqual(r.after,r.before);}
});

test('scoped typed namespaces follow scheme cascade and reject knownType-only descendants',()=>{
 const host=fixture(),theme=path.join(host,'ui/system/foundation/theme.css'),original=fs.readFileSync(theme,'utf8');
 const scopes='\n@theme inline { --color-owner: rebeccapurple; --font-owner: Alpha; --text-owner: 1rem; --radius-owner: 2px; --spacing-owner: 3px; }\n[data-gyeol] { --g-danger: var(--color-owner); }\n[data-gyeol][data-theme="dark"] { --color-owner: pink; --font-owner: Beta; --text-owner: 2rem; --radius-owner: 4px; --spacing-owner: 5px; }\n.host > .child { color: tomato; }\n';
 fs.writeFileSync(theme,original+scopes);const r=run('typed-scope',bin,['tokens'],host);assert.equal(r.status,0,r.stderr);const report=JSON.parse(r.stdout);assert.equal(report.schemes.dark.roles['--g-danger'].value,'pink');assert.equal(report.schemes.light.roles['--g-danger'].value,'rebeccapurple');const expected={'--color-owner':'pink','--font-owner':'Beta','--text-owner':'2rem','--radius-owner':'4px','--spacing-owner':'5px'};assert.equal(Object.keys(expected).length,5);for(const [name,value]of Object.entries(expected))assert.equal(report.schemes.dark.roles[name].value,value);assert.deepEqual(r.after,r.before);
 const exported=run('typed-scope-css',bin,['tokens','export','--format','css'],host);assert.equal(exported.status,0,exported.stderr);fs.writeFileSync(theme,exported.stdout);const roundtrip=run('typed-scope-roundtrip',bin,['tokens'],host);assert.equal(roundtrip.status,0,roundtrip.stderr);assert.equal(JSON.parse(roundtrip.stdout).schemes.dark.roles['--g-danger'].value,'pink');assert.deepEqual(roundtrip.after,roundtrip.before);
 const selectors=['[data-gyeol] [data-theme="dark"]','[data-gyeol]\t[data-theme="dark"]','[data-gyeol]\n[data-theme="dark"]','[data-gyeol]>[data-theme="dark"]','[data-gyeol]+[data-theme="dark"]'];assert.equal(selectors.length,5);for(const selector of selectors){fs.writeFileSync(theme,original+'\n'+selector+' { --color-owner: pink; }\n');const bad=run('typed-scope-structure',bin,['tokens'],host);assert.equal(bad.status,1,selector);assert.match(bad.stderr,/ui\/system\/foundation\/theme\.css:\d+: unsupported semantic selector structure/);assert.deepEqual(bad.after,bad.before);}
});

test('semantic scope rejects repeated attributes and validates empty palette registrations consistently',()=>{
 const host=fixture(),theme=path.join(host,'ui/system/foundation/theme.css'),original=fs.readFileSync(theme,'utf8'),cases=[['[data-gyeol][data-theme="light"][data-theme="dark"]','--g-surface: pink;','theme'],['[data-gyeol][data-palette="A"][data-palette="B"]','--g-surface: pink;','palette'],["[ data-gyeol ][ data-theme = 'light' ][ data-theme = dark ]",'--g-surface: pink;','theme'],['[data-gyeol][data-theme="dark"][data-theme="dark"]','--g-surface: pink;','theme'],['[data-gyeol][data-palette="A"][data-palette="B"][data-theme="dark"]','','palette'],["[ data-gyeol ][ data-palette = 'A' ][ data-palette = B ]",'','palette']],observed=[];assert.equal(cases.length,6);
 for(const [selector,decl,attribute]of cases){fs.writeFileSync(theme,original+'\n'+selector+' { '+decl+' }\n');const r=run('scope-duplicate',bin,['tokens','export','--output','exports/rejected-'+observed.length+'.json'],host);observed.push({selector,attribute,...r});}for(const r of observed){assert.equal(r.status,1,r.selector+' must reject repeated attribute');assert.match(r.stderr,new RegExp('ui/system/foundation/theme\\.css:\\d+: duplicate semantic '+r.attribute+' attribute'));assert.deepEqual(r.after,r.before);}
 const positives=["[ data-gyeol ][ data-palette = 'Owner' ][ data-theme = dark ]",'[data-gyeol][data-theme="dark"][data-palette="Owner"]','[data-gyeol][data-palette="Owner"]'];assert.equal(positives.length,3);for(const selector of positives){fs.writeFileSync(theme,original+'\n'+selector+' { }\n.host[data-palette="Other"] { color: pink; }\n');const r=run('scope-registration',bin,['tokens','validate','--palette','Owner'],host);assert.equal(r.status,0,r.stderr);assert.ok(JSON.parse(r.stdout).declaredPalettes.includes('Owner'));assert.deepEqual(r.after,r.before);}
});

test('repeated CSS imports retain a b a source order while active import cycles fail read-only',()=>{
 const host=fixture(),style=path.join(host,'styles/theme.css');fs.writeFileSync(path.join(host,'styles/override.css'),'[data-gyeol] { --g-surface: pink; }\n');fs.writeFileSync(style,'@import "../ui/system/foundation/theme.css";\n@import "./override.css";\n@import "../ui/system/foundation/theme.css";\n.host { color: tomato; }\n');const r=run('import-repeat',bin,['tokens','export'],host);assert.equal(r.status,0,r.stderr);const report=JSON.parse(r.stdout);assert.equal(report.schemes.light.roles['--g-surface'].value,'#FFFFFF');assert.equal(report.schemes.dark.roles['--g-surface'].value,'#1E293B');assert.deepEqual(report.inputs.map(i=>i.path),['styles/theme.css','ui/system/foundation/theme.css','styles/override.css','ui/system/foundation/theme.css']);assert.equal(report.inputs[1].hash,report.inputs[3].hash);assert.deepEqual(r.after,r.before);
 const css=run('import-repeat-css',bin,['tokens','export','--format','css'],host);assert.equal(css.status,0,css.stderr);assert.match(css.stdout,/--g-surface: #FFFFFF/);assert.match(css.stdout,/--g-surface: #1E293B/);assert.deepEqual(css.after,css.before);fs.writeFileSync(path.join(host,'styles/override.css'),'@import "./theme.css";\n');const bad=run('import-cycle',bin,['tokens','export','--output','exports/rejected.json'],host);assert.equal(bad.status,1,bad.stderr);assert.match(bad.stderr,/CSS import cycle: styles\/theme\.css -> styles\/override\.css -> styles\/theme\.css/);assert.deepEqual(bad.after,bad.before);
});

test('imports reject unsupported ancestor grammar before target reads and preserve root layer arrangements',()=>{
 const host=fixture(),style=path.join(host,'styles/theme.css'),base=fs.readFileSync(style,'utf8');fs.writeFileSync(path.join(host,'styles/override.css'),'[data-gyeol] { --g-surface: pink; }\n');const cases=['@media (min-width:800px) { @import "./override.css"; }','@supports (display:grid) { @import "./override.css"; }','@container owner (width>1px) { @import "./override.css"; }','@media (min-width:800px) { @layer owner { @import "./override.css"; } }','.host { @import "./override.css"; }','.host { @supports (display:grid) { @import "./override.css"; } }','@theme inline { @import "./override.css"; }','@unknown { @import "./override.css"; }','@media (min-width:800px) { @import "./missing.css"; }'],observed=[];assert.equal(cases.length,9);
 for(const css of cases){fs.writeFileSync(style,base+'\n'+css+'\n');const r=run('ancestor-import',bin,['tokens','export','--output','exports/rejected-'+observed.length+'.json'],host);observed.push({inputCSS:base+'\n'+css+'\n',...r});}fs.writeFileSync(path.join(evidence,'ancestor-import-source-cases-'+process.hrtime.bigint()+'.json'),JSON.stringify(observed,null,2));for(const r of observed){assert.equal(r.status,1,r.inputCSS);assert.match(r.stderr,/styles\/theme\.css:\d+: unsupported CSS import context/);assert.doesNotMatch(r.stderr,/ENOENT/);assert.deepEqual(r.after,r.before);}
 const positives=['@import "./override.css";','@import "./override.css" layer(owner);','@layer owner { @import "./override.css"; }','@layer owner { @layer inner { @import "./override.css"; } }'];assert.equal(positives.length,4);for(const css of positives){fs.writeFileSync(style,base+'\n'+css+'\n@media (min-width:800px) { .host { color: pink; } }\n.host { @supports (display:grid) { color: tomato; } }\n');const r=run('ancestor-import-positive',bin,['tokens'],host);assert.equal(r.status,0,r.stderr);assert.equal(JSON.parse(r.stdout).schemes.light.roles['--g-surface'].value,'pink');assert.deepEqual(r.after,r.before);}
 fs.writeFileSync(style,base+'\n@supports (display:grid) { [data-gyeol] { --g-surface: pink; } }\n');const direct=run('ancestor-direct-semantic',bin,['tokens'],host);assert.equal(direct.status,1,direct.stderr);assert.match(direct.stderr,/unsupported conditional\/nested semantic @supports/);assert.deepEqual(direct.after,direct.before);
});

test('theme parameters accept only empty or inline forms with actual source locations',()=>{
 const host=fixture(),theme=path.join(host,'ui/system/foundation/theme.css'),base=fs.readFileSync(theme,'utf8'),params=['reference','static','default','inline reference','inline inline','owner'],observed=[];assert.equal(params.length,6);for(const value of params){const inputCSS=base+'\n@theme '+value+' { --color-owner: pink; }\n';fs.writeFileSync(theme,inputCSS);observed.push({inputCSS,value,...run('theme-params',bin,['tokens','export','--output','exports/rejected-'+observed.length+'.json'],host)});}fs.writeFileSync(path.join(evidence,'theme-params-source-cases-'+process.hrtime.bigint()+'.json'),JSON.stringify(observed,null,2));for(const r of observed){assert.equal(r.status,1,r.value);assert.match(r.stderr,/ui\/system\/foundation\/theme\.css:\d+: unsupported @theme parameters/);assert.deepEqual(r.after,r.before);}
 const positives=['@theme { --color-owner: pink; }','@theme   inline { --color-owner: pink; }','@layer owner { @theme inline { --color-owner: pink; } }'];assert.equal(positives.length,3);for(const css of positives){fs.writeFileSync(theme,base+'\n'+css+'\n');const r=run('theme-params-positive',bin,['tokens'],host);assert.equal(r.status,0,r.stderr);assert.equal(JSON.parse(r.stdout).schemes.light.roles['--color-owner'].value,'pink');assert.deepEqual(r.after,r.before);}
});
test('direct semantic placement is never silently omitted outside a rule or supported theme',()=>{
 const host=fixture(),theme=path.join(host,'ui/system/foundation/theme.css'),base=fs.readFileSync(theme,'utf8'),cases=['@layer owner { --g-surface: pink; }','@layer owner { --color-owner: pink; }','--font-owner: Owner;','@layer owner { --text-owner: 1rem; }','@layer owner { --radius-owner: 2px; }','@layer owner { --spacing-owner: 3px; }','--g-owner-note: kept;','@supports (display:grid) { --g-surface: pink; }','@font-face { --g-surface: pink; }','@theme inline { --g-owner-note: kept; }'],observed=[];assert.equal(cases.length,10);for(const css of cases){const inputCSS=base+'\n'+css+'\n';fs.writeFileSync(theme,inputCSS);observed.push({inputCSS,...run('semantic-placement',bin,['tokens','export','--output','exports/rejected-'+observed.length+'.json'],host)});}fs.writeFileSync(path.join(evidence,'semantic-placement-source-cases-'+process.hrtime.bigint()+'.json'),JSON.stringify(observed,null,2));for(const r of observed){assert.equal(r.status,1,r.inputCSS);assert.match(r.stderr,/ui\/system\/foundation\/theme\.css:\d+: unsupported semantic declaration placement/);assert.deepEqual(r.after,r.before);}
 fs.writeFileSync(theme,base+'\n@layer owner { .host { color: pink; } }\n@media (min-width:800px) { .host { color: tomato; } }\n@font-face { font-family: Owner; src: url("local.woff2"); }\n[data-gyeol] { --g-owner-note: kept; }\n');const hostOnly=run('placement-host-only',bin,['tokens'],host);assert.equal(hostOnly.status,0,hostOnly.stderr);assert.equal(JSON.parse(hostOnly.stdout).schemes.light.roles['--g-owner-note'].sourceValue,'kept');assert.deepEqual(hostOnly.after,hostOnly.before);
});
