import { useState } from 'react';
import { Theme } from './gyeol/foundation/theme';
import { Button, type ButtonProps } from './gyeol/primitives/button';
import { Input } from './gyeol/primitives/input';
import { TextField } from './gyeol/components/text-field';
import { Select } from './gyeol/primitives/select';
import { Tabs,TabsList,TabsTrigger,TabsContent } from './gyeol/primitives/tabs';
import { Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription,DialogClose } from './gyeol/primitives/dialog';
import { FormSection,ListPanel } from './gyeol/components/composition';
import { List,ListItem,Row,Stack } from './gyeol/primitives/layout';
import { TaskExample } from './task-example';
import { Customization } from './customization';
import { BehaviorProofs } from './proofs';
const pages=['Overview','TaskExample','Foundations','Button','Input','TextField','Select','Tabs','Dialog','Layout','List','FormSection','ListPanel','Customization','Behavior'];
const references:Record<string,string>={
 Button:'HTMLButtonElement ref. native props, type="button" 기본값. variant: primary | secondary | quiet, size: small | medium. loading은 disabled와 aria-busy를 적용합니다. asChild는 지원하지 않습니다.',
 Input:'HTMLInputElement ref와 native props/className은 실제 input에 전달됩니다. invalid는 error boundary, loading은 aria-busy만 바꿉니다. DOM을 교체하거나 값을 지우지 않습니다.',
 TextField:'ref/className/native props는 실제 input, wrapperProps는 외부 div입니다. value + onValueChange로 제어하거나 defaultValue로 비제어합니다. clear는 onValueChange("")를 알립니다. 합성 ChangeEvent나 DOM value mutation은 하지 않습니다. 비제어 native reset은 최초 defaultValue를 복원하며 제어 reset은 owner 책임입니다.',
 Select:'ref는 HTMLButtonElement Trigger입니다. options, value/defaultValue, onValueChange(string), name, required를 지원합니다. Radix가 keyboard/typeahead/focus를 관리합니다. 비제어 native reset은 defaultValue로 돌아갑니다. 제어 form reset은 최초 값(defaultValue 또는 최초 value)을 onValueChange로 요청합니다. owner는 이를 적용하거나 form의 reset을 preventDefault해야 합니다. 값은 owner 소유이며 묵시 DOM mutation을 하지 않습니다. FormData는 Radix hidden native select로 전달됩니다. HTMLSelectElement/ChangeEvent 호환 API가 아닙니다.',
 Tabs:'Radix Root value/defaultValue/onValueChange, activationMode automatic/manual, orientation. TabsList ref HTMLDivElement, TabsTrigger ref HTMLButtonElement, TabsContent는 Radix Content API. disabled trigger는 roving focus에서 빠집니다. 예제 state는 docs 패널 밖에서 소유합니다.',
 Dialog:'Radix Root open/defaultOpen/onOpenChange. Content ref HTMLDivElement. Trigger ref HTMLButtonElement (asChild일 때 실제 child). Title HTMLHeadingElement, Description HTMLParagraphElement. 기본 trigger focus return은 Radix 책임입니다. trigger 없는/초기 open/async close는 Content returnFocusRef로 복귀 대상을 지정합니다. 직접 showModal/focus engine을 병행하지 않습니다.',
 Layout:'Stack/Row ref HTMLDivElement, native props 전달. Stack은 세로 흐름, Row는 줄바꿈 가능한 가로 흐름입니다. className은 layout utility 용도로 사용합니다.',
 List:'List ref HTMLUListElement, ListItem ref HTMLLIElement. ul/li semantics와 행 구분을 소유합니다. 업무 상태나 backend enum을 포함하지 않습니다.',
 FormSection:'section ref HTMLElement. heading/description/actions와 children을 조합합니다. form submit과 값의 소유자는 소비자입니다.',
 ListPanel:'section ref HTMLElement. heading/description/actions 아래에 native List를 배치합니다. children은 ListItem이며 empty/loading은 예제 owner가 렌더합니다.',
};
function ExampleWorkbench({page}:{page:string}){
 const [value,setValue]=useState('읽고, 정리하고, 이어 가기'),[variant,setVariant]=useState<NonNullable<ButtonProps['variant']>>('primary'),[disabled,setDisabled]=useState(false),[count,setCount]=useState(0),[selected,setSelected]=useState('first'),[tab,setTab]=useState('one'),[open,setOpen]=useState(false),[panel,setPanel]=useState('variant');
 const reset=()=>{setValue('읽고, 정리하고, 이어 가기');setVariant('primary');setDisabled(false);setCount(0);setSelected('first');setTab('one');setOpen(false);};
 const options=[{value:'first',label:'첫 번째'},{value:'second',label:'두 번째'}];
 let live,code;
 if(page==='Button'){live=<Row><Button variant={variant} disabled={disabled} onClick={()=>setCount(current=>current+1)}>계속하기</Button><p className="text-g-small text-g-soft">{count}번 실행</p></Row>;code=`<Button variant=${JSON.stringify(variant)} disabled={${disabled}} onClick={() => setCount(c => c + 1)}>계속하기</Button>\n// 현재 count = ${count}`;}
 else if(page==='Input'){live=<Input aria-label="입력 예제" value={value} onChange={event=>setValue(event.target.value)} disabled={disabled}/>;code=`<Input aria-label="입력 예제" value={${JSON.stringify(value)}} onChange={e => setValue(e.target.value)} disabled={${disabled}} />`;}
 else if(page==='TextField'){live=<TextField label="제목" value={value} onValueChange={setValue} disabled={disabled} clearable/>;code=`<TextField label="제목" value={${JSON.stringify(value)}} onValueChange={setValue} disabled={${disabled}} clearable />`;}
 else if(page==='Select'){live=<Select label="선택 예제" value={selected} onValueChange={setSelected} disabled={disabled} options={options}/>;code=`<Select label="선택 예제" value=${JSON.stringify(selected)} onValueChange={setSelected} disabled={${disabled}} options={${JSON.stringify(options)}} />`;}
 else if(page==='Tabs'){live=<Tabs value={tab} onValueChange={setTab}><TabsList aria-label="예제 탭"><TabsTrigger value="one">첫 화면</TabsTrigger><TabsTrigger value="two" disabled={disabled}>다음 화면</TabsTrigger></TabsList><TabsContent value="one" className="mt-4">차분하게 시작하세요.</TabsContent><TabsContent value="two" className="mt-4">다음 단계로 이어 갑니다.</TabsContent></Tabs>;code=`<Tabs value=${JSON.stringify(tab)} onValueChange={setTab}>\n  <TabsList aria-label="예제 탭">\n    <TabsTrigger value="one">첫 화면</TabsTrigger>\n    <TabsTrigger value="two" disabled={${disabled}}>다음 화면</TabsTrigger>\n  </TabsList>\n  <TabsContent value="one">차분하게 시작하세요.</TabsContent>\n  <TabsContent value="two">다음 단계로 이어 갑니다.</TabsContent>\n</Tabs>`;}
 else if(page==='Dialog'){live=<Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button disabled={disabled}>안내 열기</Button></DialogTrigger><DialogContent><DialogTitle>한 걸음씩</DialogTitle><DialogDescription>내용을 확인하고 다음 작업으로 이어 가세요.</DialogDescription><DialogClose asChild><Button>확인</Button></DialogClose></DialogContent></Dialog>;code=`<Dialog open={${open}} onOpenChange={setOpen}>\n  <DialogTrigger asChild><Button disabled={${disabled}}>안내 열기</Button></DialogTrigger>\n  <DialogContent>\n    <DialogTitle>한 걸음씩</DialogTitle>\n    <DialogDescription>내용을 확인하고 다음 작업으로 이어 가세요.</DialogDescription>\n    <DialogClose asChild><Button>확인</Button></DialogClose>\n  </DialogContent>\n</Dialog>`;}
 else if(page==='Layout'){live=<Stack><p>자연스러운 세로 흐름</p><Row><Button variant="secondary">이전</Button><Button>다음</Button></Row></Stack>;code='<Stack>\n  <p>자연스러운 세로 흐름</p>\n  <Row><Button variant="secondary">이전</Button><Button>다음</Button></Row>\n</Stack>';}
 else if(page==='FormSection'){live=<FormSection heading="기본 정보" description="필요한 것만 입력하세요."><TextField label="이름" value={value} onValueChange={setValue}/></FormSection>;code=`<FormSection heading="기본 정보" description="필요한 것만 입력하세요.">\n  <TextField label="이름" value={${JSON.stringify(value)}} onValueChange={setValue} />\n</FormSection>`;}
 else if(page==='ListPanel'){live=<ListPanel heading="메모" description="1개의 항목"><ListItem>{value}</ListItem></ListPanel>;code=`<ListPanel heading="메모" description="1개의 항목"><ListItem>${value}</ListItem></ListPanel>`;}
 else{live=<List><ListItem>오늘의 첫 작업</ListItem><ListItem>다음에 이어 갈 작업</ListItem></List>;code='<List><ListItem>오늘의 첫 작업</ListItem><ListItem>다음에 이어 갈 작업</ListItem></List>';}
 return <div className="grid gap-7"><section aria-label="Live example" className="grid gap-4 border-0 border-y border-solid border-g-line py-8"><div className="flex items-center justify-between gap-3"><h2 className="text-g-small text-g-soft font-medium">LIVE EXAMPLE</h2><Button variant="quiet" size="small" onClick={reset}>Reset</Button></div>{live}</section><Tabs value={panel} onValueChange={setPanel}><TabsList aria-label="예제 설명"><TabsTrigger value="variant">Variant</TabsTrigger><TabsTrigger value="code">Code</TabsTrigger><TabsTrigger value="docs">Docs</TabsTrigger></TabsList><TabsContent value="variant" className="mt-5"><div className="flex flex-wrap items-center gap-4">{page==='Button' && <Select label="Button variant" value={variant} onValueChange={v=>setVariant(v as NonNullable<ButtonProps['variant']>)} options={[{value:'primary',label:'Primary'},{value:'secondary',label:'Secondary'},{value:'quiet',label:'Quiet'}]}/>}{['Button','Input','TextField','Select','Tabs','Dialog'].includes(page) && <label className="flex gap-2 items-center"><input type="checkbox" checked={disabled} onChange={event=>setDisabled(event.target.checked)}/> Disabled</label>}<p className="text-g-small text-g-soft">위의 실제 예제에서 값을 바꾸면 Code에도 반영됩니다.</p></div></TabsContent><TabsContent value="code" className="mt-5"><pre className="whitespace-pre-wrap break-words text-g-small bg-g-muted p-4 rounded-g-control"><code>{code}</code></pre></TabsContent><TabsContent value="docs" className="mt-5"><p className="leading-7 text-g-soft">{references[page]}</p></TabsContent></Tabs></div>;
}
function Foundations(){return <div className="grid gap-8"><p className="text-g-soft leading-7">한결디자인은 정보와 행동의 관계를 읽기 쉽게 만드는 디자인 시스템입니다. 따뜻한 바탕, 분명한 잉크, 절제된 올리브 액션을 사용합니다. Pretendard와 여유 있는 행간으로 긴 한국어 문장을 편하게 읽습니다.</p><section className="grid grid-cols-2 gap-4 sm:grid-cols-4"><div className="bg-g-surface border border-solid border-g-line p-4"><p className="font-medium">Surface</p><p className="text-g-small text-g-soft">내용의 자리</p></div><div className="bg-g-muted p-4"><p className="font-medium">Muted</p><p className="text-g-small text-g-soft">보조 영역</p></div><div className="bg-g-action text-g-on-action p-4"><p className="font-medium">Action</p><p className="text-g-small">중요한 다음 행동</p></div><div className="border border-solid border-g-line p-4"><p className="text-g-danger font-medium">Error</p><p className="text-g-small text-g-soft">복구할 수 있는 안내</p></div></section><div className="grid gap-3"><h2 className="text-g-title font-semibold">여백으로 구분하고, 글로 설명합니다.</h2><p className="text-g-body">본문 16px · 작은 설명 14px · 제목 32px</p><p className="text-g-small text-g-soft">44px 이상의 조작 영역, 별도의 focus outline과 error border. Root/중첩 테마는 portal에도 이어집니다.</p></div><Button>다음 작업으로</Button></div>;}
function Overview({onNavigate}:{onNavigate:(page:string)=>void}){
 return <div className="grid gap-8">
  <p className="text-g-body leading-7 text-g-soft">필수 개발 도구는 core로 설치하고, UI 소스는 내 프로젝트에서 직접 수정합니다.</p>
  <div className="flex flex-wrap items-center gap-4">
   <a href="https://github.com/orderthan31/design-system/blob/f5138d67c86f965747ba2d1b187a69c008caf68b/docs/source-installation.md#core11-quickstart" className="text-g-action underline underline-offset-4">설치 안내</a>
   <Button variant="secondary" onClick={()=>onNavigate('Button')}>컴포넌트 문서</Button>
   <Button variant="quiet" onClick={()=>onNavigate('TaskExample')}>대표 소비 예제</Button>
  </div>
  <section aria-label="소스 설치와 편집" className="grid gap-7">
   <div className="grid gap-2"><h2 className="text-lg font-semibold">개발 도구는 core로</h2><p className="leading-7 text-g-soft"><code>hangyeol-core</code>를 버전이 고정된 devDependency로 설치합니다. 프로젝트의 로컬 <code>node_modules/.bin/hangyeol</code> 명령으로 초기 설정을 만들고, 필요한 컴포넌트 소스만 선택해 추가합니다.</p></div>
   <div className="grid gap-2"><h2 className="text-lg font-semibold">UI는 내 프로젝트의 소스로</h2><p className="leading-7 text-g-soft">선택한 컴포넌트와 공통 helper, theme은 프로젝트에 복사되는 편집 가능한 로컬 파일입니다. 컴포넌트 문서에서 공개 API를 확인하고, 프로젝트에 맞게 소스를 직접 수정하세요.</p></div>
   <div className="grid gap-2"><h2 className="text-lg font-semibold">팔레트도 직접 편집</h2><p className="leading-7 text-g-soft">제공된 팔레트의 값을 바꾸거나 새 팔레트를 추가할 수 있습니다. light와 dark 테마, 의미와 상태를 나타내는 토큰도 프로젝트에서 관리합니다.</p></div>
  </section>
  <p className="text-g-small leading-6 text-g-soft">현재 설치 안내는 준비된 캐시(prepared-cache)와 설치 스크립트 비활성화(scripts-off)를 사용한 검증 범위를 설명합니다. 안내를 읽으려면 저장소 접근 권한이 필요합니다.</p>
 </div>;
}
export default function App(){const [page,setPage]=useState('Overview'),[search,setSearch]=useState(''),[mode,setMode]=useState<'light'|'dark'>('light');const navigate=(name:string)=>{setPage(name);window.location.hash=name;};return <Theme mode={mode} className="min-h-screen"><div className="mx-auto grid max-w-7xl lg:grid-cols-5"><aside className="border-0 border-b border-solid border-g-line min-w-0 p-5 lg:col-span-1 lg:min-h-screen lg:border-b-0 lg:border-r lg:p-7"><div className="flex items-center justify-between gap-2"><a href="#Overview" onClick={()=>setPage('Overview')} className="no-underline text-xl font-semibold tracking-tight">한결디자인</a><Button variant="quiet" size="small" aria-label="테마 변경" onClick={()=>setMode(m=>m==='light'?'dark':'light')}>{mode==='light'?'◐':'◑'}</Button></div><div className="mt-6"><Input aria-label="문서 검색" placeholder="Search docs" value={search} onChange={event=>setSearch(event.target.value)}/></div><nav aria-label="API menu" className="mt-5 flex gap-1 overflow-x-auto lg:flex-col lg:overflow-visible">{pages.filter(p=>p.toLowerCase().includes(search.toLowerCase())).map(name=><Button key={name} variant={page===name?'secondary':'quiet'} size="small" className="shrink-0 justify-start" aria-current={page===name?'page':undefined} onClick={()=>navigate(name)}>{name}</Button>)}</nav><p className="mt-8 text-g-small text-g-soft hidden lg:block">작업에 필요한 만큼.<br/>소스는 당신의 프로젝트에.</p></aside><main className="min-w-0 px-5 py-8 sm:px-10 lg:col-span-4 lg:px-14 lg:py-12"><div className="mb-8 flex items-baseline justify-between gap-3"><h1 className="text-g-title font-semibold tracking-tight">{page==='Overview'?'한결디자인':page}</h1><span className="text-g-small text-g-soft">한결디자인 · 01</span></div>{page==='Overview'?<Overview onNavigate={navigate}/>:page==='TaskExample'?<TaskExample/>:page==='Foundations'?<Foundations/>:page==='Customization'?<div className="grid gap-6"><p className="text-g-soft">이 페이지는 설치된 소스의 className 병합 계약을 검증하는 명시적인 예외입니다. 일반 문서는 공개 variant/size를 사용합니다.</p><Customization/></div>:page==='Behavior'?<BehaviorProofs/>:<ExampleWorkbench key={page} page={page}/>}</main></div></Theme>;}
