import { useRef, useState } from 'react';
import { Button } from './gyeol/primitives/button';
import { Input } from './gyeol/primitives/input';
import { TextField } from './gyeol/components/text-field';
import { Select } from './gyeol/primitives/select';
import { Theme } from './gyeol/foundation/theme';
import { Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription,DialogClose } from './gyeol/primitives/dialog';
import { Tabs,TabsList,TabsTrigger,TabsContent } from './gyeol/primitives/tabs';
export function BehaviorProofs(){const [mode,setMode]=useState<'light'|'dark'>('light'),[value,setValue]=useState('first'),[busy,setBusy]=useState(false),[output,setOutput]=useState(''),[field,setField]=useState('유지되는 값');const ref=useRef<HTMLInputElement|null>(null);
 const options=[{value:'first',label:'첫 번째'},{value:'second',label:'두 번째'},{value:'blocked',label:'선택 불가',disabled:true}];
 return <Theme mode={mode}><div className="grid gap-6 p-4"><Button variant="secondary" onClick={()=>setMode(current=>current==='light'?'dark':'light')}>중첩 테마 변경</Button><form data-testid="proof-form" className="grid gap-4" onSubmit={event=>{event.preventDefault();setOutput(JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))));}}><Select label="비제어 선택" name="uncontrolled" required defaultValue="first" options={options}/><Select label="제어 선택" name="controlled" value={value} onValueChange={setValue} options={options}/><TextField label="비제어 입력" name="uncontrolledText" defaultValue="처음" clearable/><TextField ref={ref} label="제어 입력" name="controlledText" value={field} onValueChange={setField} clearable loading={busy}/><Input aria-label="읽기 전용" readOnly value="읽기 전용"/><Button type="submit">FormData 확인</Button><Button variant="secondary" type="reset">네이티브 reset</Button><Button variant="quiet" onClick={()=>setValue('first')}>제어 값 reset</Button><Button variant="quiet" onClick={()=>setBusy(v=>!v)}>입력 loading 전환</Button><output data-testid="form-output" className="min-w-0 break-all">{output}</output></form><Tabs defaultValue="one" activationMode="manual"><TabsList aria-label="수동 탭"><TabsTrigger value="one">First</TabsTrigger><TabsTrigger value="two">Second</TabsTrigger><TabsTrigger value="disabled" disabled>Disabled</TabsTrigger></TabsList><TabsContent value="one">첫 패널</TabsContent><TabsContent value="two">두 번째 패널</TabsContent></Tabs><Dialog><DialogTrigger asChild><Button>중첩 Dialog 열기</Button></DialogTrigger><DialogContent><DialogTitle>포털 확인</DialogTitle><DialogDescription>열린 상태에서도 현재 테마를 따릅니다.</DialogDescription><Button onClick={()=>setMode(current=>current==='light'?'dark':'light')}>Dialog에서 테마 변경</Button><Select label="Dialog 안 선택" name="dialogSelect" defaultValue="first" options={options}/><DialogClose asChild><Button variant="secondary">닫기</Button></DialogClose></DialogContent></Dialog></div></Theme>;
}
