import { useId, useState, type CSSProperties } from 'react';
import { Theme, useThemeScope } from './gyeol/foundation/theme';
import { Button } from './gyeol/primitives/button';
import { TextField } from './gyeol/components/text-field';
import { Tabs, TabsList, TabsTrigger, TabsContent } from './gyeol/primitives/tabs';
import { Row } from './gyeol/primitives/layout';
import { CodeBlock } from './component-pages';

export function Overview(){
 return <div className="docs-page docs-overview">
  <div className="docs-brand-intro"><img src="/brand/hangyeol-ci.png" width="313" height="82" alt="한결디자인 — HANGYEOL DESIGN"/><p className="docs-lead">다른 제품에서도 같은 판단 기준으로 이어 만드는 React 디자인 시스템.</p></div>
  <section className="docs-section"><h2>한결디자인</h2><div className="docs-brand-copy"><p>한결디자인은 서로 다른 제품에서도 읽기·입력·행동의 관계를 일관되게 이어 가기 위한 React 디자인 시스템입니다. 버튼과 입력, 목록의 역할을 공통 기준으로 설명하고, 개발자가 소스를 읽고 제품에 맞게 수정하는 방식을 중심에 둡니다.</p><p>한글 인터페이스와 PC·모바일의 맥락을 함께 살피며, 제품의 색과 업무 규칙은 소비 프로젝트의 선택으로 남깁니다. 공통 기준은 모든 화면을 같은 모습으로 만드는 규칙이 아니라 다음 화면을 판단할 수 있는 기준입니다.</p></div></section>
  <section className="docs-section"><h2>디자인 원칙</h2><dl className="docs-brand-principles"><div><dt>명료함</dt><dd>정보와 행동을 구분하고, 현재 상태와 다음 행동이 읽히게 합니다.</dd></div><div><dt>일관된 관계</dt><dd>같은 역할의 입력, 버튼과 목록은 공통된 크기·간격·상태 기준을 따릅니다.</dd></div><div><dt>이어 만들기</dt><dd>소스와 팔레트를 프로젝트 안에서 소유하고 제품의 맥락에 맞게 수정합니다.</dd></div></dl></section>
 </div>;
}
export function GettingStarted(){
 const example=`import { Theme } from './gyeol/foundation/theme';\nimport { TextField } from './gyeol/components/text-field';\nimport { Button } from './gyeol/primitives/button';\nimport './gyeol.css';\n\nexport function App() {\n  return <Theme mode="light" palette="Indigo" className="grid gap-4 p-6">\n    <TextField label="이름" name="name" defaultValue="김한결" clearable />\n    <Button type="button">확인</Button>\n  </Theme>;\n}`;
 return <div className="docs-page"><p className="docs-lead">필요한 컴포넌트 소스를 프로젝트에 추가하고, 직접 편집해 사용하세요.</p><section className="docs-section"><h2>준비하기</h2><p className="text-g-soft leading-7">React 19, Vite, Tailwind CSS 4 프로젝트에서 사용할 수 있습니다. Node.js 22.22.2 환경을 기준으로 합니다. 소스 설치에 사용하는 <code>hangyeol-core</code> 패키지는 별도로 전달받아 준비하세요. 현재 자동 다운로드 설치는 제공하지 않습니다.</p><p className="text-g-small text-g-soft">패키지와 UI 소스의 사용 조건을 확인하세요. 별도로 공개된 이용 라이선스가 없는 파일은 외부 제품에 사용하기 전에 권한을 확인해야 합니다.</p></section><section className="docs-section"><h2>패키지를 설치하고 소스 추가하기</h2><p className="text-g-soft leading-7">아래 패키지 경로는 전달받은 파일의 실제 경로로 바꿔 주세요. 초기 설정을 확인한 뒤 필요한 컴포넌트를 추가합니다. <code>text-field</code>를 추가하면 입력과 버튼도 함께 준비됩니다.</p><CodeBlock language="Shell">{'npm install --save-dev --save-exact /path/to/hangyeol-core.tgz\n./node_modules/.bin/hangyeol init --dry-run\n./node_modules/.bin/hangyeol init\n./node_modules/.bin/hangyeol add text-field'}</CodeBlock><p className="text-g-small text-g-soft">초기 설정과 설치 계획에 표시되는 의존성을 준비하세요. 소스의 기본 위치는 <code>src/gyeol</code>, 스타일 진입점은 <code>src/gyeol.css</code>입니다. 기존 파일이 있을 때는 변경 내용을 확인한 뒤 진행하세요.</p></section><section className="docs-section"><h2>화면에서 사용하기</h2><p className="text-g-soft leading-7">스타일은 앱 진입점에서 한 번 가져옵니다. Theme 안에 컴포넌트를 배치하고 프로젝트 구조에 맞게 import 경로를 조정하세요.</p><CodeBlock>{example}</CodeBlock></section><section className="docs-section"><h2>글꼴과 직접 편집</h2><p className="text-g-soft leading-7">초기 설정은 Pretendard 글꼴과 라이선스를 준비합니다. 기본 글꼴 경로는 <code>public/fonts/gyeol</code>입니다. 설치한 컴포넌트와 테마는 프로젝트의 로컬 파일이므로 소스를 직접 수정할 수 있습니다. 팔레트의 값과 구성도 자유롭게 바꿀 수 있어요.</p><Row><a className="docs-text-link" href="#Button">컴포넌트 사용법 보기 →</a><a className="docs-text-link" href="#Customization">스타일 바꾸기 →</a></Row></section><section className="docs-section"><h2>이 문서를 로컬에서 실행하기</h2><p className="text-g-soft leading-7">한결디자인 저장소를 받은 경우 루트 폴더에서 실행하세요.</p><CodeBlock language="Shell">{'npm ci\nnpm run dev --workspace=@gyeol/docs'}</CodeBlock></section></div>;
}
function StylePreview({fontSize=16,gap=16}:{fontSize?:number;gap?:number}){
 const [value,setValue]=useState('김한결'),[message,setMessage]=useState('');
 return <div className="docs-demo docs-style-preview" style={{'--docs-preview-gap':`${gap}px`,'--docs-preview-text-size':`${fontSize}px`} as CSSProperties}><h3 className="font-semibold">프로필 정보</h3><p className="text-g-soft">이름과 주요 행동의 색상, 글자 크기, 간격을 비교합니다.</p><TextField label="이름" value={value} onValueChange={setValue}/><Button onClick={()=>setMessage(value.trim()?'예제의 표시 이름을 변경했습니다.':'이름을 입력해 주세요.')}>저장</Button><p role="status" className="text-g-small text-g-soft">{message||'변경 내용은 예제 안에서만 유지됩니다.'}</p></div>;
}
export function Customization(){
 const {mode,palette}=useThemeScope(),id=useId();
 const [color,setColor]=useState('#166534'),[font,setFont]=useState('18'),[gap,setGap]=useState('24');
 const [panel,setPanel]=useState('preview');
 return <div className="docs-page"><p className="docs-lead">같은 화면을 두고 색상, 글자 크기와 간격을 내 프로젝트에 맞게 바꿔 보세요.</p><div className="docs-controls"><label className="grid gap-2 text-g-small font-medium" htmlFor={id+'-color'}>주요 행동 색상<input id={id+'-color'} type="color" value={color} onChange={event=>setColor(event.target.value)}/></label><label className="grid gap-2 text-g-small font-medium" htmlFor={id+'-font'}>본문 크기<select id={id+'-font'} className="docs-native-select" value={font} onChange={event=>setFont(event.target.value)}><option value="16">16px</option><option value="18">18px</option><option value="20">20px</option></select></label><label className="grid gap-2 text-g-small font-medium" htmlFor={id+'-gap'}>요소 사이 간격<select id={id+'-gap'} className="docs-native-select" value={gap} onChange={event=>setGap(event.target.value)}><option value="16">16px</option><option value="24">24px</option><option value="32">32px</option></select></label><Button variant="quiet" size="small" onClick={()=>{setColor('#166534');setFont('18');setGap('24');}}>예제 설정 되돌리기</Button></div><Tabs value={panel} onValueChange={setPanel}><TabsList aria-label="스타일 비교"><TabsTrigger value="preview">변경 전후</TabsTrigger><TabsTrigger value="code">적용 코드</TabsTrigger></TabsList><TabsContent value="preview" className="mt-6"><div className="docs-compare"><section className="grid gap-4"><h2 className="text-g-small font-medium">기본 스타일</h2><StylePreview/></section><section className="grid gap-4"><h2 className="text-g-small font-medium">바꾼 스타일</h2><Theme mode={mode} palette={palette} values={{'--g-action':color,'--g-action-hover':color,'--g-on-action':'#FFFFFF'}}><StylePreview fontSize={Number(font)} gap={Number(gap)}/></Theme></section></div></TabsContent><TabsContent value="code" className="mt-6"><CodeBlock>{`import { Theme } from './gyeol/foundation/theme';\n\n<Theme values={{\n  '--g-action': '${color}',\n  '--g-action-hover': '${color}',\n  '--g-on-action': '#FFFFFF',\n}}>\n  {/* 이 영역에 사용할 컴포넌트를 배치하세요. */}\n</Theme>`}</CodeBlock><CodeBlock language="CSS">{`.my-screen { display: grid; gap: ${gap}px; }\n.my-screen > h3, .my-screen > p { font-size: ${font}px; }`}</CodeBlock></TabsContent></Tabs><p className="text-g-small text-g-soft">색을 바꾸면 글자와 바탕을 함께 확인하세요. 이 예제의 설정 되돌리기는 화면 안의 옵션만 바꾸며, 프로젝트의 파일이나 팔레트를 수정하지 않습니다. 저장한 소스의 값을 바꾸려면 <code>gyeol/foundation/theme.css</code>에서 해당 역할을 편집하세요.</p></div>;
}
