import { useEffect, useId, useRef, useState, type CSSProperties } from 'react';
import { Theme, useThemeScope } from './gyeol/foundation/theme';
import { Button } from './gyeol/primitives/button';
import { Input } from './gyeol/primitives/input';
import { TextField } from './gyeol/components/text-field';
import { Tabs, TabsList, TabsTrigger, TabsContent } from './gyeol/primitives/tabs';
import { Badge } from './gyeol/primitives/badge';
import { Row } from './gyeol/primitives/layout';
import { CodeBlock, ProductTabs } from './component-pages';
import themeSource from './gyeol/foundation/theme.css?raw';

const colorRoles=[['--g-canvas','전체 바탕'],['--g-surface','내용 영역'],['--g-muted','보조 바탕'],['--g-ink','본문'],['--g-soft','보조 글자'],['--g-line','구분선과 입력 경계'],['--g-action','주요 행동'],['--g-action-hover','주요 행동에 마우스를 올렸을 때'],['--g-on-action','주요 행동 위 글자'],['--g-focus','키보드 초점'],['--g-danger','오류 안내']] as const;
function tokenValue(name:string){return themeSource.match(new RegExp(name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\s*:\\s*([^;]+)'))?.[1].trim()??'';}
export function Overview(){
 const id=useId(),[message,setMessage]=useState('반가워요, 한결디자인'),[preview,setPreview]=useState('');
 return <div className="docs-page">
  <div className="docs-intro"><p className="docs-lead">화면을 만드는 데 필요한 색상, 글자, 컴포넌트를 살펴보세요.</p><p className="text-g-soft leading-7">같은 기준으로 읽고, 입력하고, 선택할 수 있는 React 디자인 시스템입니다. 필요한 소스를 가져가 내 프로젝트에 맞게 바꿀 수 있어요.</p><nav aria-label="소개에서 둘러보기" className="docs-intro-links"><a href="#Foundations" className="docs-primary-link">파운데이션 살펴보기 <span aria-hidden="true">→</span></a><a href="#Button" className="docs-text-link">컴포넌트 보기</a><a href="#GettingStarted" className="docs-text-link">시작하기</a></nav></div>
  <div className="docs-intro-preview"><section className="grid gap-4"><div className="flex items-center justify-between gap-3"><h2 className="text-g-small font-medium">색상</h2><Badge tone="info">내 화면에 맞게</Badge></div><div className="docs-color-strip"><span style={{background:'var(--g-action)'}}/><span style={{background:'var(--g-action-hover)'}}/><span style={{background:'var(--g-muted)'}}/><span style={{background:'var(--g-surface)'}}/></div><h3 className="text-g-title font-semibold leading-snug">읽기 편한 화면</h3><p>제목과 본문, 작은 안내를 같은 흐름으로 배치해 보세요.</p><p className="text-g-small text-g-soft">한글, 영문과 숫자도 자연스럽게. Hangyeol 2026.</p></section><section className="grid content-start gap-4"><h2 className="text-g-small font-medium">직접 써 보기</h2><label htmlFor={id} className="text-g-small font-medium">미리 볼 문구</label><Input id={id} value={message} onChange={event=>setMessage(event.target.value)}/><Row><Button onClick={()=>setPreview(message.trim()||'미리 볼 문구를 입력해 주세요.')}>문구 미리보기</Button><Button variant="secondary" onClick={()=>{setMessage('반가워요, 한결디자인');setPreview('');}}>되돌리기</Button></Row><p role="status" className="text-g-small text-g-soft">{preview||'문구를 바꾸고 버튼을 눌러 보세요.'}</p></section></div>
  <section className="docs-section"><h2>관련된 내용을 한 화면에</h2><ProductTabs/></section>
  <nav aria-label="문서 둘러보기" className="docs-paths"><a href="#Foundations"><h2>파운데이션</h2><p>색상, 글자, 간격으로 화면의 기준을 잡아요.</p><span aria-hidden="true">→</span></a><a href="#TaskExample"><h2>조합 예제</h2><p>입력과 버튼, 탭과 목록을 함께 써 보세요.</p><span aria-hidden="true">→</span></a><a href="#Customization"><h2>스타일 바꾸기</h2><p>같은 화면을 내 프로젝트의 색과 크기로 바꿔요.</p><span aria-hidden="true">→</span></a></nav>
 </div>;
}
function TypeSample({label,token,className,text}:{label:string;token?:string;className:string;text:string}){
 const ref=useRef<HTMLParagraphElement>(null),[values,setValues]=useState({font:'',size:'',weight:'',line:''});
 useEffect(()=>{if(ref.current){const style=getComputedStyle(ref.current);setValues({font:style.fontFamily,size:style.fontSize,weight:style.fontWeight,line:style.lineHeight});}},[]);
 return <div className="docs-type-sample"><div className="docs-type-meta"><span className="font-medium">{label}</span><code>{token?`${token}: ${tokenValue(token)}`:'크기: 현재 적용값'}</code><p className="text-g-caption text-g-soft">{values.font} · {values.size}<br/>굵기 {values.weight} · 줄간격 {values.line} (현재 적용값)</p></div><p ref={ref} className={className}>{text}</p></div>;
}
function SpacingSample({multiple}:{multiple:number}){
 const ref=useRef<HTMLSpanElement>(null),[width,setWidth]=useState('');
 useEffect(()=>{if(ref.current)setWidth(getComputedStyle(ref.current).width);},[]);
 return <div className="docs-spacing-row"><code>--spacing × {multiple}</code><span ref={ref} aria-hidden="true" style={{width:`calc(var(--spacing) * ${multiple})`}}/><span className="text-g-small text-g-soft">{width}</span></div>;
}
export function Foundations(){
 const {variables,palette,mode}=useThemeScope();
 const [space,setSpace]=useState(''),[created,setCreated]=useState('');
 return <div className="docs-page"><p className="docs-lead">같은 색상과 글자, 간격을 사용하면 서로 다른 요소도 하나의 화면으로 읽힙니다.</p>
  <section className="docs-section"><div className="docs-section-title"><h2>색상과 팔레트</h2><span className="text-g-small text-g-soft">{palette} · {mode==='light'?'밝은 화면':'어두운 화면'}</span></div><p className="text-g-soft leading-7">위의 팔레트 선택으로 인디고, 실버, 포레스트, 앰버, 로즈를 비교하세요. 밝기 선택은 팔레트와 별개입니다. 색상값은 지금 적용된 테마에서 가져옵니다.</p><div className="docs-swatches">{colorRoles.map(([token,label])=><div key={token} className="docs-swatch"><span aria-hidden="true" style={{background:`var(${token})`}}/><div><p className="text-g-small font-medium">{label}</p><code>{token}</code><span className="text-g-caption text-g-soft">{String((variables as Record<string,string>)[token]??'')}</span></div></div>)}</div><div className="docs-demo grid gap-4"><h3 className="text-xl font-semibold">새로운 공간을 만들어 보세요</h3><p className="text-g-soft">밝은 내용 영역에 제목과 본문을 놓고, 중요한 행동을 구분합니다.</p><TextField label="공간 이름" placeholder="나의 작업실" value={space} onValueChange={setSpace} hint="나중에 언제든 바꿀 수 있어요."/><Row><Button onClick={()=>setCreated(space.trim()?`${space}의 샘플 공간을 만들었습니다.`:'공간 이름을 입력해 주세요.')}>공간 만들기</Button><Badge tone="info">새 소식</Badge></Row><p className="text-g-small text-g-danger">오류 예시: 공간 이름을 입력해 주세요.</p><p role="status" className="text-g-small text-g-soft">{created||'이 예제는 실제 공간을 저장하지 않습니다.'}</p></div><p className="text-g-small text-g-soft">제공 팔레트는 출발점입니다. 색상값을 수정하거나 새 팔레트를 추가할 수 있고, 오류색도 프로젝트에 맞게 관리할 수 있습니다.</p></section>
  <section className="docs-section"><h2>타이포그래피</h2><p className="text-g-soft leading-7">Pretendard로 제목, 본문, 안내와 입력 라벨을 구분합니다. 등록된 글자 크기와 실제 예제에 적용된 굵기·줄간격을 함께 표시합니다.</p><div><TypeSample label="페이지 제목" token="--text-g-title" className="text-g-title font-semibold leading-[1.3]" text="내 공간을 정리하는 작은 습관"/><TypeSample label="섹션 제목" className="text-xl font-semibold leading-[1.4]" text="내 공간을 정리하는 작은 습관"/><TypeSample label="본문" token="--text-g-body" className="text-g-body leading-[1.5]" text="내 공간을 정리하는 작은 습관"/><TypeSample label="입력 라벨" token="--text-g-small" className="text-g-small font-medium leading-[1.4]" text="내 공간을 정리하는 작은 습관"/><TypeSample label="작은 설명" token="--text-g-caption" className="text-g-caption leading-[1.5] text-g-soft" text="내 공간을 정리하는 작은 습관"/></div><article className="docs-reading"><h3 className="text-g-title font-semibold leading-[1.3]">내 공간을 정리하는 작은 습관</h3><p className="text-g-body leading-[1.5]">자주 사용하는 물건은 가까이에 두고, 계절이 바뀌면 필요한 물건을 다시 골라 보세요. 작은 정리만으로도 공간을 편하게 사용할 수 있어요.</p><p className="text-g-caption text-g-soft">마지막 수정: 10월 10일</p><p className="text-g-small text-g-soft">Hangyeol Design · 공간 03 · 2026년 10월</p></article></section>
  <section className="docs-section"><h2>간격과 형태</h2><p className="text-g-soft leading-7">요소 사이의 간격은 부모 배치가, 입력과 버튼 안쪽 여백은 각 컴포넌트가 담당합니다.</p><div className="docs-foundation-grid"><div className="grid gap-4">{[1,2,3,4,6,8].map(multiple=><SpacingSample key={multiple} multiple={multiple}/>)}<p className="text-g-caption text-g-soft">Tailwind의 기본 간격 변수에 배수를 적용한 실제 길이입니다.</p></div><div className="grid gap-4"><div className="docs-demo"><code>--spacing-g-control: {tokenValue('--spacing-g-control')}</code><Row className="gap-4 mt-4"><Button>저장</Button><Button variant="secondary">취소</Button></Row></div><div className="docs-shapes"><div style={{borderRadius:'var(--radius-g-control)'}}><p>입력·버튼</p><code>{tokenValue('--radius-g-control')}</code></div><div style={{borderRadius:'var(--radius-g-panel)'}}><p>대화상자</p><code>{tokenValue('--radius-g-panel')}</code></div></div><p className="text-g-small text-g-soft">필요한 경계는 1px, 키보드 초점은 별도의 3px 외곽선으로 표시합니다. Tab 키로 버튼과 입력창을 이동해 보세요.</p></div></div></section>
 </div>;
}
export function GettingStarted(){
 const example=`import { Theme } from './gyeol/foundation/theme';\nimport { TextField } from './gyeol/components/text-field';\nimport { Button } from './gyeol/primitives/button';\nimport './gyeol.css';\n\nexport function App() {\n  return <Theme mode="light" palette="Indigo" className="grid gap-4 p-6">\n    <TextField label="이름" name="name" defaultValue="김한결" clearable />\n    <Button type="button">확인</Button>\n  </Theme>;\n}`;
 return <div className="docs-page"><p className="docs-lead">필요한 컴포넌트 소스를 프로젝트에 추가하고, 직접 편집해 사용하세요.</p><section className="docs-section"><h2>준비하기</h2><p className="text-g-soft leading-7">React 19, Vite, Tailwind CSS 4 프로젝트에서 사용할 수 있습니다. Node.js 22.22.2 환경을 기준으로 합니다. 소스 설치에 사용하는 <code>hangyeol-core</code> 패키지는 별도로 전달받아 준비하세요. 현재 자동 다운로드 설치는 제공하지 않습니다.</p><p className="text-g-small text-g-soft">패키지와 UI 소스의 사용 조건을 확인하세요. 별도로 공개된 이용 라이선스가 없는 파일은 외부 제품에 사용하기 전에 권한을 확인해야 합니다.</p></section><section className="docs-section"><h2>패키지를 설치하고 소스 추가하기</h2><p className="text-g-soft leading-7">아래 패키지 경로는 전달받은 파일의 실제 경로로 바꿔 주세요. 초기 설정을 확인한 뒤 필요한 컴포넌트를 추가합니다. <code>text-field</code>를 추가하면 입력과 버튼도 함께 준비됩니다.</p><CodeBlock language="Shell">{'npm install --save-dev --save-exact /path/to/hangyeol-core.tgz\n./node_modules/.bin/hangyeol init --dry-run\n./node_modules/.bin/hangyeol init\n./node_modules/.bin/hangyeol add text-field'}</CodeBlock><p className="text-g-small text-g-soft">초기 설정과 설치 계획에 표시되는 의존성을 준비하세요. 소스의 기본 위치는 <code>src/gyeol</code>, 스타일 진입점은 <code>src/gyeol.css</code>입니다. 기존 파일이 있을 때는 변경 내용을 확인한 뒤 진행하세요.</p></section><section className="docs-section"><h2>화면에서 사용하기</h2><p className="text-g-soft leading-7">스타일은 앱 진입점에서 한 번 가져옵니다. Theme 안에 컴포넌트를 배치하고 프로젝트 구조에 맞게 import 경로를 조정하세요.</p><CodeBlock>{example}</CodeBlock></section><section className="docs-section"><h2>글꼴과 직접 편집</h2><p className="text-g-soft leading-7">초기 설정은 Pretendard 글꼴과 라이선스를 준비합니다. 기본 글꼴 경로는 <code>public/fonts/gyeol</code>입니다. 설치한 컴포넌트와 테마는 프로젝트의 로컬 파일이므로 소스를 직접 수정할 수 있습니다. 팔레트의 값과 구성도 자유롭게 바꿀 수 있어요.</p><Row><a className="docs-text-link" href="#Button">컴포넌트 사용법 보기 →</a><a className="docs-text-link" href="#Customization">스타일 바꾸기 →</a></Row></section><section className="docs-section"><h2>이 문서를 로컬에서 실행하기</h2><p className="text-g-soft leading-7">한결디자인 저장소를 받은 경우 루트 폴더에서 실행하세요.</p><CodeBlock language="Shell">{'npm ci\nnpm run dev --workspace=@gyeol/docs'}</CodeBlock></section></div>;
}
function StylePreview({fontSize=16,gap=16}:{fontSize?:number;gap?:number}){
 const [value,setValue]=useState('나의 작업실'),[message,setMessage]=useState('');
 return <div className="docs-demo grid" style={{gap} as CSSProperties}><h3 style={{fontSize}} className="font-semibold">작은 공간을 만들어 보세요</h3><p style={{fontSize}} className="text-g-soft">이름을 정하고 필요한 것부터 채워 보세요.</p><TextField label="공간 이름" value={value} onValueChange={setValue}/><Button onClick={()=>setMessage(value.trim()?`${value}의 샘플을 만들었습니다.`:'공간 이름을 입력해 주세요.')}>공간 만들기</Button><p role="status" className="text-g-small text-g-soft">{message||'이 예제는 실제 공간을 저장하지 않습니다.'}</p></div>;
}
export function Customization(){
 const {mode,palette}=useThemeScope(),id=useId();
 const [color,setColor]=useState('#166534'),[font,setFont]=useState('18'),[gap,setGap]=useState('24');
 const [panel,setPanel]=useState('preview');
 return <div className="docs-page"><p className="docs-lead">같은 화면을 두고 색상, 글자 크기와 간격을 내 프로젝트에 맞게 바꿔 보세요.</p><div className="docs-controls"><label className="grid gap-2 text-g-small font-medium" htmlFor={id+'-color'}>주요 행동 색상<input id={id+'-color'} type="color" value={color} onChange={event=>setColor(event.target.value)}/></label><label className="grid gap-2 text-g-small font-medium" htmlFor={id+'-font'}>본문 크기<select id={id+'-font'} className="docs-native-select" value={font} onChange={event=>setFont(event.target.value)}><option value="16">16px</option><option value="18">18px</option><option value="20">20px</option></select></label><label className="grid gap-2 text-g-small font-medium" htmlFor={id+'-gap'}>요소 사이 간격<select id={id+'-gap'} className="docs-native-select" value={gap} onChange={event=>setGap(event.target.value)}><option value="16">16px</option><option value="24">24px</option><option value="32">32px</option></select></label><Button variant="quiet" size="small" onClick={()=>{setColor('#166534');setFont('18');setGap('24');}}>예제 설정 되돌리기</Button></div><Tabs value={panel} onValueChange={setPanel}><TabsList aria-label="스타일 비교"><TabsTrigger value="preview">변경 전후</TabsTrigger><TabsTrigger value="code">적용 코드</TabsTrigger></TabsList><TabsContent value="preview" className="pt-6"><div className="docs-compare"><section className="grid gap-4"><h2 className="text-g-small font-medium">기본 스타일</h2><StylePreview/></section><section className="grid gap-4"><h2 className="text-g-small font-medium">바꾼 스타일</h2><Theme mode={mode} palette={palette} values={{'--g-action':color,'--g-action-hover':color,'--g-on-action':'#FFFFFF'}}><StylePreview fontSize={Number(font)} gap={Number(gap)}/></Theme></section></div></TabsContent><TabsContent value="code" className="pt-6"><CodeBlock>{`import { Theme } from './gyeol/foundation/theme';\n\n<Theme values={{\n  '--g-action': '${color}',\n  '--g-action-hover': '${color}',\n  '--g-on-action': '#FFFFFF',\n}}>\n  {/* 이 영역에 사용할 컴포넌트를 배치하세요. */}\n</Theme>`}</CodeBlock><CodeBlock language="CSS">{`.my-screen { display: grid; gap: ${gap}px; }\n.my-screen > h3, .my-screen > p { font-size: ${font}px; }`}</CodeBlock></TabsContent></Tabs><p className="text-g-small text-g-soft">색을 바꾸면 글자와 바탕을 함께 확인하세요. 이 예제의 설정 되돌리기는 화면 안의 옵션만 바꾸며, 프로젝트의 파일이나 팔레트를 수정하지 않습니다. 저장한 소스의 값을 바꾸려면 <code>gyeol/foundation/theme.css</code>에서 해당 역할을 편집하세요.</p></div>;
}
