import { useMemo,useRef,useState,type ReactNode,type Key } from 'react';
import { Table,TableCaption,TableHeader,TableBody,TableRow,TableHead,TableCell } from './table';
import { SearchField } from './search-field';
import { Checkbox } from '../primitives/checkbox';
import { Select } from '../primitives/select';
import { Button } from '../primitives/button';
import { Pagination } from './pagination';
import { EmptyState } from './empty-state';
import { ErrorState } from './error-state';
export type DataTableColumn<T>={id:string;label:string;value:(row:T)=>string|number;render?:(row:T)=>ReactNode;numeric?:boolean;sortable?:boolean};
export type DataTableProps<T>={data:T[];columns:DataTableColumn<T>[];getKey:(row:T)=>Key;label:string;filter?:{columnId:string;label:string;options:{value:string;label:string}[]};loading?:boolean;error?:string;onRetry?:()=>void;selectedKeys?:Key[];defaultSelectedKeys?:Key[];onSelectionChange?:(keys:Key[])=>void;onBulkAction?:(rows:T[])=>void|Promise<void>;bulkLabel?:string;pageSizes?:number[]};
export function DataTable<T>({data,columns,getKey,label,filter,loading=false,error,onRetry,selectedKeys,defaultSelectedKeys=[],onSelectionChange,onBulkAction,bulkLabel='선택 항목 처리',pageSizes=[5,10,20]}:DataTableProps<T>){const [query,setQuery]=useState(''),[filterValue,setFilter]=useState('__all__'),[sort,setSort]=useState<{id:string;direction:'asc'|'desc'}|null>(null),[local,setLocal]=useState<Key[]>(defaultSelectedKeys),[page,setPage]=useState(1),[pageSize,setSize]=useState(pageSizes.find(size=>Number.isInteger(size)&&size>0)??5),[pending,setPending]=useState(false),[actionError,setActionError]=useState('');const running=useRef(false);const keys=new Set(data.map(getKey)),selection=(selectedKeys??local).filter(key=>keys.has(key));const selected=new Set(selection);
 const rows=useMemo(()=>{let result=data.filter(row=>columns.some(column=>String(column.value(row)).toLocaleLowerCase().includes(query.toLocaleLowerCase())));const filtered=filter&&columns.find(column=>column.id===filter.columnId);if(filtered&&filterValue!=='__all__')result=result.filter(row=>String(filtered.value(row))===filterValue);const column=sort&&columns.find(item=>item.id===sort.id);if(column&&sort)result=[...result].sort((a,b)=>{const left=column.value(a),right=column.value(b),order=typeof left==='number'&&typeof right==='number'?left-right:String(left).localeCompare(String(right),'ko',{numeric:true});return sort.direction==='asc'?order:-order;});return result;},[data,columns,query,filter,filterValue,sort]);
 const pages=Math.max(1,Math.ceil(rows.length/pageSize)),currentPage=Math.min(page,pages),visible=rows.slice((currentPage-1)*pageSize,currentPage*pageSize),count=visible.filter(row=>selected.has(getKey(row))).length;const update=(next:Key[])=>{if(loading||pending)return;const unique=Array.from(new Set(next));if(selectedKeys===undefined)setLocal(unique);onSelectionChange?.(unique);};const bulk=async()=>{if(!onBulkAction||running.current||loading||error||!selection.length)return;running.current=true;setPending(true);setActionError('');try{await onBulkAction(data.filter(row=>selected.has(getKey(row))));}catch{setActionError('선택한 항목을 처리하지 못했어요. 다시 시도해 주세요.');}finally{running.current=false;setPending(false);}};
 return <section aria-label={label} className="grid min-w-0 gap-4"><div className="flex min-w-0 flex-wrap items-end gap-3"><div className="min-w-0 flex-1"><SearchField label="목록 검색" value={query} disabled={loading||pending} onValueChange={next=>{setQuery(next);setPage(1);}}/></div>{filter&&<Select label={filter.label} value={filterValue} disabled={loading||pending} options={[{value:'__all__',label:'전체'},...filter.options]} onValueChange={next=>{setFilter(next);setPage(1);}}/>}<Select label="페이지당 항목 수" value={String(pageSize)} disabled={loading||pending} options={pageSizes.filter(size=>Number.isInteger(size)&&size>0).map(size=>({value:String(size),label:size+'개'}))} onValueChange={next=>{setSize(Number(next));setPage(1);}}/></div><div className="flex flex-wrap items-center justify-between gap-3"><p role="status" className="text-g-small text-g-soft">{rows.length}개 항목 · {selection.length}개 선택</p>{onBulkAction&&<Button variant="secondary" disabled={!selection.length||loading||Boolean(error)} loading={pending} onClick={()=>void bulk()}>{bulkLabel}</Button>}</div>{actionError&&<p role="alert" className="text-g-small text-g-danger">{actionError}</p>}{loading?<p role="status" aria-busy="true">목록을 불러오고 있어요.</p>:error?<ErrorState title="목록을 표시하지 못했어요." message={error} onRetry={onRetry}/>:rows.length===0?<EmptyState heading="표시할 항목이 없어요." description="검색어나 필터를 바꿔 보세요."/>:<><Table><TableCaption>{label}</TableCaption><TableHeader><TableRow><TableHead><Checkbox aria-label="현재 페이지 전체 선택" checked={count===0?false:count===visible.length?true:'indeterminate'} disabled={pending} onCheckedChange={checked=>{const pageKeys=new Set(visible.map(getKey));update(checked===true?[...selection,...pageKeys]:selection.filter(key=>!pageKeys.has(key)));}}/></TableHead>{columns.map(column=><TableHead key={column.id} numeric={column.numeric} aria-sort={sort?.id===column.id?(sort.direction==='asc'?'ascending':'descending'):undefined}>{column.sortable?<Button size="small" variant="quiet" disabled={pending} onClick={()=>{setSort({id:column.id,direction:sort?.id===column.id&&sort.direction==='asc'?'desc':'asc'});setPage(1);}}>{column.label}{sort?.id===column.id?(sort.direction==='asc'?' ↑':' ↓'):''}</Button>:column.label}</TableHead>)}</TableRow></TableHeader><TableBody>{visible.map(row=><TableRow key={getKey(row)}><TableCell><Checkbox aria-label={String(columns[0]?.value(row)??'항목')+' 선택'} checked={selected.has(getKey(row))} disabled={pending} onCheckedChange={checked=>update(checked===true?[...selection,getKey(row)]:selection.filter(key=>key!==getKey(row)))}/></TableCell>{columns.map(column=><TableCell key={column.id} numeric={column.numeric}>{column.render?column.render(row):column.value(row)}</TableCell>)}</TableRow>)}</TableBody></Table><Pagination page={currentPage} totalPages={pages} onPageChange={setPage} disabled={pending}/></>}</section>;
}
