import {GalleryDocs,GalleryControls} from './workbench';
import React from 'react';
import { Table, Pagination, List, ListItem, type DataColumn } from '../components/data-display';
import { Button, Input } from '../components/atoms';
import { Checkbox, Select } from '../components/primitives';
import { CodeBlock } from './code-block';
import '../examples.css';

export const dataDetailNames=['Table','Pagination','List','ListItem'] as const;
export type DataDetailName=typeof dataDetailNames[number];
export function hasDataDetail(name:string):name is DataDetailName{return (dataDetailNames as readonly string[]).includes(name);}
type Row={id:number;title:string;owner:string;status:string};
const sampleRows:Row[]=[{id:1,title:'문서 정리',owner:'디자인',status:'확인 전'},{id:2,title:'컴포넌트 점검',owner:'개발',status:'진행 중'},{id:3,title:'예시 확인',owner:'공통',status:'완료'}];
const rowType='type Row = { id: number; title: string; owner: string; status: string };';
export function DataDetail({name}:{name:DataDetailName}) {
  const initialLabel=name==='Table'?'작업 목록':name==='Pagination'?'페이지 탐색':'문서 목록';
  const [label,setLabel]=React.useState(initialLabel),[count,setCount]=React.useState(3),[ownerColumn,setOwnerColumn]=React.useState(true),[renderMode,setRenderMode]=React.useState('rich'),[wide,setWide]=React.useState(false),[page,setPage]=React.useState(1),[pageCount,setPageCount]=React.useState(12),[nativeId,setNativeId]=React.useState('example-list'),[title,setTitle]=React.useState('문서 정리'),[description,setDescription]=React.useState('로컬 예시 항목입니다.'),[showDescription,setShowDescription]=React.useState(true),[showThumbnail,setShowThumbnail]=React.useState(true),[selected,setSelected]=React.useState(false),[selectionCallback,setSelectionCallback]=React.useState(true),[showAction,setShowAction]=React.useState(true),[actionLabel,setActionLabel]=React.useState('열기'),[actions,setActions]=React.useState(0),[revision,setRevision]=React.useState(0);
  const rows=sampleRows.slice(0,count),displayCount=Math.max(1,Math.floor(pageCount)),displayPage=Math.max(1,Math.min(page,displayCount));
  const columns:DataColumn<Row>[]=[{id:'id',header:'번호',value:row=>row.id},{id:'title',header:'제목',value:row=>row.title,...(renderMode==='rich'?{render:(row:Row)=><strong className="example-table-cell" data-wide={wide||undefined}>{row.title}</strong>}:renderMode==='null'?{render:()=>null}:{})},...(ownerColumn?[{id:'owner',header:'담당',value:(row:Row)=>row.owner}]:[])];
  const reset=()=>{setLabel(initialLabel);setCount(3);setOwnerColumn(true);setRenderMode('rich');setWide(false);setPage(1);setPageCount(12);setNativeId('example-list');setTitle('문서 정리');setDescription('로컬 예시 항목입니다.');setShowDescription(true);setShowThumbnail(true);setSelected(false);setSelectionCallback(true);setShowAction(true);setActionLabel('열기');setActions(0);setRevision(n=>n+1);};
  const text=(caption:string,value:string,set:(value:string)=>void,aria:string)=><label className="field"><span>{caption}</span><Input aria-label={aria} value={value} onChange={event=>set(event.target.value)}/></label>;
  const check=(caption:string,value:boolean,set:(value:boolean)=>void)=><Checkbox label={caption} checked={value} onChange={event=>set(event.target.checked)}/>;
  let preview:React.ReactNode,source:string;
  if(name==='Table') {
    preview=<Table caption={label} rows={rows} columns={columns} rowKey={row=>row.id}/>;
    source=`import { Table, type DataColumn } from './src';\nimport './src/core.css';\nimport './src/examples.css';\n\n${rowType}\nconst rows: Row[] = ${JSON.stringify(rows)};\nconst columns: DataColumn<Row>[] = [\n  { id: 'id', header: '번호', value: row => row.id },\n  { id: 'title', header: '제목', value: row => row.title${renderMode==='rich'?`, render: row => <strong className="example-table-cell"${wide?' data-wide="true"':''}>{row.title}</strong>`:renderMode==='null'?', render: () => null':''} },\n${ownerColumn?"  { id: 'owner', header: '담당', value: row => row.owner },\n":''}];\nconst rowKey = (row: Row) => row.id;\n\nexport function Example() {\n  return <div className="ds-core"><Table caption={${JSON.stringify(label)}} rows={rows} columns={columns} rowKey={rowKey} /></div>;\n}`;
  } else if(name==='Pagination') {
    preview=<><Pagination page={page} pageCount={pageCount} label={label} onPageChange={setPage}/><p className="help" data-page-state>부모 page: {page} · 표시 page: {displayPage} / {displayCount}</p></>;
    source=`import { useState } from 'react';\nimport { Pagination } from './src';\nimport './src/core.css';\nimport './src/examples.css';\n\nexport function Example() {\n  const [page, setPage] = useState(${page});\n  const pageCount = ${pageCount};\n  const count = Math.max(1, Math.floor(pageCount));\n  const current = Math.max(1, Math.min(page, count));\n  return <div className="ds-core">\n    <Pagination page={page} pageCount={pageCount} label={${JSON.stringify(label)}} onPageChange={setPage} />\n    <p>부모 page: {page} · 표시 page: {current} / {count}</p>\n  </div>;\n}`;
  } else if(name==='List') {
    preview=<List label={label} id={nativeId||undefined}>{rows.map(row=><ListItem key={row.id} title={row.title} description={row.owner}/>)}</List>;
    source=`import { List, ListItem } from './src';\nimport './src/core.css';\nimport './src/examples.css';\n\n${rowType}\nconst items: Row[] = ${JSON.stringify(rows)};\n\nexport function Example() {\n  return <div className="ds-core">\n    <List label={${JSON.stringify(label)}}${nativeId?` id={${JSON.stringify(nativeId)}}`:''}>\n      {items.map(item => <ListItem key={item.id} title={item.title} description={item.owner} />)}\n    </List>\n  </div>;\n}`;
  } else {
    preview=<><List label={label}><ListItem title={title} description={showDescription?description:undefined} thumbnail={showThumbnail?<span aria-hidden="true">문</span>:undefined} selected={selected} onSelectionChange={selectionCallback?setSelected:undefined} action={showAction?{label:actionLabel,onClick:()=>setActions(n=>n+1)}:undefined}/></List><p className="help" role="status" data-list-item-state>selected: {String(selected)} · 동작 횟수: {actions}</p></>;
    source=`${selectionCallback||showAction?"import { useState } from 'react';\n":''}import { List, ListItem } from './src';\nimport './src/core.css';\nimport './src/examples.css';\n\nexport function Example() {\n${selectionCallback?`  const [selected, setSelected] = useState(${selected});\n`:''}${showAction?`  const [actions, setActions] = useState(${actions});\n`:''}  return <div className="ds-core">\n    <List label={${JSON.stringify(label)}}>\n      <ListItem title={${JSON.stringify(title)}}${showDescription?` description={${JSON.stringify(description)}}`:''}${showThumbnail?' thumbnail={<span aria-hidden="true">문</span>}':''} selected={${selectionCallback?'selected':String(selected)}}${selectionCallback?' onSelectionChange={setSelected}':''}${showAction?` action={{ label: ${JSON.stringify(actionLabel)}, onClick: () => setActions(n => n + 1) }}`:''} />\n    </List>\n    <p role="status">selected: ${selectionCallback?'{String(selected)}':String(selected)} · 동작 횟수: ${showAction?'{actions}':actions}</p>\n  </div>;\n}`;
  }
  return <div className="connected-detail stack" data-data-detail={name}>
    <div data-data-preview key={revision}>{preview}</div>
    <GalleryControls className="form-detail-controls">
      {text(name==='Table'?'caption':'label',label,setLabel,'data label control')}
      {(name==='Table'||name==='List')&&<label className="field"><span>{name==='Table'?'rows':'children · 항목 수'}</span><Select aria-label="data count control" value={count} onChange={event=>setCount(Number(event.target.value))}>{[0,1,3].map(n=><option key={n} value={n}>{n}개</option>)}</Select></label>}
      {name==='Table'&&<><label className="field"><span>columns[].render</span><Select aria-label="cell render control" value={renderMode} onChange={event=>setRenderMode(event.target.value)}><option value="plain">value만 표시</option><option value="rich">strong 노드</option><option value="null">null → value fallback</option></Select></label><div className="wrap">{check('담당 열 표시',ownerColumn,setOwnerColumn)}<Checkbox label="넓은 셀 render" disabled={renderMode!=='rich'} checked={wide} onChange={event=>setWide(event.target.checked)}/></div></>}
      {name==='Pagination'&&<><label className="field"><span>page · 유한 정수</span><Input type="number" step={1} aria-label="page control" value={page} onChange={event=>{const n=event.target.valueAsNumber;if(Number.isSafeInteger(n))setPage(n);}}/></label><label className="field"><span>pageCount</span><Select aria-label="pageCount control" value={pageCount} onChange={event=>setPageCount(Number(event.target.value))}>{[0,1,5,12,12.7].map(n=><option key={n} value={n}>{n}</option>)}</Select></label></>}
      {name==='List'&&text('native id',nativeId,setNativeId,'List id control')}
      {name==='ListItem'&&<>{text('title',title,setTitle,'ListItem title control')}{text('description · 텍스트',description,setDescription,'ListItem description control')}{text('action.label',actionLabel,setActionLabel,'ListItem action label control')}<div className="wrap">{check('description 전달',showDescription,setShowDescription)}{check('thumbnail 전달',showThumbnail,setShowThumbnail)}{check('selected',selected,setSelected)}{check('onSelectionChange 전달',selectionCallback,setSelectionCallback)}{check('action 전달',showAction,setShowAction)}</div></>}
      <Button variant="ghost" onClick={reset}>초기화</Button>
    </GalleryControls>
    <GalleryDocs open><summary>현재 코드</summary><CodeBlock source={source}/></GalleryDocs>
    <GalleryDocs><summary>Props · 데이터와 상태</summary>{name==='Table'?<><p>caption·rows·columns·rowKey는 필수입니다. caption에 표의 목적을 설명하고 고유한 rowKey를 지정하세요. 모든 rows를 표시하며 넓은 내용은 표 안에서 가로로 이동할 수 있습니다.</p><p>columns.value는 문자열 또는 숫자를 반환합니다. render로 셀 내용을 구성할 수 있으며 null이나 undefined를 반환하면 value를 표시합니다. 검색과 정렬이 필요한 표에는 DataTable을 사용하세요.</p></>:name==='Pagination'?<><p>page·pageCount·onPageChange를 전달하고 page는 1부터 시작합니다. onPageChange에서 페이지 값과 표시할 내용을 갱신하세요. 표시 범위 밖 page는 화면에서 보정하며 앱의 원래 값은 유지합니다.</p><p>이전과 다음은 표시 범위의 양 끝에서 비활성화됩니다. page에는 유한한 정수를 전달하세요. pageCount는 정수로 내림해 표시하고 최소 1페이지를 보여줍니다.</p></>:name==='List'?<><p>label에 목록의 이름을 적고 children에 ListItem 또는 ListRow를 넣습니다. id·className 등 ul 속성을 지정할 수 있습니다. 접근 가능한 이름에는 label을 사용합니다.</p><p>빈 목록에는 EmptyState 등으로 이유와 다음 동작을 안내하세요. 검색이나 페이지 이동은 목록을 사용하는 화면에 연결합니다.</p></>:<><p>title은 필수입니다. description·thumbnail·action을 추가하고 selected/onSelectionChange로 선택을 관리할 수 있습니다. selected의 기본값은 false이며 콜백을 지정하면 체크박스를 표시합니다.</p><p>선택은 체크박스, 실행은 action 버튼으로 구분합니다. description에는 문단 안에 들어갈 수 있는 내용을 사용하세요. 오른쪽 보조 내용이나 비활성 선택이 필요하면 ListRow를 선택하세요.</p></>}<p>예제의 초기화 버튼은 속성과 선택값을 시작 상태로 되돌립니다.</p></GalleryDocs>
  </div>;
}
