import React from 'react';
import { Table, Pagination, List, ListItem, type DataColumn } from '../components/data-display';
import { Button, Input } from '../components/atoms';
import { Checkbox, Select } from '../components/primitives';
import { CodeBlock } from './code-block';
import '../examples.css';

export const dataDetailNames=['Table','Pagination','List','ListItem'] as const;
export type DataDetailName=typeof dataDetailNames[number];
export function hasDataDetail(name:string):name is DataDetailName{return (dataDetailNames as readonly string[]).includes(name);}
type Row={id:number;title:string;owner:string;status:string};
const sampleRows:Row[]=[{id:1,title:'문서 정리',owner:'디자인',status:'확인 전'},{id:2,title:'컴포넌트 점검',owner:'개발',status:'진행 중'},{id:3,title:'예시 확인',owner:'공통',status:'완료'}];
const rowType='type Row = { id: number; title: string; owner: string; status: string };';
export function DataDetail({name}:{name:DataDetailName}) {
  const initialLabel=name==='Table'?'작업 목록':name==='Pagination'?'페이지 탐색':'문서 목록';
  const [label,setLabel]=React.useState(initialLabel),[count,setCount]=React.useState(3),[ownerColumn,setOwnerColumn]=React.useState(true),[renderMode,setRenderMode]=React.useState('rich'),[wide,setWide]=React.useState(false),[page,setPage]=React.useState(1),[pageCount,setPageCount]=React.useState(12),[nativeId,setNativeId]=React.useState('example-list'),[title,setTitle]=React.useState('문서 정리'),[description,setDescription]=React.useState('로컬 예시 항목입니다.'),[showDescription,setShowDescription]=React.useState(true),[showThumbnail,setShowThumbnail]=React.useState(true),[selected,setSelected]=React.useState(false),[selectionCallback,setSelectionCallback]=React.useState(true),[showAction,setShowAction]=React.useState(true),[actionLabel,setActionLabel]=React.useState('열기'),[actions,setActions]=React.useState(0),[revision,setRevision]=React.useState(0);
  const rows=sampleRows.slice(0,count),displayCount=Math.max(1,Math.floor(pageCount)),displayPage=Math.max(1,Math.min(page,displayCount));
  const columns:DataColumn<Row>[]=[{id:'id',header:'번호',value:row=>row.id},{id:'title',header:'제목',value:row=>row.title,...(renderMode==='rich'?{render:(row:Row)=><strong className="example-table-cell" data-wide={wide||undefined}>{row.title}</strong>}:renderMode==='null'?{render:()=>null}:{})},...(ownerColumn?[{id:'owner',header:'담당',value:(row:Row)=>row.owner}]:[])];
  const reset=()=>{setLabel(initialLabel);setCount(3);setOwnerColumn(true);setRenderMode('rich');setWide(false);setPage(1);setPageCount(12);setNativeId('example-list');setTitle('문서 정리');setDescription('로컬 예시 항목입니다.');setShowDescription(true);setShowThumbnail(true);setSelected(false);setSelectionCallback(true);setShowAction(true);setActionLabel('열기');setActions(0);setRevision(n=>n+1);};
  const text=(caption:string,value:string,set:(value:string)=>void,aria:string)=><label className="field"><span>{caption}</span><Input aria-label={aria} value={value} onChange={event=>set(event.target.value)}/></label>;
  const check=(caption:string,value:boolean,set:(value:boolean)=>void)=><Checkbox label={caption} checked={value} onChange={event=>set(event.target.checked)}/>;
  let preview:React.ReactNode,source:string;
  if(name==='Table') {
    preview=<Table caption={label} rows={rows} columns={columns} rowKey={row=>row.id}/>;
    source=`import { Table, type DataColumn } from './src';\nimport './src/core.css';\nimport './src/examples.css';\n\n${rowType}\nconst rows: Row[] = ${JSON.stringify(rows)};\nconst columns: DataColumn<Row>[] = [\n  { id: 'id', header: '번호', value: row => row.id },\n  { id: 'title', header: '제목', value: row => row.title${renderMode==='rich'?`, render: row => <strong className="example-table-cell"${wide?' data-wide="true"':''}>{row.title}</strong>`:renderMode==='null'?', render: () => null':''} },\n${ownerColumn?"  { id: 'owner', header: '담당', value: row => row.owner },\n":''}];\nconst rowKey = (row: Row) => row.id;\n\nexport function Example() {\n  return <div className="ds-core"><Table caption={${JSON.stringify(label)}} rows={rows} columns={columns} rowKey={rowKey} /></div>;\n}`;
  } else if(name==='Pagination') {
    preview=<><Pagination page={page} pageCount={pageCount} label={label} onPageChange={setPage}/><p className="help" data-page-state>부모 page: {page} · 표시 page: {displayPage} / {displayCount}</p></>;
    source=`import { useState } from 'react';\nimport { Pagination } from './src';\nimport './src/core.css';\nimport './src/examples.css';\n\nexport function Example() {\n  const [page, setPage] = useState(${page});\n  const pageCount = ${pageCount};\n  const count = Math.max(1, Math.floor(pageCount));\n  const current = Math.max(1, Math.min(page, count));\n  return <div className="ds-core">\n    <Pagination page={page} pageCount={pageCount} label={${JSON.stringify(label)}} onPageChange={setPage} />\n    <p>부모 page: {page} · 표시 page: {current} / {count}</p>\n  </div>;\n}`;
  } else if(name==='List') {
    preview=<List label={label} id={nativeId||undefined}>{rows.map(row=><ListItem key={row.id} title={row.title} description={row.owner}/>)}</List>;
    source=`import { List, ListItem } from './src';\nimport './src/core.css';\nimport './src/examples.css';\n\n${rowType}\nconst items: Row[] = ${JSON.stringify(rows)};\n\nexport function Example() {\n  return <div className="ds-core">\n    <List label={${JSON.stringify(label)}}${nativeId?` id={${JSON.stringify(nativeId)}}`:''}>\n      {items.map(item => <ListItem key={item.id} title={item.title} description={item.owner} />)}\n    </List>\n  </div>;\n}`;
  } else {
    preview=<><List label={label}><ListItem title={title} description={showDescription?description:undefined} thumbnail={showThumbnail?<span aria-hidden="true">문</span>:undefined} selected={selected} onSelectionChange={selectionCallback?setSelected:undefined} action={showAction?{label:actionLabel,onClick:()=>setActions(n=>n+1)}:undefined}/></List><p className="help" role="status" data-list-item-state>selected: {String(selected)} · 동작 횟수: {actions}</p></>;
    source=`${selectionCallback||showAction?"import { useState } from 'react';\n":''}import { List, ListItem } from './src';\nimport './src/core.css';\nimport './src/examples.css';\n\nexport function Example() {\n${selectionCallback?`  const [selected, setSelected] = useState(${selected});\n`:''}${showAction?`  const [actions, setActions] = useState(${actions});\n`:''}  return <div className="ds-core">\n    <List label={${JSON.stringify(label)}}>\n      <ListItem title={${JSON.stringify(title)}}${showDescription?` description={${JSON.stringify(description)}}`:''}${showThumbnail?' thumbnail={<span aria-hidden="true">문</span>}':''} selected={${selectionCallback?'selected':String(selected)}}${selectionCallback?' onSelectionChange={setSelected}':''}${showAction?` action={{ label: ${JSON.stringify(actionLabel)}, onClick: () => setActions(n => n + 1) }}`:''} />\n    </List>\n    <p role="status">selected: ${selectionCallback?'{String(selected)}':String(selected)} · 동작 횟수: ${showAction?'{actions}':actions}</p>\n  </div>;\n}`;
  }
  return <div className="connected-detail stack" data-data-detail={name}>
    <div data-data-preview key={revision}>{preview}</div>
    <div className="form-detail-controls">
      {text(name==='Table'?'caption':'label',label,setLabel,'data label control')}
      {(name==='Table'||name==='List')&&<label className="field"><span>{name==='Table'?'rows':'children · 항목 수'}</span><Select aria-label="data count control" value={count} onChange={event=>setCount(Number(event.target.value))}>{[0,1,3].map(n=><option key={n} value={n}>{n}개</option>)}</Select></label>}
      {name==='Table'&&<><label className="field"><span>columns[].render</span><Select aria-label="cell render control" value={renderMode} onChange={event=>setRenderMode(event.target.value)}><option value="plain">value만 표시</option><option value="rich">strong 노드</option><option value="null">null → value fallback</option></Select></label><div className="wrap">{check('담당 열 표시',ownerColumn,setOwnerColumn)}<Checkbox label="넓은 셀 render" disabled={renderMode!=='rich'} checked={wide} onChange={event=>setWide(event.target.checked)}/></div></>}
      {name==='Pagination'&&<><label className="field"><span>page · 유한 정수</span><Input type="number" step={1} aria-label="page control" value={page} onChange={event=>{const n=event.target.valueAsNumber;if(Number.isSafeInteger(n))setPage(n);}}/></label><label className="field"><span>pageCount</span><Select aria-label="pageCount control" value={pageCount} onChange={event=>setPageCount(Number(event.target.value))}>{[0,1,5,12,12.7].map(n=><option key={n} value={n}>{n}</option>)}</Select></label></>}
      {name==='List'&&text('native id',nativeId,setNativeId,'List id control')}
      {name==='ListItem'&&<>{text('title',title,setTitle,'ListItem title control')}{text('description · 텍스트',description,setDescription,'ListItem description control')}{text('action.label',actionLabel,setActionLabel,'ListItem action label control')}<div className="wrap">{check('description 전달',showDescription,setShowDescription)}{check('thumbnail 전달',showThumbnail,setShowThumbnail)}{check('selected',selected,setSelected)}{check('onSelectionChange 전달',selectionCallback,setSelectionCallback)}{check('action 전달',showAction,setShowAction)}</div></>}
      <Button variant="ghost" onClick={reset}>초기화</Button>
    </div>
    <details open><summary>현재 코드</summary><CodeBlock source={source}/></details>
    <details><summary>Props · 데이터와 상태</summary>{name==='Table'?<><p>caption/rows/columns/rowKey가 모두 필수입니다. DataTable alias가 아닌 독립 native table이며 모든 rows를 렌더합니다. caption·scope="col"과 focus 가능한 내부 스크롤 영역을 사용합니다. 넓은 셀 render는 소비자 노드의 minWidth 예시이며 별도 Table width prop이 아닙니다.</p><p>columns.value는 문자열/숫자이고 render는 ReactNode입니다. render 결과가 null/undefined면 value로 fallback하며 false/0/빈 문자열은 유지합니다. sortable은 Table에서 사용하지 않습니다. 검색·정렬·선택·페이지·서버 데이터 기능이나 일반 native attributes/children API는 없습니다.</p></>:name==='Pagination'?<><p>page/pageCount/onPageChange는 필수이며 label은 선택적입니다. 호출자가 page를 소유합니다. 표시 count는 pageCount를 내림하고 최소1, 표시 current는 page를1부터count로 보정합니다. 표시 보정은 부모 값을 자동 변경하거나 callback으로 통지하지 않습니다. 현재 번호 클릭도 callback을 호출합니다.</p><p>이전/다음은 표시 경계에서 disabled입니다. 유한 정수 page를 사용하는 예제이며 core는 page의 소수·NaN/Infinity 방어를 제공하지 않습니다. pageCount의12.7은 내림 표시를 시연합니다. 콘텐츠 slicing·서버 페이지·router는 별도 소비자 책임이며 예제에는 추가하지 않습니다.</p></>:name==='List'?<><p>필수 label과 native ul attributes/children을 받습니다. id는 native attribute이고 className은 ds-list에 병합됩니다. 별도 aria-label을 전달해도 label이 우선하며 일반 ref 전달 구현은 없습니다.</p><p>이 예제는 실제 ListItem children을 구성합니다. 항목 수·빈 배열은 부모의 구성 선택이며 List 자체의 검색·페이지·선택 기능이 아닙니다.</p></>:<><p>필수 title, 선택적 description/thumbnail ReactNode·selected·onSelectionChange·action(label/onClick)을 사용합니다. native li이므로 실제 List의 ul 안에서 표시합니다. selected 기본값은 false이며 callback이 있을 때만 checkbox가 생성됩니다. 부모가 선택값을 반영해야 바뀌고 callback 없이 selected=true여도 선택 스타일은 유지됩니다.</p><p>행 전체 클릭이 아니라 checkbox와 별도 action 버튼을 사용합니다. description/thumbnail은 truthy 값만 표시하므로0/빈 문자열/false는 생략합니다. description은 p 안에 렌더하므로 노드의 HTML 적합성은 소비자 책임입니다. disabled/defaultSelected/children/임의 trailing/router API는 없습니다. 동작 횟수는 부모 로컬 상태이며 서버 저장·전송이 아닙니다.</p></>}<p>초기화는 예제 props·부모 state를 되돌리고 미리보기를 다시 마운트합니다.</p></details>
  </div>;
}
