import {GalleryDocs,GalleryControls} from './workbench';
import React from 'react';
import { MonthPicker, TimeInput, DateTimeInput } from '../components/date-controls';
import { FileInput, AddressField, type AddressValue } from '../components/form-controls';
import { Button, Input } from '../components/atoms';
import { Checkbox, Select } from '../components/primitives';
import { CodeBlock } from './code-block';

export const extendedInputDetailNames=['FileInput','AddressField','MonthPicker','TimeInput','DateTimeInput'] as const;
export type ExtendedInputDetailName=typeof extendedInputDetailNames[number];
export function hasExtendedInputDetail(name:string):name is ExtendedInputDetailName{return (extendedInputDetailNames as readonly string[]).includes(name);}
type DateName='MonthPicker'|'TimeInput'|'DateTimeInput';
const dateDefaults={MonthPicker:'2026-10',TimeInput:'10:30',DateTimeInput:'2026-10-06T10:30'};
const dateLabels={MonthPicker:'기준 월',TimeInput:'기준 시간',DateTimeInput:'기준 날짜와 시간'};
const dateLimits={MonthPicker:['2026-01','2026-12'],TimeInput:['09:00','18:00'],DateTimeInput:['2026-10-01T09:00','2026-10-31T18:00']} as const;
function DateDetail({name}:{name:DateName}) {
  const [value,setValue]=React.useState(dateDefaults[name]),[valid,setValid]=React.useState(true);
  const [disabled,setDisabled]=React.useState(false),[readOnly,setReadOnly]=React.useState(false),[busy,setBusy]=React.useState(false),[required,setRequired]=React.useState(false),[error,setError]=React.useState(false),[limited,setLimited]=React.useState(true),[blocked,setBlocked]=React.useState(false);
  const [revision,setRevision]=React.useState(0);
  const flags={label:dateLabels[name],value,onChange:setValue,onValidityChange:setValid,disabled,readOnly,busy,required,error:error?'입력 내용을 확인하세요.':undefined,min:limited?dateLimits[name][0]:undefined,max:limited?dateLimits[name][1]:undefined};
  const source=`import { useState } from 'react';\nimport { ${name} } from './src';\nimport './src/core.css';\n\nexport function Example() {\n  const [value, setValue] = useState(${JSON.stringify(value)});\n  const [valid, setValid] = useState(${valid});\n  return (\n    <div className="ds-core">\n      <${name} label=${JSON.stringify(flags.label)} value={value} onChange={setValue} onValidityChange={setValid}\n        disabled={${disabled}} readOnly={${readOnly}} busy={${busy}} required={${required}}${flags.error?` error=${JSON.stringify(flags.error)}`:''}${limited?` min=${JSON.stringify(flags.min)} max=${JSON.stringify(flags.max)}`:''}${name==='DateTimeInput'&&blocked?' disabledDates={["2026-10-10"]}':''} />\n      <p>확정 value: {value || '미선택'} · 유효성: {valid ? '유효' : '확인 필요'}</p>\n    </div>\n  );\n}`;
  const reset=()=>{setValue(dateDefaults[name]);setDisabled(false);setReadOnly(false);setBusy(false);setRequired(false);setError(false);setLimited(true);setBlocked(false);setRevision(n=>n+1);};
  return <div className="connected-detail stack" data-extended-input-detail={name}>
    <div data-extended-preview key={revision}>{name==='MonthPicker'?<MonthPicker {...flags}/>:name==='TimeInput'?<TimeInput {...flags}/>:<DateTimeInput {...flags} disabledDates={blocked?['2026-10-10']:undefined}/>}<p className="help" data-committed-value>확정 value: {value||'미선택'} · 유효성: {valid?'유효':'확인 필요'}</p></div>
    <GalleryControls className="form-detail-controls"><label className="field"><span>확정 value</span><Input aria-label="확정 value control" value={value} onChange={event=>setValue(event.target.value)}/></label>
      <div className="wrap">{[{label:'disabled',value:disabled,set:setDisabled},{label:'readOnly',value:readOnly,set:setReadOnly},{label:'busy',value:busy,set:setBusy},{label:'required',value:required,set:setRequired},{label:'error',value:error,set:setError},{label:'범위 제한',value:limited,set:setLimited}].map(control=><Checkbox key={control.label} label={control.label} checked={control.value} onChange={event=>control.set(event.target.checked)}/>)}{name==='DateTimeInput'&&<Checkbox label="2026-10-10 선택 제한" checked={blocked} onChange={event=>setBlocked(event.target.checked)}/>}</div>
      <Button variant="ghost" onClick={reset}>초기화</Button>
    </GalleryControls>
    <GalleryDocs open><summary>현재 코드</summary><CodeBlock source={source}/></GalleryDocs>
    <GalleryDocs><summary>Props · 값과 유효성</summary><p>{name==='MonthPicker'?'value 형식은 YYYY-MM입니다. 한국어 연도·월 선택과 지우기를 제공하고 min/max 범위 밖 월은 선택할 수 없습니다.':name==='TimeInput'?'value 형식은 HH:mm이며 00:00–23:59 범위의 text 입력입니다. 시간 팝업·초·step·시간대 API는 없습니다.':'value 형식은 시간대 없는 YYYY-MM-DDTHH:mm입니다. DatePicker와 TimeInput을 조합하고 disabledDates는 날짜 선택에 적용됩니다. 현재 날짜가 min/max 경계 날짜일 때만 해당 시간 한계를 적용합니다. 시간대 변환을 수행하지 않습니다.'}</p>
      <p>value/onChange는 제어형, defaultValue는 비제어형 초기값입니다. 잘못된 편집 텍스트는 내부 draft에 남으며 확정 value control과 현재 코드에는 콜백으로 전달된 값이 표시됩니다. 빈 값·부분값의 onChange는 유효성 true를 보장하지 않으므로 onValidityChange를 별도로 확인하세요. required는 빈 값을 invalid로 표시하지만 지우기 콜백은 발생할 수 있습니다.</p>
      <p>disabled는 native 비활성, readOnly와 busy는 읽기 전용이며 편집·선택을 차단합니다. busy는 입력 로딩 안내를 표시합니다. error와 잘못된 draft는 validity에 반영됩니다. min/max는 양끝을 포함합니다. name/form/id/step/onDraftChange props는 없고 제출 연결은 소비자 소유입니다. 초기화는 소유 값·설정과 preview 내부 draft/팝업을 되돌리며 native form.reset()과는 별도입니다.</p>
    </GalleryDocs>
  </div>;
}
function FileDetail() {
  const [accept,setAccept]=React.useState('.txt'),[multiple,setMultiple]=React.useState(false),[required,setRequired]=React.useState(false),[disabled,setDisabled]=React.useState(false),[error,setError]=React.useState(false),[files,setFiles]=React.useState<File[]>([]),[revision,setRevision]=React.useState(0);
  const reset=()=>{setFiles([]);setAccept('.txt');setMultiple(false);setRequired(false);setDisabled(false);setError(false);setRevision(n=>n+1);};
  const source=`import { useState } from 'react';\nimport { FileInput, Button } from './src';\nimport './src/core.css';\n\nexport function Example() {\n  const [files, setFiles] = useState<File[]>([]);\n  const [revision, setRevision] = useState(0);\n  return (\n    <div className="ds-core">\n      <FileInput key={revision} label="로컬 예시 파일" name="attachment" accept=${JSON.stringify(accept)} multiple={${multiple}} required={${required}} disabled={${disabled}}${error?' error="파일 선택 내용을 확인하세요."':''} hint="문서 예시입니다. 업로드하거나 외부로 전송하지 않습니다." onFilesChange={setFiles} />\n      <p>선택 파일: {files.map(file => file.name).join(', ') || '없음'}</p>\n      <Button variant="ghost" onClick={() => { setFiles([]); setRevision(value => value + 1); }}>선택 비우기</Button>\n    </div>\n  );\n}`;
  return <div className="connected-detail stack" data-extended-input-detail="FileInput">
    <div data-extended-preview key={revision}><FileInput label="로컬 예시 파일" name="attachment" hint="문서 예시입니다. 업로드하거나 외부로 전송하지 않습니다." accept={accept} multiple={multiple} required={required} disabled={disabled} error={error?'파일 선택 내용을 확인하세요.':undefined} onFilesChange={setFiles}/><p className="help" data-file-result>선택 파일: {files.map(file=>file.name).join(', ')||'없음'}</p><Button variant="ghost" onClick={()=>{setFiles([]);setRevision(n=>n+1);}}>선택 비우기</Button></div>
    <GalleryControls className="form-detail-controls"><label className="field"><span>accept</span><Select aria-label="허용 파일 형식" value={accept} onChange={event=>setAccept(event.target.value)}><option value=".txt">.txt</option><option value="image/*">image/*</option><option value=".txt,image/*">.txt,image/*</option><option value="">제한 없음</option></Select></label><div className="wrap">{[{label:'multiple',value:multiple,set:setMultiple},{label:'required',value:required,set:setRequired},{label:'disabled',value:disabled,set:setDisabled},{label:'error',value:error,set:setError}].map(control=><Checkbox key={control.label} label={control.label} checked={control.value} onChange={event=>control.set(event.target.checked)}/>)}</div><Button variant="ghost" onClick={reset}>초기화</Button></GalleryControls>
    <GalleryDocs open><summary>현재 코드</summary><CodeBlock source={source}/></GalleryDocs>
    <GalleryDocs><summary>Props · 파일 선택</summary><p>label은 필수이며 accept/multiple/onFilesChange와 required/disabled/error/hint/id/name을 받습니다. native FileList가 선택을 소유하고 onFilesChange는 File[]를 전달합니다. 파일 input에 value/defaultValue 문자열을 넣는 API가 아닙니다. 현재 코드는 선택·콜백·설정 방법이며 실제 File 객체나 경로를 직렬화해 재생하지 않습니다.</p><p>허용 형식은 확장자·정확 MIME·MIME wildcard로 검사합니다. 하나라도 거절하면 전체 선택을 비우고 [] 콜백·오류/custom validity를 설정합니다. 유효 파일 재선택으로 형식 오류를 해제합니다. accept 변경만으로 이미 고른 파일을 다시 검증하지는 않습니다. 외부 error 안내와 native validity는 별개입니다.</p><p>선택 비우기/초기화는 소비자 배열을 []로 바꾸고 FileInput을 다시 마운트합니다. native form.reset()에 내부 파일명·오류·소비자 상태가 자동 동기화되는 계약은 없습니다. 크기·개수 상한·업로드·저장·외부 전송을 구현하지 않습니다. 문서용 로컬 예시 파일만 사용하세요.</p></GalleryDocs>
  </div>;
}
const emptyAddress:AddressValue={postal:'',road:'',jibun:'',detail:''};
const sampleAddress:AddressValue={postal:'12345',road:'예시로 123',jibun:'예시동 123-4',detail:'101호'};
function AddressDetail() {
  const [value,setValue]=React.useState<AddressValue>(emptyAddress),[disabled,setDisabled]=React.useState(false),[required,setRequired]=React.useState(false),[error,setError]=React.useState(false),[revision,setRevision]=React.useState(0);
  const reset=()=>{setValue(emptyAddress);setDisabled(false);setRequired(false);setError(false);setRevision(n=>n+1);};
  const source=`import { useState } from 'react';\nimport { AddressField, Button, type AddressValue } from './src';\nimport './src/core.css';\n\nconst sample: AddressValue = ${JSON.stringify(sampleAddress)};\n\nexport function Example() {\n  const [value, setValue] = useState<AddressValue>(${JSON.stringify(value)});\n  return (\n    <div className="ds-core">\n      <AddressField label="예시 주소" name="address" value={value} onValueChange={setValue} disabled={${disabled}} required={${required}}${error?' error="주소 내용을 확인하세요."':''} hint="로컬 샘플입니다. 실제 주소 검색 서비스가 아닙니다." searchSlot={select => <Button variant="secondary" disabled={${disabled}} onClick={() => select(sample)}>로컬 샘플 선택</Button>} />\n    </div>\n  );\n}`;
  return <div className="connected-detail stack" data-extended-input-detail="AddressField">
    <div data-extended-preview key={revision}><AddressField label="예시 주소" name="address" value={value} onValueChange={setValue} disabled={disabled} required={required} error={error?'주소 내용을 확인하세요.':undefined} hint="로컬 샘플입니다. 실제 주소 검색 서비스가 아닙니다." searchSlot={select=><Button variant="secondary" disabled={disabled} onClick={()=>select(sampleAddress)}>로컬 샘플 선택</Button>}/></div>
    <GalleryControls className="form-detail-controls"><div className="selection-text-controls">{(['postal','road','jibun','detail'] as const).map(key=><label key={key} className="field"><span>value.{key}</span><Input aria-label={`확정 ${key} control`} value={value[key]} onChange={event=>{const text=event.target.value;setValue(previous=>({...previous,[key]:text}));}}/></label>)}</div><div className="wrap">{[{label:'disabled',value:disabled,set:setDisabled},{label:'required',value:required,set:setRequired},{label:'error',value:error,set:setError}].map(control=><Checkbox key={control.label} label={control.label} checked={control.value} onChange={event=>control.set(event.target.checked)}/>)}</div><Button variant="ghost" onClick={reset}>초기화</Button></GalleryControls>
    <GalleryDocs open><summary>현재 코드</summary><CodeBlock source={source}/></GalleryDocs>
    <GalleryDocs><summary>Props · 주소와 검색 어댑터</summary><p>value/defaultValue는 postal/road/jibun/detail 문자열 객체이며 onValueChange는 전체 객체를 전달합니다. name을 주면 name.postal 등 native 필드 이름으로 연결됩니다. required는 postal/road에 적용되고 우편번호는 5자리 숫자 pattern입니다. disabled는 입력과 선택 콜백을 막습니다. error는 안내/ARIA이며 주소의 실제 존재나 배송 가능성을 검증하지 않습니다.</p><p>검색 연결은 소비자가 onSearch(select) 또는 searchSlot(select)을 공급합니다. 이 예제는 메모리에 정의된 가상 주소를 선택하는 로컬 어댑터이며 SDK/provider·실주소 검색·외부 요청이 없습니다. select 콜백은 현재 disabled와 최신 onValueChange를 따릅니다. 임의 검색 slot의 버튼 disabled는 소비자가 명시합니다.</p><p>readOnly/busy/min/max/form 등의 props는 없습니다. 초기화는 소유 객체·설정과 preview의 touched 상태를 되돌리며 native form.reset과는 별도입니다. 실제 서비스에서 쓰려면 소비자가 검증된 provider와 개인정보 처리 계약을 별도로 연결해야 합니다.</p></GalleryDocs>
  </div>;
}
export function ExtendedInputDetail({name}:{name:ExtendedInputDetailName}) {return name==='FileInput'?<FileDetail/>:name==='AddressField'?<AddressDetail/>:<DateDetail name={name}/>;}
