import {GalleryDocs,GalleryControls} from './workbench';
import React from 'react';
import { Icon, IconAction, iconNames, type IconName } from '../components/icons';
import { Button, Input, type ButtonProps } from '../components/atoms';
import { Checkbox, Select } from '../components/primitives';
import { CodeBlock } from './code-block';
import '../examples.css';
export const iconDetailNames=['Icon','IconAction'] as const;
export type IconDetailName=typeof iconDetailNames[number];
export function hasIconDetail(name:string):name is IconDetailName{return (iconDetailNames as readonly string[]).includes(name);}
export function IconDetail({name}:{name:IconDetailName}) {
 const action=name==='IconAction';
 const [icon,setIcon]=React.useState<IconName>('search'),[svgSize,setSvgSize]=React.useState(20),[strokeWidth,setStrokeWidth]=React.useState(1.75),[color,setColor]=React.useState('currentColor'),[label,setLabel]=React.useState('검색 확인'),[variant,setVariant]=React.useState<NonNullable<ButtonProps['variant']>>('secondary'),[size,setSize]=React.useState<NonNullable<ButtonProps['size']>>('medium'),[loading,setLoading]=React.useState(false),[disabled,setDisabled]=React.useState(false),[id,setId]=React.useState('icon-action-example'),[count,setCount]=React.useState(0),[last,setLast]=React.useState('');
 const reset=()=>{setIcon('search');setSvgSize(20);setStrokeWidth(1.75);setColor('currentColor');setLabel('검색 확인');setVariant('secondary');setSize('medium');setLoading(false);setDisabled(false);setId('icon-action-example');setCount(0);setLast('');};
 const source=action?`import { useState } from 'react';\nimport { IconAction } from './src';\nimport './src/core.css';\nimport './src/examples.css';\n\nexport function Example() {\n  const [count, setCount] = useState(${count});\n  const [last, setLast] = useState(${JSON.stringify(last)});\n  return <div className="ds-core">\n    <IconAction name=${JSON.stringify(icon)} label={${JSON.stringify(label)}} variant=${JSON.stringify(variant)} size=${JSON.stringify(size)} type="button" id={${JSON.stringify(id)}} loading={${loading}} disabled={${disabled}}\n      onClick={event => { setCount(n => n + 1); setLast(event.currentTarget.id); }} />\n    <p role="status">실행 {count}회 · 최근 버튼 id: {last || '없음'}</p>\n  </div>;\n}`:`import { Icon } from './src';\nimport './src/core.css';\nimport './src/examples.css';\n\nexport function Example() {\n  return <div className="ds-core">\n    <span className="example-icon-inline">\n      <Icon name=${JSON.stringify(icon)} size={${svgSize}} strokeWidth={${strokeWidth}} color={${JSON.stringify(color)}} />\n      <span>아이콘: {${JSON.stringify(icon)}}</span>\n    </span>\n  </div>;\n}`;
 const numeric=(caption:string,value:number,set:(n:number)=>void,min:number,max:number,step:number,aria:string)=><label className="field"><span>{caption}</span><Input type="number" aria-label={aria} min={min} max={max} step={step} value={value} onChange={event=>{const next=Number(event.target.value);if(Number.isFinite(next))set(Math.min(max,Math.max(min,next)));}}/></label>;
 return <div className="connected-detail stack" data-icon-detail={name}>
  <div data-icon-preview>{action?<><IconAction name={icon} label={label} variant={variant} size={size} type="button" id={id} loading={loading} disabled={disabled} onClick={event=>{setCount(n=>n+1);setLast(event.currentTarget.id);}}/><p role="status" className="help">실행 {count}회 · 최근 버튼 id: {last||'없음'}</p></>:<span className="example-icon-inline"><Icon name={icon} size={svgSize} strokeWidth={strokeWidth} color={color}/><span>아이콘: {icon}</span></span>}</div>
  <GalleryControls className="form-detail-controls">
   <label className="field"><span>name</span><Select aria-label="icon name control" value={icon} onChange={event=>setIcon(event.target.value as IconName)}>{iconNames.map(item=><option key={item} value={item}>{item}</option>)}</Select></label>
   {action?<><label className="field"><span>label · 접근 가능한 버튼 이름</span><Input aria-label="icon action label control" value={label} onChange={event=>setLabel(event.target.value)}/></label><label className="field"><span>id · native button</span><Input aria-label="icon action id control" value={id} onChange={event=>setId(event.target.value)}/></label><label className="field"><span>variant</span><Select aria-label="icon action variant control" value={variant} onChange={event=>setVariant(event.target.value as NonNullable<ButtonProps['variant']>)}>{(['primary','secondary','quiet','ghost','destructive'] as const).map(value=><option key={value}>{value}</option>)}</Select></label><label className="field"><span>size · 버튼 prop</span><Select aria-label="icon action size control" value={size} onChange={event=>setSize(event.target.value as NonNullable<ButtonProps['size']>)}>{(['small','medium','large'] as const).map(value=><option key={value}>{value}</option>)}</Select></label><div className="wrap"><Checkbox label="loading" checked={loading} onChange={event=>setLoading(event.target.checked)}/><Checkbox label="disabled" checked={disabled} onChange={event=>setDisabled(event.target.checked)}/></div></>:<>{numeric('size · SVG',svgSize,setSvgSize,8,96,1,'icon svg size control')}{numeric('strokeWidth',strokeWidth,setStrokeWidth,0.5,4,0.25,'icon stroke width control')}<label className="field"><span>color · SVG 상속 prop</span><Select aria-label="icon color control" value={color} onChange={event=>setColor(event.target.value)}><option value="currentColor">currentColor · 주변 텍스트 색</option><option value="#2563eb">파랑 · #2563eb</option><option value="#334155">회색 · #334155</option></Select></label></>}
   <Button variant="ghost" onClick={reset}>초기화</Button>
  </GalleryControls>
  <GalleryDocs open><summary>현재 코드</summary><CodeBlock source={source}/></GalleryDocs>
  <GalleryDocs><summary>Props · 아이콘과 버튼</summary>{action?<><p>IconAction은 name으로 아이콘을 선택하고 label로 버튼 동작을 설명합니다. Button의 variant·size·loading과 button 속성을 사용할 수 있습니다. size는 버튼 크기이며 small·medium·large를 선택합니다.</p><p>label은 버튼의 접근 가능한 이름입니다. 기본값은 type=button, variant=secondary, size=medium입니다. id·form과 클릭 이벤트를 전달할 수 있습니다.</p><p>loading은 진행 상태를 알리고 버튼 클릭 실행을 막습니다. disabled는 버튼을 비활성화합니다. 폼 제출에는 type=submit을 지정하고 제출 로직에서도 중복 실행을 관리하세요. 버튼 ref는 실제 버튼 요소에 연결됩니다.</p></>:<><p>name으로 iconNames의 아이콘을 선택합니다. 기본 size는 20, strokeWidth는 1.75이며 색은 주변 텍스트를 따릅니다. SVG 속성으로 크기와 색을 조정할 수 있습니다.</p><p>기본 SVG는 장식으로 표시합니다. 의미를 주변 텍스트로 설명하거나 단독으로 사용할 때 role과 접근 가능한 이름을 지정하세요.</p></>}<p>실행 예제에서는 버튼의 동작과 진행·비활성 상태를 비교할 수 있습니다.</p></GalleryDocs>
 </div>;
}
