import {GalleryDocs,GalleryControls} from './workbench';
import React from 'react';
import { Icon, IconAction, iconNames, type IconName } from '../components/icons';
import { Button, Input, type ButtonProps } from '../components/atoms';
import { Checkbox, Select } from '../components/primitives';
import { CodeBlock } from './code-block';
import '../examples.css';
export const iconDetailNames=['Icon','IconAction'] as const;
export type IconDetailName=typeof iconDetailNames[number];
export function hasIconDetail(name:string):name is IconDetailName{return (iconDetailNames as readonly string[]).includes(name);}
export function IconDetail({name}:{name:IconDetailName}) {
 const action=name==='IconAction';
 const [icon,setIcon]=React.useState<IconName>('search'),[svgSize,setSvgSize]=React.useState(20),[strokeWidth,setStrokeWidth]=React.useState(1.75),[color,setColor]=React.useState('currentColor'),[label,setLabel]=React.useState('검색 확인'),[variant,setVariant]=React.useState<NonNullable<ButtonProps['variant']>>('secondary'),[size,setSize]=React.useState<NonNullable<ButtonProps['size']>>('medium'),[loading,setLoading]=React.useState(false),[disabled,setDisabled]=React.useState(false),[id,setId]=React.useState('icon-action-example'),[count,setCount]=React.useState(0),[last,setLast]=React.useState('');
 const reset=()=>{setIcon('search');setSvgSize(20);setStrokeWidth(1.75);setColor('currentColor');setLabel('검색 확인');setVariant('secondary');setSize('medium');setLoading(false);setDisabled(false);setId('icon-action-example');setCount(0);setLast('');};
 const source=action?`import { useState } from 'react';\nimport { IconAction } from './src';\nimport './src/core.css';\nimport './src/examples.css';\n\nexport function Example() {\n  const [count, setCount] = useState(${count});\n  const [last, setLast] = useState(${JSON.stringify(last)});\n  return <div className="ds-core">\n    <IconAction name=${JSON.stringify(icon)} label={${JSON.stringify(label)}} variant=${JSON.stringify(variant)} size=${JSON.stringify(size)} type="button" id={${JSON.stringify(id)}} loading={${loading}} disabled={${disabled}}\n      onClick={event => { setCount(n => n + 1); setLast(event.currentTarget.id); }} />\n    <p role="status">실행 {count}회 · 최근 버튼 id: {last || '없음'}</p>\n  </div>;\n}`:`import { Icon } from './src';\nimport './src/core.css';\nimport './src/examples.css';\n\nexport function Example() {\n  return <div className="ds-core">\n    <span className="example-icon-inline">\n      <Icon name=${JSON.stringify(icon)} size={${svgSize}} strokeWidth={${strokeWidth}} color={${JSON.stringify(color)}} />\n      <span>아이콘: {${JSON.stringify(icon)}}</span>\n    </span>\n  </div>;\n}`;
 const numeric=(caption:string,value:number,set:(n:number)=>void,min:number,max:number,step:number,aria:string)=><label className="field"><span>{caption}</span><Input type="number" aria-label={aria} min={min} max={max} step={step} value={value} onChange={event=>{const next=Number(event.target.value);if(Number.isFinite(next))set(Math.min(max,Math.max(min,next)));}}/></label>;
 return <div className="connected-detail stack" data-icon-detail={name}>
  <div data-icon-preview>{action?<><IconAction name={icon} label={label} variant={variant} size={size} type="button" id={id} loading={loading} disabled={disabled} onClick={event=>{setCount(n=>n+1);setLast(event.currentTarget.id);}}/><p role="status" className="help">실행 {count}회 · 최근 버튼 id: {last||'없음'}</p></>:<span className="example-icon-inline"><Icon name={icon} size={svgSize} strokeWidth={strokeWidth} color={color}/><span>아이콘: {icon}</span></span>}</div>
  <GalleryControls className="form-detail-controls">
   <label className="field"><span>name</span><Select aria-label="icon name control" value={icon} onChange={event=>setIcon(event.target.value as IconName)}>{iconNames.map(item=><option key={item} value={item}>{item}</option>)}</Select></label>
   {action?<><label className="field"><span>label · 접근 가능한 버튼 이름</span><Input aria-label="icon action label control" value={label} onChange={event=>setLabel(event.target.value)}/></label><label className="field"><span>id · native button</span><Input aria-label="icon action id control" value={id} onChange={event=>setId(event.target.value)}/></label><label className="field"><span>variant</span><Select aria-label="icon action variant control" value={variant} onChange={event=>setVariant(event.target.value as NonNullable<ButtonProps['variant']>)}>{(['primary','secondary','quiet','ghost','destructive'] as const).map(value=><option key={value}>{value}</option>)}</Select></label><label className="field"><span>size · 버튼 prop</span><Select aria-label="icon action size control" value={size} onChange={event=>setSize(event.target.value as NonNullable<ButtonProps['size']>)}>{(['small','medium','large'] as const).map(value=><option key={value}>{value}</option>)}</Select></label><div className="wrap"><Checkbox label="loading" checked={loading} onChange={event=>setLoading(event.target.checked)}/><Checkbox label="disabled" checked={disabled} onChange={event=>setDisabled(event.target.checked)}/></div></>:<>{numeric('size · SVG',svgSize,setSvgSize,8,96,1,'icon svg size control')}{numeric('strokeWidth',strokeWidth,setStrokeWidth,0.5,4,0.25,'icon stroke width control')}<label className="field"><span>color · SVG 상속 prop</span><Select aria-label="icon color control" value={color} onChange={event=>setColor(event.target.value)}><option value="currentColor">currentColor · 주변 텍스트 색</option><option value="#2563eb">파랑 · #2563eb</option><option value="#334155">회색 · #334155</option></Select></label></>}
   <Button variant="ghost" onClick={reset}>초기화</Button>
  </GalleryControls>
  <GalleryDocs open><summary>현재 코드</summary><CodeBlock source={source}/></GalleryDocs>
  <GalleryDocs><summary>Props · 아이콘과 버튼</summary>{action?<><p>IconAction은 name/label과 children을 제외한 ButtonProps를 받으며 기존 IconButton → Button 조합입니다. IconButton의 alias가 아니고 SVG size/strokeWidth/iconProps/children prop은 없습니다. size는 small/medium/large 버튼 prop입니다. 기본 버튼은48×48px·SVG20px입니다. large에는 기존 Button의 padding/최소 높이56px 규칙도 적용되므로 모든 size의 버튼을48px 고정이라고 안내하지 않습니다. SVG는 size로 확대되지 않습니다.</p><p>label은 버튼 aria-label이며 전달한 className/aria-label보다 IconButton의 icon-button/label이 우선합니다. native button attrs/id/type/form 및 mouse event를 전달하며 기본 type=button, variant=secondary, size=medium입니다. 이 예제는 명시적 type=button이고 callback에서 currentTarget.id를 기록합니다.</p><p>loading은 aria-busy/aria-disabled·장식 spinner를 추가하며 native disabled로 바꾸지 않습니다. click default와 onClick을 막지만 모든 종류의 이벤트를 차단하는 계약은 아닙니다. disabled는 별도 native disabled입니다. submit은 type=submit/native form과 부모 중복실행 방어가 필요하고 서버 처리/저장 기능은 없습니다. 세 wrapper는 forwardRef/ref API를 제공하지 않습니다.</p></>:<><p>필수 name은 iconNames의 정적 Lucide subset입니다. 기본 size=20/strokeWidth=1.75/currentColor이며 color/stroke/SVG attributes·이벤트는 상속 prop입니다. 이 예제의 숫자 범위는 controls 범위이고 public size는 string 또는 number입니다. 별도 tone API/전체 팩 runtime registry/잘못된 name fallback/ref API는 없습니다.</p><p>기본 aria-hidden=true/focusable=false인 장식 SVG이고 주변 텍스트가 의미를 전달합니다. 상속 props spread로 해당 attributes를 소비자가 override할 수 있으므로 항상 장식용으로 강제된다고 설명하지 않습니다. 의미 있는 단독 SVG의 접근성 이름/role은 소비자가 명시해야 합니다.</p></>}<p>실행 횟수와 최근 id는 부모 메모리 예제입니다. 초기화는 실제 props와 부모 기록을 복원합니다.</p></GalleryDocs>
 </div>;
}
