import {GalleryDocs,GalleryControls} from './workbench';
import React from 'react';
import { Button, Input, type ButtonProps } from '../components/atoms';
import { Textarea, Select, Checkbox, IconButton } from '../components/primitives';
import { FormField } from '../components/molecules';
import { Icon, iconNames, type IconName } from '../components/icons';
import { CodeBlock } from './code-block';
export const nativeInputDetailNames=['Input','Textarea','Select','Checkbox','FormField','IconButton'] as const;
type Name=typeof nativeInputDetailNames[number];
export function hasNativeInputDetail(name:string):name is Name{return (nativeInputDetailNames as readonly string[]).includes(name);}
export function NativeInputDetail({name}:{name:Name}) {
 const [value,setValue]=React.useState(name==='Select'?'a':'예시 내용'),[label,setLabel]=React.useState('예제 입력'),[placeholder,setPlaceholder]=React.useState('내용을 입력하세요.'),[disabled,setDisabled]=React.useState(false),[required,setRequired]=React.useState(false),[readOnly,setReadOnly]=React.useState(false),[error,setError]=React.useState(false),[loading,setLoading]=React.useState(false),[checked,setChecked]=React.useState(false),[mixed,setMixed]=React.useState(false),[rows,setRows]=React.useState(3),[child,setChild]=React.useState(false),[variant,setVariant]=React.useState<ButtonProps['variant']>('secondary'),[size,setSize]=React.useState<ButtonProps['size']>('medium'),[icon,setIcon]=React.useState<IconName>('check'),[count,setCount]=React.useState(0),[revision,setRevision]=React.useState(0);
 const textual=name==='Input'||name==='Textarea'||name==='FormField';
 const reset=()=>{setValue(name==='Select'?'a':'예시 내용');setLabel('예제 입력');setPlaceholder('내용을 입력하세요.');setDisabled(false);setRequired(false);setReadOnly(false);setError(false);setLoading(false);setChecked(false);setMixed(false);setRows(3);setChild(false);setVariant('secondary');setSize('medium');setIcon('check');setCount(0);setRevision(current=>current+1);};
 const native={id:'native-example',name:'example',disabled,required};
 const input={...native,value,onChange:(event:React.ChangeEvent<HTMLInputElement>)=>setValue(event.currentTarget.value),readOnly,placeholder};
 const errorText=error?'입력 내용을 확인하세요.':undefined;
 const preview=name==='Input'?<Input {...input} loading={loading} busyLabel="입력 확인 중…" aria-label={label} aria-invalid={error}/>:name==='Textarea'?<Textarea {...native} aria-label={label} aria-invalid={error} value={value} onChange={event=>setValue(event.currentTarget.value)} readOnly={readOnly} placeholder={placeholder} rows={rows}/>:name==='Select'?<Select {...native} aria-label={label} aria-invalid={error} value={value} onChange={event=>setValue(event.currentTarget.value)}><option value="a">첫 항목</option><option value="b">둘째 항목</option></Select>:name==='Checkbox'?<Checkbox {...native} label={label} checked={checked} mixed={mixed} onChange={event=>setChecked(event.currentTarget.checked)}/>:name==='FormField'?child?<FormField label={label} id={native.id} required={required} description="입력 예시입니다." error={errorText}><Input {...input}/></FormField>:<FormField {...input} label={label} description="입력 예시입니다." error={errorText}/>:<IconButton id="native-example" label={label} disabled={disabled} loading={loading} variant={variant} size={size} onClick={()=>setCount(current=>current+1)}><Icon name={icon}/></IconButton>;
 const flags=`id="native-example" name="example" disabled={${disabled}} required={${required}}`;
 const inputFlags=`${flags} value={value} onChange={event => setValue(event.currentTarget.value)} readOnly={${readOnly}} placeholder={${JSON.stringify(placeholder)}}`;
 const fieldFlags=`label={${JSON.stringify(label)}} id="native-example" required={${required}} description="입력 예시입니다."${errorText?` error={${JSON.stringify(errorText)}}`:''}`;
 const component=name==='Input'?`<Input ${inputFlags} aria-label={${JSON.stringify(label)}} aria-invalid={${error}} loading={${loading}} busyLabel="입력 확인 중…" />`:name==='Textarea'?`<Textarea ${inputFlags} aria-label={${JSON.stringify(label)}} aria-invalid={${error}} rows={${rows}} />`:name==='Select'?`<Select ${flags} aria-label={${JSON.stringify(label)}} aria-invalid={${error}} value={value} onChange={event => setValue(event.currentTarget.value)}><option value="a">첫 항목</option><option value="b">둘째 항목</option></Select>`:name==='Checkbox'?`<Checkbox ${flags} label={${JSON.stringify(label)}} checked={checked} mixed={${mixed}} onChange={event => setChecked(event.currentTarget.checked)} />`:name==='FormField'?child?`<FormField ${fieldFlags}><Input ${inputFlags} /></FormField>`:`<FormField ${inputFlags} label={${JSON.stringify(label)}} description="입력 예시입니다."${errorText?` error={${JSON.stringify(errorText)}}`:''} />`:`<IconButton id="native-example" label={${JSON.stringify(label)}} disabled={${disabled}} loading={${loading}} variant={${JSON.stringify(variant)}} size={${JSON.stringify(size)}} onClick={() => setCount(current => current + 1)}><Icon name={${JSON.stringify(icon)}} /></IconButton>`;
 const owner=name==='Checkbox'?`const [checked, setChecked] = useState(${checked});`:name==='IconButton'?`const [count, setCount] = useState(${count});`:`const [value, setValue] = useState(${JSON.stringify(value)});`;
 const imports=name==='IconButton'?', Icon':name==='FormField'&&child?', Input':'';
 const status=name==='Checkbox'?'String(checked)':name==='IconButton'?'count':'value';
 const source=`import { useState } from 'react';\nimport { ${name}${imports} } from './src';\nimport './src/core.css';\n\nexport function Example() {\n  ${owner}\n  return <div className="ds-core">\n    ${component}\n    <p role="status">부모 값: {${status}}</p>\n  </div>;\n}`;
 return <div className="connected-detail stack" data-native-input-detail={name}>
  <div className="connected-preview" data-native-input-preview key={revision}>{preview}<p role="status" className="help">부모 값: {name==='Checkbox'?String(checked):name==='IconButton'?count:value}</p></div>
  <GalleryControls className="form-detail-controls">
   <label className="field"><span>label / aria-label</span><Input aria-label="native label control" value={label} onChange={event=>setLabel(event.target.value)}/></label>
   {textual&&<><label className="field"><span>value · 부모 상태</span><Input aria-label="native value control" value={value} onChange={event=>setValue(event.target.value)}/></label><label className="field"><span>placeholder</span><Input aria-label="native placeholder control" value={placeholder} onChange={event=>setPlaceholder(event.target.value)}/></label></>}
   {name==='Select'&&<label className="field"><span>value · 부모 상태</span><Select aria-label="native value control" value={value} onChange={event=>setValue(event.target.value)}><option value="a">첫 항목</option><option value="b">둘째 항목</option></Select></label>}
   <div className="wrap"><Checkbox label="disabled" checked={disabled} onChange={event=>setDisabled(event.target.checked)}/>{name!=='IconButton'&&<Checkbox label="required" checked={required} onChange={event=>setRequired(event.target.checked)}/>} {textual&&<Checkbox label="readOnly" checked={readOnly} onChange={event=>setReadOnly(event.target.checked)}/>} {(textual||name==='Select')&&<Checkbox label={name==='FormField'?'error':'aria-invalid'} checked={error} onChange={event=>setError(event.target.checked)}/>} {(name==='Input'||name==='IconButton')&&<Checkbox label="loading" checked={loading} onChange={event=>setLoading(event.target.checked)}/>}</div>
   {name==='Textarea'&&<label className="field"><span>rows</span><Select aria-label="native rows control" value={rows} onChange={event=>setRows(Number(event.target.value))}><option value={3}>3</option><option value={6}>6</option></Select></label>}
   {name==='Checkbox'&&<div className="wrap"><Checkbox label="checked" checked={checked} onChange={event=>setChecked(event.target.checked)}/><Checkbox label="mixed" checked={mixed} onChange={event=>setMixed(event.target.checked)}/></div>}
   {name==='FormField'&&<Checkbox label="children 분기 · Input 슬롯" checked={child} onChange={event=>setChild(event.target.checked)}/>}
   {name==='IconButton'&&<div className="wrap"><label className="field"><span>variant</span><Select aria-label="native variant control" value={variant} onChange={event=>setVariant(event.target.value as ButtonProps['variant'])}>{['primary','secondary','quiet','ghost','destructive'].map(item=><option key={item} value={item}>{item}</option>)}</Select></label><label className="field"><span>size · 버튼</span><Select aria-label="native size control" value={size} onChange={event=>setSize(event.target.value as ButtonProps['size'])}>{['small','medium','large'].map(item=><option key={item} value={item}>{item}</option>)}</Select></label><label className="field"><span>children · Icon 예시</span><Select aria-label="native icon control" value={icon} onChange={event=>setIcon(event.target.value as IconName)}>{iconNames.map(item=><option key={item} value={item}>{item}</option>)}</Select></label></div>}
   <Button variant="ghost" onClick={reset}>초기화</Button>
  </GalleryControls>
  <GalleryDocs open><summary>현재 코드</summary><CodeBlock source={source}/></GalleryDocs>
  <GalleryDocs><summary>속성 · 입력값</summary><p>{name==='IconButton'?'label에 동작 이름을, children에 아이콘을 넣습니다. variant·size·loading과 button 속성을 전달할 수 있습니다. 기본 variant는 secondary, type은 button입니다. size는 버튼 크기이며 아이콘 크기는 children에서 정합니다.':'HTML 입력 속성과 DOM 이벤트를 전달할 수 있습니다. value/checked로 값을 관리하거나 defaultValue/defaultChecked로 초기값을 지정하세요. disabled는 조작과 제출을 제한합니다. 텍스트 입력에는 readOnly를 지정해 읽기만 허용할 수 있습니다.'}</p>{name==='Input'&&<p>loading은 입력 옆에 진행 상태를 안내합니다. 입력 편집은 유지하므로 편집을 막아야 하면 readOnly나 disabled를 함께 지정하세요. 기존 aria-describedby와 진행 안내를 연결합니다.</p>}{name==='Checkbox'&&<p>mixed는 일부만 선택된 상태를 표시하며 checked와 별도로 설정합니다. onChange에서 checked를 받아 선택을 갱신하세요. 라벨 전체를 눌러 선택할 수 있습니다.</p>}{name==='FormField'&&<p>FormField에 children을 넣으면 라벨과 설명·오류를 해당 입력에 연결합니다. value·onChange·disabled·readOnly·placeholder는 children의 입력에 설정하세요. children을 생략하면 Input을 표시합니다.</p>}<p>예제의 초기화 버튼은 입력값과 설정을 시작 상태로 되돌립니다. 폼의 제어 값을 초기화할 때도 앱의 값을 함께 갱신하세요.</p></GalleryDocs>
 </div>;
}
