import React from 'react';
import { Button, Input, type ButtonProps } from '../components/atoms';
import { Textarea, Select, Checkbox, IconButton } from '../components/primitives';
import { FormField } from '../components/molecules';
import { Icon, iconNames, type IconName } from '../components/icons';
import { CodeBlock } from './code-block';
export const nativeInputDetailNames=['Input','Textarea','Select','Checkbox','FormField','IconButton'] as const;
type Name=typeof nativeInputDetailNames[number];
export function hasNativeInputDetail(name:string):name is Name{return (nativeInputDetailNames as readonly string[]).includes(name);}
export function NativeInputDetail({name}:{name:Name}) {
 const [value,setValue]=React.useState(name==='Select'?'a':'예시 내용'),[label,setLabel]=React.useState('예제 입력'),[placeholder,setPlaceholder]=React.useState('내용을 입력하세요.'),[disabled,setDisabled]=React.useState(false),[required,setRequired]=React.useState(false),[readOnly,setReadOnly]=React.useState(false),[error,setError]=React.useState(false),[loading,setLoading]=React.useState(false),[checked,setChecked]=React.useState(false),[mixed,setMixed]=React.useState(false),[rows,setRows]=React.useState(3),[child,setChild]=React.useState(false),[variant,setVariant]=React.useState<ButtonProps['variant']>('secondary'),[size,setSize]=React.useState<ButtonProps['size']>('medium'),[icon,setIcon]=React.useState<IconName>('check'),[count,setCount]=React.useState(0),[revision,setRevision]=React.useState(0);
 const textual=name==='Input'||name==='Textarea'||name==='FormField';
 const reset=()=>{setValue(name==='Select'?'a':'예시 내용');setLabel('예제 입력');setPlaceholder('내용을 입력하세요.');setDisabled(false);setRequired(false);setReadOnly(false);setError(false);setLoading(false);setChecked(false);setMixed(false);setRows(3);setChild(false);setVariant('secondary');setSize('medium');setIcon('check');setCount(0);setRevision(current=>current+1);};
 const native={id:'native-example',name:'example',disabled,required};
 const input={...native,value,onChange:(event:React.ChangeEvent<HTMLInputElement>)=>setValue(event.currentTarget.value),readOnly,placeholder};
 const errorText=error?'입력 내용을 확인하세요.':undefined;
 const preview=name==='Input'?<Input {...input} loading={loading} busyLabel="입력 확인 중…" aria-label={label} aria-invalid={error}/>:name==='Textarea'?<Textarea {...native} aria-label={label} aria-invalid={error} value={value} onChange={event=>setValue(event.currentTarget.value)} readOnly={readOnly} placeholder={placeholder} rows={rows}/>:name==='Select'?<Select {...native} aria-label={label} aria-invalid={error} value={value} onChange={event=>setValue(event.currentTarget.value)}><option value="a">첫 항목</option><option value="b">둘째 항목</option></Select>:name==='Checkbox'?<Checkbox {...native} label={label} checked={checked} mixed={mixed} onChange={event=>setChecked(event.currentTarget.checked)}/>:name==='FormField'?child?<FormField label={label} id={native.id} required={required} description="입력 예시입니다." error={errorText}><Input {...input}/></FormField>:<FormField {...input} label={label} description="입력 예시입니다." error={errorText}/>:<IconButton id="native-example" label={label} disabled={disabled} loading={loading} variant={variant} size={size} onClick={()=>setCount(current=>current+1)}><Icon name={icon}/></IconButton>;
 const flags=`id="native-example" name="example" disabled={${disabled}} required={${required}}`;
 const inputFlags=`${flags} value={value} onChange={event => setValue(event.currentTarget.value)} readOnly={${readOnly}} placeholder={${JSON.stringify(placeholder)}}`;
 const fieldFlags=`label={${JSON.stringify(label)}} id="native-example" required={${required}} description="입력 예시입니다."${errorText?` error={${JSON.stringify(errorText)}}`:''}`;
 const component=name==='Input'?`<Input ${inputFlags} aria-label={${JSON.stringify(label)}} aria-invalid={${error}} loading={${loading}} busyLabel="입력 확인 중…" />`:name==='Textarea'?`<Textarea ${inputFlags} aria-label={${JSON.stringify(label)}} aria-invalid={${error}} rows={${rows}} />`:name==='Select'?`<Select ${flags} aria-label={${JSON.stringify(label)}} aria-invalid={${error}} value={value} onChange={event => setValue(event.currentTarget.value)}><option value="a">첫 항목</option><option value="b">둘째 항목</option></Select>`:name==='Checkbox'?`<Checkbox ${flags} label={${JSON.stringify(label)}} checked={checked} mixed={${mixed}} onChange={event => setChecked(event.currentTarget.checked)} />`:name==='FormField'?child?`<FormField ${fieldFlags}><Input ${inputFlags} /></FormField>`:`<FormField ${inputFlags} label={${JSON.stringify(label)}} description="입력 예시입니다."${errorText?` error={${JSON.stringify(errorText)}}`:''} />`:`<IconButton id="native-example" label={${JSON.stringify(label)}} disabled={${disabled}} loading={${loading}} variant=${JSON.stringify(variant)} size=${JSON.stringify(size)} onClick={() => setCount(current => current + 1)}><Icon name=${JSON.stringify(icon)} /></IconButton>`;
 const owner=name==='Checkbox'?`const [checked, setChecked] = useState(${checked});`:name==='IconButton'?`const [count, setCount] = useState(${count});`:`const [value, setValue] = useState(${JSON.stringify(value)});`;
 const imports=name==='IconButton'?', Icon':name==='FormField'&&child?', Input':'';
 const status=name==='Checkbox'?'String(checked)':name==='IconButton'?'count':'value';
 const source=`import { useState } from 'react';\nimport { ${name}${imports} } from './src';\nimport './src/core.css';\n\nexport function Example() {\n  ${owner}\n  return <div className="ds-core">\n    ${component}\n    <p role="status">부모 값: {${status}}</p>\n  </div>;\n}`;
 return <div className="connected-detail stack" data-native-input-detail={name}>
  <div className="connected-preview" data-native-input-preview key={revision}>{preview}<p role="status" className="help">부모 값: {name==='Checkbox'?String(checked):name==='IconButton'?count:value}</p></div>
  <div className="form-detail-controls">
   <label className="field"><span>label / aria-label</span><Input aria-label="native label control" value={label} onChange={event=>setLabel(event.target.value)}/></label>
   {textual&&<><label className="field"><span>value · 부모 상태</span><Input aria-label="native value control" value={value} onChange={event=>setValue(event.target.value)}/></label><label className="field"><span>placeholder</span><Input aria-label="native placeholder control" value={placeholder} onChange={event=>setPlaceholder(event.target.value)}/></label></>}
   {name==='Select'&&<label className="field"><span>value · 부모 상태</span><Select aria-label="native value control" value={value} onChange={event=>setValue(event.target.value)}><option value="a">첫 항목</option><option value="b">둘째 항목</option></Select></label>}
   <div className="wrap"><Checkbox label="disabled" checked={disabled} onChange={event=>setDisabled(event.target.checked)}/>{name!=='IconButton'&&<Checkbox label="required" checked={required} onChange={event=>setRequired(event.target.checked)}/>} {textual&&<Checkbox label="readOnly" checked={readOnly} onChange={event=>setReadOnly(event.target.checked)}/>} {(textual||name==='Select')&&<Checkbox label={name==='FormField'?'error':'aria-invalid'} checked={error} onChange={event=>setError(event.target.checked)}/>} {(name==='Input'||name==='IconButton')&&<Checkbox label="loading" checked={loading} onChange={event=>setLoading(event.target.checked)}/>}</div>
   {name==='Textarea'&&<label className="field"><span>rows</span><Select aria-label="native rows control" value={rows} onChange={event=>setRows(Number(event.target.value))}><option value={3}>3</option><option value={6}>6</option></Select></label>}
   {name==='Checkbox'&&<div className="wrap"><Checkbox label="checked" checked={checked} onChange={event=>setChecked(event.target.checked)}/><Checkbox label="mixed" checked={mixed} onChange={event=>setMixed(event.target.checked)}/></div>}
   {name==='FormField'&&<Checkbox label="children 분기 · Input 슬롯" checked={child} onChange={event=>setChild(event.target.checked)}/>}
   {name==='IconButton'&&<div className="wrap"><label className="field"><span>variant</span><Select aria-label="native variant control" value={variant} onChange={event=>setVariant(event.target.value as ButtonProps['variant'])}>{['primary','secondary','quiet','ghost','destructive'].map(item=><option key={item} value={item}>{item}</option>)}</Select></label><label className="field"><span>size · 버튼</span><Select aria-label="native size control" value={size} onChange={event=>setSize(event.target.value as ButtonProps['size'])}>{['small','medium','large'].map(item=><option key={item} value={item}>{item}</option>)}</Select></label><label className="field"><span>children · Icon 예시</span><Select aria-label="native icon control" value={icon} onChange={event=>setIcon(event.target.value as IconName)}>{iconNames.map(item=><option key={item} value={item}>{item}</option>)}</Select></label></div>}
   <Button variant="ghost" onClick={reset}>초기화</Button>
  </div>
  <details open><summary>현재 코드</summary><CodeBlock source={source}/></details>
  <details><summary>Props · 값 소유권</summary><p>{name==='IconButton'?'label은 필수 접근성 이름, children은 임의 ReactNode입니다. Button의 variant/size/loading 및 native button 속성/이벤트를 받으며 기본 variant는 secondary, type은 button입니다. loading은 aria-busy/aria-disabled와 click guard이고 native disabled와 다릅니다. label/className은 wrapper에서 지정되며 ref API는 없습니다. SVG 크기는 children이 소유합니다.':'native 속성과 실제 DOM 이벤트를 전달합니다. 위 예제의 value/checked는 부모 상태이며 일반 편집은 같은 DOM을 유지합니다. 각 native 요소가 지원하는 defaultValue 또는 defaultChecked는 비제어형 초기값이며 disabled와 readOnly는 다른 계약입니다. Select와 Checkbox에 readOnly를 대신 구현하지 않습니다.'}</p>{name==='Input'&&<p>loading/busyLabel은 기존 입력과 별도의 status 안내를 유지합니다. loading은 native disabled나 자동 편집 차단이 아닙니다. aria-describedby에 busy 설명을 추가하고 기존 설명 ID도 유지합니다.</p>}{name==='Checkbox'&&<p>mixed는 native indeterminate 표시이며 checked와 독립입니다. onChange는 native checked 값을 전달합니다. label의 전체 영역이 클릭 대상입니다.</p>}{name==='FormField'&&<p>children이 없으면 native Input 속성을 fallback Input으로 전달합니다. children이 있으면 id/aria-describedby/aria-invalid/required 연결만 clone하며 value/onChange/disabled/readOnly/placeholder는 child에 직접 설정해야 합니다. 기존 ARIA 설명 병합이나 전체 native 속성 전달을 새로 보장하지 않습니다.</p>}<p>초기화는 예제 부모의 값/설정/기록과 preview 내부 상태를 초기화합니다. native form.reset 검증이나 저장/서버 요청이 아닙니다.</p></details>
 </div>;
}
