import React from 'react';
import { DesktopWorkspaceTemplate, MobileWorkspaceTemplate } from '../components/workspace-templates';
import { Button, Input } from '../components/atoms';
import { Checkbox } from '../components/primitives';
import { CodeBlock } from './code-block';
import '../examples.css';
export const workspaceDetailNames=['DesktopWorkspaceTemplate','MobileWorkspaceTemplate'] as const;
export type WorkspaceDetailName=typeof workspaceDetailNames[number];
export function hasWorkspaceDetail(name:string):name is WorkspaceDetailName{return (workspaceDetailNames as readonly string[]).includes(name);}
type Row={id:string;title:string;team:string;status:string};
const sampleRows:Row[]=Array.from({length:7},(_,i)=>({id:`doc-${i+1}`,title:`문서 ${i+1}`,team:i%2?'개발':'디자인',status:'확인 전'}));
const navItems=[{id:'documents',label:'문서'},{id:'examples',label:'예시'},{id:'settings',label:'설정',disabled:true}];
const groups=[{id:'library',label:'라이브러리',items:[{id:'all',label:'전체 문서'},{id:'recent',label:'최근 문서'}]}];
const rowType='type Row = { id: string; title: string; team: string; status: string };';
export function WorkspaceDetail({name}:{name:WorkspaceDetailName}) {
 const desktop=name==='DesktopWorkspaceTemplate';
 const [title,setTitle]=React.useState(desktop?'문서 작업 공간':'모바일 문서 작업'),[caption,setCaption]=React.useState('문서 목록'),[rows,setRows]=React.useState(sampleRows),[navId,setNavId]=React.useState('documents'),[localId,setLocalId]=React.useState('all'),[selectedKeys,setSelectedKeys]=React.useState<React.Key[]>([]),[actionRecord,setActionRecord]=React.useState(''),[applyRecord,setApplyRecord]=React.useState(''),[headerCount,setHeaderCount]=React.useState(0),[showHeader,setShowHeader]=React.useState(true),[showFooter,setShowFooter]=React.useState(true),[showAside,setShowAside]=React.useState(true),[showBreadcrumbs,setShowBreadcrumbs]=React.useState(true),[showFilter,setShowFilter]=React.useState(true),[showBulk,setShowBulk]=React.useState(true),[loading,setLoading]=React.useState(false),[error,setError]=React.useState(false),[showDescription,setShowDescription]=React.useState(true),[extendedSearch,setExtendedSearch]=React.useState(false),[empty,setEmpty]=React.useState(false),[pageSize,setPageSize]=React.useState(3),[prefix,setPrefix]=React.useState(''),[detailText,setDetailText]=React.useState('이 항목을 로컬에서 확인합니다.'),[revision,setRevision]=React.useState(0);
 const data=empty?[]:rows;
 const navigation={items:navItems,selectedId:navId,onSelect:setNavId,label:'예제 전체 탐색'};
 const headerActions=showHeader?<Button variant="secondary" onClick={()=>setHeaderCount(n=>n+1)}>로컬 헤더 확인</Button>:undefined;
 const footer=showFooter?<p className="help">전체 {data.length}개 · 메모리 예시</p>:undefined;
 const bulk=(chosen:Row[])=>setActionRecord(chosen.map(row=>row.title).join(', '));
 const apply=(row:Row)=>{setApplyRecord(row.title);setRows(current=>current.map(item=>item.id===row.id?{...item,status:'확인됨'}:item));};
 const reset=()=>{setTitle(desktop?'문서 작업 공간':'모바일 문서 작업');setCaption('문서 목록');setRows(sampleRows);setNavId('documents');setLocalId('all');setSelectedKeys([]);setActionRecord('');setApplyRecord('');setHeaderCount(0);setShowHeader(true);setShowFooter(true);setShowAside(true);setShowBreadcrumbs(true);setShowFilter(true);setShowBulk(true);setLoading(false);setError(false);setShowDescription(true);setExtendedSearch(false);setEmpty(false);setPageSize(3);setPrefix('');setDetailText('이 항목을 로컬에서 확인합니다.');setRevision(n=>n+1);};
 const input=(label:string,value:string,set:(value:string)=>void,aria:string)=><label className="field"><span>{label}</span><Input aria-label={aria} value={value} onChange={event=>set(event.target.value)}/></label>;
 const flag=(label:string,value:boolean,set:(value:boolean)=>void)=><Checkbox label={label} checked={value} onChange={event=>set(event.target.checked)}/>;
 const commonProps={title,navigation,headerActions,footer};
 const preview=desktop?<DesktopWorkspaceTemplate<Row> {...commonProps} localNavigation={{groups,selectedId:localId,onSelect:setLocalId,label:'예제 영역 탐색'}} breadcrumbs={showBreadcrumbs?[{label:'문서',href:'#/components/desktop-workspace-template'},{label:'작업 공간'}]:undefined} aside={showAside?<p className="example-wrap-text">현재 영역: {localId}</p>:undefined} table={{caption,rows:data,columns:[{id:'title',header:'문서',value:row=>row.title,sortable:true,render:row=><strong>{row.title}</strong>},{id:'team',header:'담당',value:row=>row.team,sortable:true},{id:'status',header:'상태',value:row=>row.status}],rowKey:row=>row.id,rowLabel:row=>row.title,initialPageSize:pageSize,loading,error:error?'로컬 오류 상태 예시입니다.':undefined,onRetry:error?()=>setError(false):undefined,filter:showFilter?{label:'담당',value:row=>row.team,options:['디자인','개발']}:undefined,bulkAction:showBulk?{label:'선택 기록',onAction:bulk}:undefined}}/>:<MobileWorkspaceTemplate<Row> {...commonProps} rows={data} rowKey={row=>row.id} itemTitle={row=>prefix+row.title} itemDescription={showDescription?row=>`${row.team} · ${row.status}`:undefined} searchText={extendedSearch?row=>`${row.title} ${row.team} ${row.status}`:undefined} selectedKeys={selectedKeys} onSelectionChange={setSelectedKeys} selectedAction={{label:'선택 기록',onAction:bulk}} renderDetail={row=><><p className="example-wrap-text">{detailText}</p><p>{row.title} · {row.team} · {row.status}</p></>} onApply={apply}/>;
 let declarations=`const [navId, setNavId] = useState(${JSON.stringify(navId)});\n${showHeader?`const [headerCount, setHeaderCount] = useState(${headerCount});`:`const headerCount = ${headerCount};`}\nconst [actionRecord${desktop&&!showBulk?'':', setActionRecord'}] = useState(${JSON.stringify(actionRecord)});\n`;
 const common=`title={${JSON.stringify(title)}}\n  navigation={{ items: ${JSON.stringify(navItems)}, selectedId: navId, onSelect: setNavId, label: '예제 전체 탐색' }}${showHeader?'\n  headerActions={<Button variant="secondary" onClick={() => setHeaderCount(n => n + 1)}>로컬 헤더 확인</Button>}':''}${showFooter?'\n  footer={<p>전체 {data.length}개 · 메모리 예시</p>}':''}`;
 let content:string;
 if(desktop){
  declarations+=`const rows: Row[] = ${JSON.stringify(rows)};\nconst data = ${empty?'rows.slice(0, 0)':'rows'};\nconst [localId, setLocalId] = useState(${JSON.stringify(localId)});\n${error?'const [error, setError] = useState(true);\n':''}`;
  content=`<DesktopWorkspaceTemplate<Row>\n  ${common}\n  localNavigation={{ groups: ${JSON.stringify(groups)}, selectedId: localId, onSelect: setLocalId, label: '예제 영역 탐색' }}${showBreadcrumbs?'\n  breadcrumbs={[{ label: \'문서\', href: \'#/components/desktop-workspace-template\' }, { label: \'작업 공간\' }]}':''}${showAside?'\n  aside={<p className="example-wrap-text">현재 영역: {localId}</p>}':''}\n  table={{ caption: ${JSON.stringify(caption)}, rows: data,\n    columns: [{ id: 'title', header: '문서', value: row => row.title, sortable: true, render: row => <strong>{row.title}</strong> }, { id: 'team', header: '담당', value: row => row.team, sortable: true }, { id: 'status', header: '상태', value: row => row.status }],\n    rowKey: row => row.id, rowLabel: row => row.title, initialPageSize: ${pageSize}, loading: ${loading}${error?',\n    error: error ? \'로컬 오류 상태 예시입니다.\' : undefined, onRetry: () => setError(false)':''}${showFilter?",\n    filter: { label: '담당', value: row => row.team, options: ['디자인', '개발'] }":''}${showBulk?",\n    bulkAction: { label: '선택 기록', onAction: chosen => setActionRecord(chosen.map(row => row.title).join(', ')) }":''}\n  }}\n/>\n<p role="status">부모 전체 선택: {navId} · 영역: {localId} · 헤더 {headerCount}회 · 선택작업: {actionRecord || '없음'}</p>`;
 }else{
  declarations+=`const [rows, setRows] = useState<Row[]>(${JSON.stringify(rows)});\nconst data = ${empty?'rows.slice(0, 0)':'rows'};\nconst [selectedKeys, setSelectedKeys] = useState<Key[]>(${JSON.stringify(selectedKeys)});\nconst [applyRecord, setApplyRecord] = useState(${JSON.stringify(applyRecord)});\n`;
  content=`<MobileWorkspaceTemplate<Row>\n  ${common}\n  rows={data} rowKey={row => row.id} itemTitle={row => ${JSON.stringify(prefix)} + row.title}${showDescription?'\n  itemDescription={row => `${row.team} · ${row.status}`}':''}${extendedSearch?'\n  searchText={row => `${row.title} ${row.team} ${row.status}`}':''}\n  selectedKeys={selectedKeys} onSelectionChange={setSelectedKeys}\n  selectedAction={{ label: '선택 기록', onAction: chosen => setActionRecord(chosen.map(row => row.title).join(', ')) }}\n  renderDetail={row => <><p className="example-wrap-text">{${JSON.stringify(detailText)}}</p><p>{row.title} · {row.team} · {row.status}</p></>}\n  onApply={row => { setApplyRecord(row.title); setRows(current => current.map(item => item.id === row.id ? { ...item, status: '확인됨' } : item)); }}\n/>\n<p role="status">부모 전체 선택: {navId} · 헤더 {headerCount}회 · 선택키: {selectedKeys.join(', ') || '없음'} · 선택작업: {actionRecord || '없음'} · 적용: {applyRecord || '없음'}</p>`;
 }
 const source=`import { useState${desktop?'':', type Key'} } from 'react';\nimport { ${name}${showHeader?', Button':''} } from './src';\nimport './src/core.css';\nimport './src/examples.css';\n${rowType}\n\nexport function Example() {\n${declarations}  return <div className="ds-core example-workspace">\n${content}\n  </div>;\n}`;
 return <div className="connected-detail stack" data-workspace-detail={name}>
  <div data-workspace-preview key={revision} className="example-workspace">{preview}</div>
  <p role="status" className="help" data-workspace-owner>부모 전체 선택: {navId}{desktop?` · 영역: ${localId}`:''} · 헤더 {headerCount}회{desktop?'':` · 선택키: ${selectedKeys.join(', ')||'없음'}`} · 선택작업: {actionRecord||'없음'}{desktop?'':` · 적용: ${applyRecord||'없음'}`}</p>
  <div className="form-detail-controls">
   {input('title',title,setTitle,'workspace title control')}
   {desktop?input('table.caption',caption,setCaption,'workspace caption control'):<>{input('itemTitle · 접두어',prefix,setPrefix,'workspace prefix control')}{input('renderDetail · 안내',detailText,setDetailText,'workspace detail text control')}</>}
   <div className="wrap">{flag('headerActions 전달',showHeader,setShowHeader)}{flag('footer 전달',showFooter,setShowFooter)}{flag('rows 빈 배열',empty,setEmpty)}</div>
   {desktop?<><label className="field"><span>table.initialPageSize · 최초 마운트값</span><Input type="number" min={1} step={1} aria-label="workspace initial page size control" value={pageSize} onChange={event=>{const next=Number(event.target.value);if(Number.isFinite(next))setPageSize(Math.max(1,Math.floor(next)));}}/></label><div className="wrap">{flag('breadcrumbs 전달',showBreadcrumbs,setShowBreadcrumbs)}{flag('aside 전달',showAside,setShowAside)}{flag('table.filter 전달',showFilter,setShowFilter)}{flag('table.bulkAction 전달',showBulk,setShowBulk)}{flag('table.loading',loading,setLoading)}{flag('table.error / onRetry 전달',error,setError)}</div><p className="help">initialPageSize는 최초값입니다. control 변경은 현재 표의 페이지 크기를 재초기화하지 않습니다.</p></>:<div className="wrap">{flag('itemDescription 전달',showDescription,setShowDescription)}{flag('searchText · 담당/상태 포함',extendedSearch,setExtendedSearch)}{flag('부모 첫 항목 선택',selectedKeys.includes('doc-1'),selected=>setSelectedKeys(keys=>selected?[...keys.filter(key=>key!=='doc-1'),'doc-1']:keys.filter(key=>key!=='doc-1')))}</div>}
   <Button variant="ghost" onClick={reset}>초기화</Button>
  </div>
  <details open><summary>현재 코드</summary><CodeBlock source={source}/></details>
  <details><summary>Props · 템플릿과 자식 상태</summary>{desktop?<><p>필수 title/navigation/localNavigation/table과 선택 breadcrumbs/headerActions/aside/footer를 조합합니다. navigation/localNavigation의 selectedId/onSelect는 부모 제어이고 자식 GNB/LNB의 펼침/그룹접기는 내부 상태입니다. 선택만으로 데이터나 URL을 바꾸지 않습니다. Breadcrumb 앞 항목은 native href, 마지막은 current span입니다.</p><p>table은 DataTable의 caption/rows/typed columns/rowKey와 실제 optional config를 전달합니다. 검색·정렬·filter·페이지·크기·선택은 DataTable 내부 소유이며 외부 query/page/selected API를 만들지 않습니다. 전체 선택은 현재 페이지에만 적용하고 bulkAction은 rows 전체에서 선택한 행을 받아 선택을 비웁니다. loading 우선/error/자식 retry는 실제 표 계약이고 저장/서버 연결이 아닙니다.</p><p>내부 Shell은 이미 mainAs="div"입니다. Workspace props에는 mainAs/일반 children/native rest가 없습니다. footer는 ListTemplate footer이며 aside는 별도 보조 영역입니다. initialPageSize 변경은 기존 내부 크기를 다시 초기화하지 않습니다. 예제 현재 코드는 새 마운트의 초기값을 보여주며 진행 중 내부 query/정렬/페이지 값을 외부 prop으로 꾸미지 않습니다.</p></>:<><p>필수 title/navigation/rows/rowKey/itemTitle/selectedKeys/onSelectionChange/selectedAction/renderDetail/onApply와 선택 itemDescription/searchText/headerActions/footer를 사용합니다. selectedKeys는 부모 제어입니다. 선택작업은 검색으로 숨은 선택도 rows 전체에서 모아 onAction에 전달하고 onSelectionChange([])를 호출합니다. 기록/적용된 rows 변경은 메모리 예제이며 저장/서버 처리하지 않습니다.</p><p>query/detailKey는 내부 상태입니다. searchText 기본은 itemTitle이고 담당/상태 포함 예시는 실제 함수 prop을 전달합니다. 외부 query/open/filter/loading/router API 없음. 상세는 rowKey로 찾는 실제 BottomSheet이고 취소/Escape는 적용하지 않습니다. 적용은 onApply 호출 후 닫힘이며 Promise/실패 대기 API가 아닙니다. Dialog의 초점/모달 계약을 재사용하고 사라진 opener에 동일 버튼 복귀를 약속하지 않습니다.</p><p>현재 코드는 실제 rows/선택키/handler/함수 슬롯과 부모 기록을 포함합니다. 내부 검색/상세 상태는 외부 props로 표시하지 않습니다.</p></>}<p>초기화는 부모 상태·optional 슬롯을 되돌리고 미리보기를 재마운트하여 자식 내부 상태도 초기화합니다. consumer 컨테이너의 minWidth/overflowWrap은 예제 소유 CSS class로 코드에도 명시합니다.</p></details>
 </div>;
}
