import { ResponsiveContainer,LineChart,Line,BarChart,Bar,PieChart,Pie,Cell,XAxis,YAxis,CartesianGrid,Tooltip,Legend } from 'recharts';
import { Table,TableCaption,TableHeader,TableBody,TableRow,TableHead,TableCell } from './table';
import { EmptyState } from './empty-state';
import { ErrorState } from './error-state';
export type ChartProps={label:string;data:Record<string,string|number>[];labelKey:string;series:{key:string;label:string;color?:string}[];kind?:'line'|'bar'|'donut';loading?:boolean;error?:string;onRetry?:()=>void};
const colors=['var(--g-action)','var(--g-soft)','var(--g-line)','var(--g-ink)'];
export function Chart({label,data,labelKey,series,kind='line',loading,error,onRetry}:ChartProps){if(loading)return <p role="status" aria-busy="true">차트 값을 불러오고 있어요.</p>;const invalid=data.some(row=>series.some(item=>typeof row[item.key]!=='number'||!Number.isFinite(row[item.key])));if(error||invalid)return <ErrorState title="차트를 표시하지 못했어요." message={error||'유효한 숫자 값을 전달해 주세요.'} onRetry={onRetry}/>;if(!data.length||!series.length)return <EmptyState heading="표시할 값이 없어요."/>;const tooltip=<Tooltip contentStyle={{background:'var(--g-surface)',color:'var(--g-ink)',border:'1px solid var(--g-line)',borderRadius:'var(--radius-g-control)'}}/>;const legend=<Legend/>;const axes=<><CartesianGrid stroke="var(--g-line)" vertical={false}/><XAxis dataKey={labelKey} tick={{fill:'var(--g-soft)'}}/><YAxis tick={{fill:'var(--g-soft)'}}/>{tooltip}{legend}</>;
 return <section aria-label={label} className="grid min-w-0 gap-4"><h3 className="font-medium">{label}</h3><div className="h-64 min-w-0"><ResponsiveContainer width="100%" height="100%" minWidth={0}>{kind==='donut'?<PieChart accessibilityLayer>{tooltip}{legend}<Pie data={data} dataKey={series[0].key} nameKey={labelKey} innerRadius="55%" outerRadius="80%" isAnimationActive={false}>{data.map((row,index)=><Cell key={String(row[labelKey])+'-'+index} fill={colors[index%colors.length]}/>)}</Pie></PieChart>:kind==='bar'?<BarChart data={data} accessibilityLayer>{axes}{series.map((item,index)=><Bar key={item.key} dataKey={item.key} name={item.label} fill={item.color??colors[index%colors.length]} isAnimationActive={false}/>)}</BarChart>:<LineChart data={data} accessibilityLayer>{axes}{series.map((item,index)=><Line key={item.key} type="monotone" dataKey={item.key} name={item.label} stroke={item.color??colors[index%colors.length]} isAnimationActive={false}/>)}</LineChart>}</ResponsiveContainer></div><details><summary className="min-h-11 cursor-pointer rounded-g-control px-3 py-2 text-g-small focus-visible:outline-3 focus-visible:outline-g-focus">실제 값을 표로 보기</summary><Table><TableCaption>{label+' 값'}</TableCaption><TableHeader><TableRow><TableHead>항목</TableHead>{series.map(item=><TableHead key={item.key} numeric>{item.label}</TableHead>)}</TableRow></TableHeader><TableBody>{data.map((row,index)=><TableRow key={String(row[labelKey])+'-'+index}><TableCell>{row[labelKey]}</TableCell>{series.map(item=><TableCell numeric key={item.key}>{row[item.key]}</TableCell>)}</TableRow>)}</TableBody></Table></details></section>;
}
