import { useRef,useState,type HTMLAttributes } from 'react';
import { DatePicker } from './date-picker';
import { CalendarGrid } from './calendar-grid';
import { CalendarControls } from './calendar-controls';
import { Button } from '../primitives/button';
import { Popover,PopoverTrigger,PopoverContent,PopoverTitle } from '../primitives/popover';
import { useFieldState } from '../lib/use-field-state';
import { dateAllowed,parseDate,todayString } from '../lib/date-utils';
import { cn } from '../lib/cn';
export type DateRangeValue={start:string;end:string};
export type DateRangePickerProps=Omit<HTMLAttributes<HTMLFieldSetElement>,'defaultValue'|'onChange'> & {label:string;value?:DateRangeValue;defaultValue?:DateRangeValue;onValueChange?:(value:DateRangeValue)=>void;min?:string;max?:string;disabledDates?:readonly string[];name?:string;form?:string;disabled?:boolean;readOnly?:boolean;required?:boolean;error?:string};
const empty:DateRangeValue={start:'',end:''};
export function DateRangePicker({label,value,defaultValue=empty,onValueChange,min,max,disabledDates=[],name,form,disabled,readOnly,required,error,className,...props}:DateRangePickerProps){const root=useRef<HTMLFieldSetElement>(null);const [current,change]=useFieldState(value,defaultValue,onValueChange,root,form);const [open,setOpen]=useState(false),[hover,setHover]=useState(''),[month,setMonth]=useState((parseDate(current.start)?current.start:todayString()).slice(0,7));const order=Boolean(parseDate(current.start)&&parseDate(current.end)&&current.start>current.end),blockedSpan=Boolean(parseDate(current.start)&&parseDate(current.end)&&disabledDates.some(day=>day>=current.start&&day<=current.end)),message=error||(order?'끝 날짜가 시작 날짜보다 앞서 있어요.':blockedSpan?'기간에 선택할 수 없는 날짜가 포함돼 있어요.':'');const pick=(day:string)=>{if(disabled||readOnly||!dateAllowed(day,min,max,disabledDates))return;if(!parseDate(current.start)||current.end||day<current.start)change({start:day,end:''});else{change({...current,end:day});setOpen(false);}setHover('');};const preview=current.end||((hover>=current.start&&dateAllowed(hover,min,max,disabledDates))?hover:'');
 return <fieldset {...props} ref={root} disabled={disabled} form={form} className={cn('grid min-w-0 gap-4 border-0 p-0',className)}><legend className="mb-3 font-medium">{label}</legend><DatePicker hideCalendar label="시작 날짜" name={name&&name+'.start'} form={form} value={current.start} onValueChange={start=>change({...current,start})} min={min} max={max} disabledDates={disabledDates} disabled={disabled} readOnly={readOnly} required={required}/><DatePicker hideCalendar label="끝 날짜" name={name&&name+'.end'} form={form} value={current.end} onValueChange={end=>change({...current,end})} min={min} max={max} disabledDates={disabledDates} disabled={disabled} readOnly={readOnly} required={required} error={message}/><div className="flex flex-wrap gap-2"><Popover open={open&&!disabled&&!readOnly} onOpenChange={next=>{if(next)setMonth((parseDate(current.start)?current.start:todayString()).slice(0,7));setHover('');setOpen(next);}}><PopoverTrigger asChild><Button variant="secondary" disabled={disabled||readOnly}>기간 선택</Button></PopoverTrigger><PopoverContent aria-label={label+' 기간 선택'} aria-describedby={undefined}><PopoverTitle>{label}</PopoverTitle><p className="text-g-small text-g-soft">{!current.start||current.end?'시작 날짜를 선택해 주세요.':'끝 날짜를 선택해 주세요.'}</p><CalendarControls month={month} onChange={setMonth} min={min} max={max}/><CalendarGrid month={month} onMonthChange={setMonth} value={current.end||current.start} onSelect={pick} min={min} max={max} disabledDates={disabledDates} range={{start:current.start,end:preview}} onHover={setHover} autoFocus/></PopoverContent></Popover><Button size="small" variant="quiet" disabled={disabled||readOnly||(!current.start&&!current.end)} onClick={()=>change(empty)}>기간 지우기</Button></div></fieldset>;
}
