import React,{useId,useState} from 'react';
import {Button} from './atoms';import {Alert,EmptyState} from './feedback';import {Progress,Skeleton} from './primitives';import {Icon,IconAction} from './icons';
export interface AccordionItem {id:string;title:string;content:React.ReactNode;disabled?:boolean}
export function Accordion({items,multiple=false}:{items:readonly AccordionItem[];multiple?:boolean}){const [open,setOpen]=useState<string[]>([]);const id=useId();return <div className="ds-accordion">{items.map(item=><section key={item.id}><h3><Button variant="ghost" disabled={item.disabled} aria-expanded={open.includes(item.id)} aria-controls={`${id}-${item.id}`} onClick={()=>setOpen(current=>current.includes(item.id)?current.filter(value=>value!==item.id):multiple?[...current,item.id]:[item.id])}>{item.title}<Icon name={open.includes(item.id)?'chevron-up':'chevron-down'}/></Button></h3><div role="region" aria-label={item.title} id={`${id}-${item.id}`} hidden={!open.includes(item.id)}>{item.content}</div></section>)}</div>;}
export function Collapse({title,children}:{title:string;children:React.ReactNode}){const [open,setOpen]=useState(false);const id=useId();return <section className="ds-collapse"><Button variant="secondary" aria-expanded={open} aria-controls={id} onClick={()=>setOpen(!open)}>{title}</Button><div id={id} hidden={!open}>{children}</div></section>;}
export function LoadingSpinner({label='불러오는 중'}:{label?:string}){return <span role="status" aria-label={label} className="ds-loading"><span className="spinner" aria-hidden="true"/>{label}</span>;}
export function ErrorState({message='불러오지 못했습니다',onRetry}:{message?:string;onRetry:()=>void}){return <Alert tone="error" title={message}><Button variant="secondary" onClick={onRetry}><Icon name="retry"/>다시 시도</Button></Alert>;}
export function Toast({message,onDismiss}:{message:string;onDismiss:()=>void}){return <div role="status" className="ds-toast"><Icon name="check"/><span>{message}</span><IconAction name="close" label="알림 닫기" variant="ghost" onClick={onDismiss}/></div>;}
export function FeedbackGallery(){const [state,setState]=useState<'ready'|'loading'|'empty'|'error'>('ready');const [toast,setToast]=useState(false);return <section aria-label="상태와 펼침"><h2>상태</h2><div className="ds-actions"><Button onClick={()=>setState('loading')}>불러오기</Button><Button variant="secondary" onClick={()=>setState('empty')}>빈 결과 보기</Button><Button variant="secondary" onClick={()=>setState('error')}>실패 보기</Button><Button variant="secondary" onClick={()=>{setState('ready');setToast(true);}}>알림 보기</Button></div>{state==='loading'?<><LoadingSpinner/><Skeleton/><Progress label="진행 중"/></>:state==='empty'?<EmptyState title="결과 없음" action="다시 불러오기" onAction={()=>setState('loading')}>검색 조건을 바꿔 보세요.</EmptyState>:state==='error'?<ErrorState onRetry={()=>setState('loading')}/>:<Alert tone="success" title="준비 완료">내용을 불러왔습니다.</Alert>}{toast&&<Toast message="작업이 완료되었습니다" onDismiss={()=>setToast(false)}/>}<h2>펼침</h2><Accordion items={[{id:'a',title:'단일 펼침 1',content:'첫 내용'},{id:'b',title:'단일 펼침 2',content:'둘째 내용'}]}/><Accordion multiple items={[{id:'a',title:'복수 펼침 1',content:'첫 내용'},{id:'b',title:'복수 펼침 2',content:'둘째 내용'}]}/><Collapse title="상세 펼치기">독립적으로 펼치는 내용</Collapse></section>;}
