import {afterEach,expect,test} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {createRef,useState,type CSSProperties} from 'react';
import {Input} from '../src/primitives/input';
import {Button} from '../src/primitives/button';
import {TextField} from '../src/components/text-field';
import {Select} from '../src/primitives/select';
afterEach(cleanup);
test('Input loading preserves node, value, focus and selection, native props/ref target input',()=>{
 const ref=createRef<HTMLInputElement>();const {rerender}=render(<Input ref={ref} name="field" aria-label="Field" defaultValue="가나다"/>);const input=screen.getByRole('textbox') as HTMLInputElement;input.focus();input.setSelectionRange(1,2);rerender(<Input loading ref={ref} name="field" aria-label="Field" defaultValue="가나다"/>);expect(ref.current).toBe(input);expect(input.value).toBe('가나다');expect(document.activeElement).toBe(input);expect([input.selectionStart,input.selectionEnd]).toEqual([1,2]);expect(input.getAttribute('aria-busy')).toBe('true');
});
test('Button type/native submit and loading guard',()=>{let submits=0;render(<form onSubmit={e=>{e.preventDefault();submits++;}}><Button>Ordinary</Button><Button type="submit">Submit</Button><Button type="submit" loading>Busy</Button></form>);fireEvent.click(screen.getByText('Ordinary'));expect(submits).toBe(0);fireEvent.click(screen.getByText('Submit'));expect(submits).toBe(1);fireEvent.click(screen.getByText('Busy'));expect(submits).toBe(1);});
test('controlled TextField clear and actual ref, uncontrolled reset restores default',async()=>{
 const ref=createRef<HTMLInputElement>();function Owner(){const [value,setValue]=useState('제어 값');return <form><TextField ref={ref} label="제어" value={value} onValueChange={setValue} clearable/><TextField label="비제어" defaultValue="처음" clearable/><Button type="reset">Reset</Button></form>;}
 render(<Owner/>);const controlled=screen.getByLabelText('제어');expect(ref.current).toBe(controlled);fireEvent.click(screen.getByRole('button',{name:'제어 지우기',exact:true}));expect((controlled as HTMLInputElement).value).toBe('');expect(document.activeElement).toBe(controlled);const uncontrolled=screen.getByLabelText('비제어') as HTMLInputElement;fireEvent.change(uncontrolled,{target:{value:'변경'}});expect(uncontrolled.value).toBe('변경');fireEvent.click(screen.getByText('Reset'));await waitFor(()=>expect(uncontrolled.value).toBe('처음'));expect(screen.getByLabelText('비제어')).toBe(uncontrolled);
});
test('Radix hidden select FormData/reset explicit controlled owner and ref type',async()=>{
 const ref=createRef<HTMLButtonElement>();function Owner(){const [value,setValue]=useState('first');const options=[{value:'first',label:'First'},{value:'second',label:'Second'}];return <form data-testid="form"><Select ref={ref} label="Controlled" name="controlled" required value={value} onValueChange={setValue} options={options}/><Select label="Uncontrolled" name="uncontrolled" defaultValue="first" options={options}/><Button onClick={()=>setValue('second')}>Owner second</Button><Button type="reset">Reset</Button></form>;}
 render(<Owner/>);const form=screen.getByTestId('form') as HTMLFormElement;expect(ref.current?.tagName).toBe('BUTTON');fireEvent.click(screen.getByText('Owner second'));await waitFor(()=>expect(new FormData(form).get('controlled')).toBe('second'));
 const hidden=form.querySelector('select[name="uncontrolled"]') as HTMLSelectElement;fireEvent.change(hidden,{target:{value:'second'}});await waitFor(()=>expect(new FormData(form).get('uncontrolled')).toBe('second'));
 fireEvent.click(screen.getByText('Reset'));await waitFor(()=>{expect(new FormData(form).get('uncontrolled')).toBe('first');expect(new FormData(form).get('controlled')).toBe('first');});
});

test('canceling native reset retains both controlled and uncontrolled fields',async()=>{
 function Owner(){const [value,setValue]=useState('second');return <form onReset={event=>event.preventDefault()}><Select label="Retained select" name="choice" value={value} onValueChange={setValue} options={[{value:'first',label:'First'},{value:'second',label:'Second'}]}/><TextField label="Retained input" defaultValue="original"/><Button type="reset">Cancel reset</Button></form>;}
 render(<Owner/>);const input=screen.getByLabelText('Retained input') as HTMLInputElement;fireEvent.change(input,{target:{value:'edited'}});fireEvent.click(screen.getByText('Cancel reset'));await new Promise(resolve=>queueMicrotask(resolve));expect(input.value).toBe('edited');expect(screen.getByRole('combobox',{name:'Retained select'}).textContent).toContain('Second');
});
import userEvent from '@testing-library/user-event';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '../src/primitives/tabs';
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription,DialogClose} from '../src/primitives/dialog';
import {Theme,type ThemeMode} from '../src/foundation/theme';
test('theme default/palette and semantic values propagate through nested open portals without remounting Input',async()=>{
 class Observer {observe(){} unobserve(){} disconnect(){}}
 const prior=globalThis.ResizeObserver;globalThis.ResizeObserver=Observer as unknown as typeof ResizeObserver;
 const scroll=HTMLElement.prototype.scrollIntoView;HTMLElement.prototype.scrollIntoView=()=>{};
 const user=userEvent.setup();const ref=createRef<HTMLInputElement>();
 function Owner({palette,mode,values}:{palette?:string;mode?:ThemeMode;values?:Record<`--${string}`,string>}){return <Theme palette={palette} mode={mode} values={values}><Theme><Dialog><DialogTrigger asChild><Button>Palette open</Button></DialogTrigger><DialogContent><DialogTitle>Palette title</DialogTitle><DialogDescription>Palette description</DialogDescription><Input ref={ref} aria-label="Palette input" defaultValue="owner value"/><Select label="Palette select" defaultValue="first" options={[{value:'first',label:'Palette first'},{value:'second',label:'Palette second'}]}/></DialogContent></Dialog></Theme></Theme>;}
 try{const {rerender}=render(<Owner/>);expect(document.querySelector('[data-gyeol]')?.getAttribute('data-palette')).toBe('Indigo');await user.click(screen.getByText('Palette open'));const input=screen.getByLabelText('Palette input') as HTMLInputElement;input.setSelectionRange(1,3);expect(ref.current).toBe(input);const trigger=screen.getByRole('combobox',{name:'Palette select'});trigger.focus();await user.keyboard('{ArrowDown}');const list=await screen.findByRole('listbox');const dialog=screen.getByRole('dialog');expect(dialog.contains(list)).toBe(true);rerender(<Owner mode="dark" palette="Ocean" values={{'--g-surface':'#123456','--g-ink':'#fedcba'}}/>);expect(screen.getByLabelText('Palette input')).toBe(input);expect(input.value).toBe('owner value');expect(ref.current).toBe(input);expect(list.getAttribute('data-theme')).toBe('dark');expect(dialog.getAttribute('data-palette')).toBe('Ocean');expect(list.getAttribute('data-palette')).toBe('Ocean');expect(dialog.style.getPropertyValue('--g-surface')).toBe('#123456');expect(list.style.getPropertyValue('--g-ink')).toBe('#fedcba');expect(dialog.contains(document.activeElement)).toBe(true);}
 finally{globalThis.ResizeObserver=prior;HTMLElement.prototype.scrollIntoView=scroll;}
});
test('Radix manual Tabs uses keyboard focus and skips disabled trigger',async()=>{
 const user=userEvent.setup();render(<Tabs defaultValue="one" activationMode="manual"><TabsList><TabsTrigger value="one">One</TabsTrigger><TabsTrigger value="two">Two</TabsTrigger><TabsTrigger value="disabled" disabled>Disabled</TabsTrigger></TabsList><TabsContent value="one">First panel</TabsContent><TabsContent value="two">Second panel</TabsContent></Tabs>);screen.getByRole('tab',{name:'One'}).focus();await user.keyboard('{ArrowRight}');expect(document.activeElement).toBe(screen.getByRole('tab',{name:'Two'}));expect(screen.getByRole('tab',{name:'Two'}).getAttribute('aria-selected')).toBe('false');await user.keyboard('{Enter}');expect(screen.getByRole('tab',{name:'Two'}).getAttribute('aria-selected')).toBe('true');await user.keyboard('{ArrowRight}');expect(document.activeElement).toBe(screen.getByRole('tab',{name:'One'}));
});
test('Radix Dialog focus trap/return and installed themed Select portal update',async()=>{
 // JSDOM omits layout observation/scroll; this test proves behavior and attributes only.
 class Observer { observe(){} unobserve(){} disconnect(){} }
 const prior=globalThis.ResizeObserver;globalThis.ResizeObserver=Observer as unknown as typeof ResizeObserver;
 const scroll=HTMLElement.prototype.scrollIntoView;HTMLElement.prototype.scrollIntoView=()=>{};
 const user=userEvent.setup();function Owner({mode}:{mode:ThemeMode}){return <Theme mode={mode}><Dialog><DialogTrigger asChild><Button>Open</Button></DialogTrigger><DialogContent><DialogTitle>Title</DialogTitle><DialogDescription>Description</DialogDescription><Input aria-label="Dialog input"/><Select label="Dialog select" defaultValue="first" name="choice" options={[{value:'first',label:'First choice'},{value:'second',label:'Second choice'}]}/><DialogClose asChild><Button>Close</Button></DialogClose></DialogContent></Dialog></Theme>;}
 const {rerender}=render(<Owner mode="light"/>);await user.click(screen.getByText('Open'));const content=screen.getByRole('dialog');expect(content.contains(document.activeElement)).toBe(true);for(let i=0;i<6;i++){await user.keyboard('{Tab}');expect(content.contains(document.activeElement)).toBe(true);}const trigger=screen.getByRole('combobox',{name:'Dialog select'});trigger.focus();await user.keyboard('{ArrowDown}');const list=await screen.findByRole('listbox');expect(content.contains(list)).toBe(true);expect(list.getAttribute('data-theme')).toBe('light');rerender(<Owner mode="dark"/>);expect(screen.getByRole('dialog').getAttribute('data-theme')).toBe('dark');expect(screen.getByRole('listbox').getAttribute('data-theme')).toBe('dark');expect(list.closest('[aria-hidden="true"]')).toBe(null);await user.keyboard('{ArrowDown}{Enter}');expect(trigger.textContent).toContain('Second choice');await user.keyboard('{Escape}');await waitFor(()=>expect(screen.queryByRole('dialog')).toBe(null));expect(document.activeElement).toBe(screen.getByText('Open'));
 globalThis.ResizeObserver=prior;HTMLElement.prototype.scrollIntoView=scroll;
});
import {TaskExample} from '../../../apps/docs/src/task-example';
test('real task example search/empty/create/edit/cancel/error/loading flows',async()=>{
 const user=userEvent.setup();render(<TaskExample/>);const search=screen.getByRole('textbox',{name:'작업 검색'});await user.type(search,'찾을 수 없음');expect(screen.getByText('해당하는 작업이 없어요.')).toBeTruthy();await user.click(screen.getByRole('button',{name:'작업 검색 지우기'}));expect((search as HTMLInputElement).value).toBe('');expect(document.activeElement).toBe(search);
 await user.click(screen.getByRole('button',{name:'새 작업',exact:true}));const input=screen.getByRole('textbox',{name:'작업 이름'}) as HTMLInputElement;expect(document.activeElement).toBe(input);await user.click(screen.getByRole('button',{name:'저장',exact:true}));expect(screen.getByRole('alert').textContent).toContain('작업 이름을 입력해 주세요.');await user.type(input,'실제로 생성한 작업');await user.click(screen.getByRole('button',{name:'저장',exact:true}));expect(screen.getByRole('textbox',{name:'작업 이름'})).toBe(input);expect(input.value).toBe('실제로 생성한 작업');expect(input.getAttribute('aria-busy')).toBe('true');await waitFor(()=>expect(screen.queryByRole('dialog')).toBe(null));expect(screen.getByText('실제로 생성한 작업')).toBeTruthy();expect(document.activeElement?.textContent).toContain('새 작업');
 await user.click(screen.getByRole('button',{name:'실제로 생성한 작업 편집'}));await user.clear(screen.getByRole('textbox',{name:'작업 이름'}));await user.type(screen.getByRole('textbox',{name:'작업 이름'}),'실제로 편집한 작업');await user.click(screen.getByRole('button',{name:'저장',exact:true}));await waitFor(()=>expect(screen.queryByRole('dialog')).toBe(null));expect(screen.getByText('실제로 편집한 작업')).toBeTruthy();await user.click(screen.getByRole('button',{name:'실제로 편집한 작업 편집'}));await user.clear(screen.getByRole('textbox',{name:'작업 이름'}));await user.type(screen.getByRole('textbox',{name:'작업 이름'}),'취소할 작업');await user.click(screen.getByRole('button',{name:'취소',exact:true}));expect(screen.getByText('실제로 편집한 작업')).toBeTruthy();expect(screen.queryByText('취소할 작업')).toBe(null);
 await user.click(screen.getByRole('button',{name:'새로 고침',exact:true}));expect(screen.getByRole('status').textContent).toContain('불러오는 중');await waitFor(()=>expect(screen.getByText('실제로 편집한 작업')).toBeTruthy());
});
import DocsApp from '../../../apps/docs/src/App';
test('docs live/current Code/reset share state across panels and menu search',async()=>{
 const user=userEvent.setup();render(<DocsApp/>);await user.click(screen.getByRole('button',{name:'Input',exact:true}));const input=screen.getByRole('textbox',{name:'입력 예제'}) as HTMLInputElement;await user.clear(input);await user.type(input,'패널 이동에도 유지');await user.click(screen.getByRole('tab',{name:'Code',exact:true}));expect(input.value).toBe('패널 이동에도 유지');expect(screen.getByRole('tabpanel').textContent).toContain('패널 이동에도 유지');await user.click(screen.getByRole('tab',{name:'Docs',exact:true}));expect(screen.getByRole('textbox',{name:'입력 예제'})).toBe(input);expect(input.value).toBe('패널 이동에도 유지');await user.click(screen.getByRole('button',{name:'Reset',exact:true}));expect(input.value).toBe('읽고, 정리하고, 이어 가기');await user.type(screen.getByRole('textbox',{name:'문서 검색'}),'select');expect(screen.getByRole('button',{name:'Select',exact:true})).toBeTruthy();expect(screen.queryByRole('button',{name:'Button',exact:true})).toBe(null);
});

test('first Select open and reopen transport current scope without an owner rerender',async()=>{
 // JSDOM validates applied custom properties/refs, not computed browser colors.
 class Observer {observe(){} unobserve(){} disconnect(){}}
 const previous=globalThis.ResizeObserver,scroll=HTMLElement.prototype.scrollIntoView;
 globalThis.ResizeObserver=Observer as unknown as typeof ResizeObserver;HTMLElement.prototype.scrollIntoView=()=>{};
 const user=userEvent.setup(),inputRef=createRef<HTMLInputElement>(),triggerRef=createRef<HTMLButtonElement>();
 try{render(<Theme values={{'--g-surface':'#123456','--g-action':'#654321','--g-danger':'rebeccapurple'}}><Input ref={inputRef} aria-label="Mount input" defaultValue="owner value"/><Select ref={triggerRef} label="Mount select" defaultValue="first" options={[{value:'first',label:'Mount first'},{value:'second',label:'Mount second'}]}/></Theme>);
 const input=screen.getByLabelText('Mount input') as HTMLInputElement,trigger=screen.getByRole('combobox',{name:'Mount select'});
 await user.click(input);await user.keyboard('{Home}{Shift>}{ArrowRight}{ArrowRight}{/Shift}');const selection=[input.selectionStart,input.selectionEnd];await user.tab();expect(document.activeElement).toBe(trigger);
 for(let opening=0;opening<2;opening++){await user.keyboard('{ArrowDown}');const list=await screen.findByRole('listbox');console.info('CORE08_FIRST_PORTAL',JSON.stringify({opening,surface:list.style.getPropertyValue('--g-surface'),action:list.style.getPropertyValue('--g-action'),danger:list.style.getPropertyValue('--g-danger'),inputValue:input.value,sameInput:inputRef.current===input,selection:[input.selectionStart,input.selectionEnd],refIsTrigger:triggerRef.current===trigger,theme:list.getAttribute('data-theme')}));expect(list.style.getPropertyValue('--g-surface')).toBe('#123456');expect(list.style.getPropertyValue('--g-action')).toBe('#654321');expect(list.style.getPropertyValue('--g-danger')).toBe('rebeccapurple');expect(triggerRef.current).toBe(trigger);expect(inputRef.current).toBe(input);expect(input.value).toBe('owner value');expect([input.selectionStart,input.selectionEnd]).toEqual(selection);await user.keyboard('{Escape}');await waitFor(()=>expect(screen.queryByRole('listbox')).toBe(null));expect(document.activeElement).toBe(trigger);}
 }finally{globalThis.ResizeObserver=previous;HTMLElement.prototype.scrollIntoView=scroll;}
});
test('first nested Dialog Select mount keeps explicit scope and actual native content ref/style',async()=>{
 class Observer {observe(){} unobserve(){} disconnect(){}}
 const previous=globalThis.ResizeObserver,scroll=HTMLElement.prototype.scrollIntoView;
 globalThis.ResizeObserver=Observer as unknown as typeof ResizeObserver;HTMLElement.prototype.scrollIntoView=()=>{};
 const user=userEvent.setup(),contentRef=createRef<HTMLDivElement>(),inputRef=createRef<HTMLInputElement>();
 const nativeStyle={'--owner-note':'owner','fontStyle':'italic'} as CSSProperties;
 try{render(<Theme values={{'--g-surface':'#123456','--g-action':'#654321','--g-danger':'rebeccapurple'}}><Theme><Dialog><DialogTrigger asChild><Button>First nested open</Button></DialogTrigger><DialogContent ref={contentRef} style={nativeStyle} data-owner="kept"><DialogTitle>First nested title</DialogTitle><DialogDescription>First nested description</DialogDescription><Input ref={inputRef} aria-label="Nested mount input" defaultValue="nested value"/><Select label="Nested mount select" defaultValue="first" options={[{value:'first',label:'Nested mount first'},{value:'second',label:'Nested mount second'}]}/></DialogContent></Dialog></Theme></Theme>);
 await user.click(screen.getByText('First nested open'));const dialog=screen.getByRole('dialog'),input=screen.getByLabelText('Nested mount input') as HTMLInputElement;expect(contentRef.current).toBe(dialog);expect(dialog.getAttribute('data-owner')).toBe('kept');expect(dialog.style.fontStyle).toBe('italic');expect(dialog.style.getPropertyValue('--owner-note')).toBe('owner');expect(dialog.style.getPropertyValue('--g-surface')).toBe('#123456');expect(document.activeElement).toBe(input);await user.keyboard('{Home}{Shift>}{ArrowRight}{ArrowRight}{/Shift}');const selection=[input.selectionStart,input.selectionEnd];await user.tab();const trigger=screen.getByRole('combobox',{name:'Nested mount select'});expect(document.activeElement).toBe(trigger);
 for(let opening=0;opening<2;opening++){await user.keyboard('{ArrowDown}');const list=await screen.findByRole('listbox');console.info('CORE08_NESTED_PORTAL',JSON.stringify({opening,inDialog:dialog.contains(list),surface:list.style.getPropertyValue('--g-surface'),action:list.style.getPropertyValue('--g-action'),danger:list.style.getPropertyValue('--g-danger'),sameInput:inputRef.current===input,value:input.value,selection:[input.selectionStart,input.selectionEnd],nativeRef:contentRef.current===dialog,nativeFontStyle:dialog.style.fontStyle,nativeCustom:dialog.style.getPropertyValue('--owner-note')}));expect(dialog.contains(list)).toBe(true);for(const [name,value]of Object.entries({'--g-surface':'#123456','--g-action':'#654321','--g-danger':'rebeccapurple'}))expect(list.style.getPropertyValue(name)).toBe(value);expect(inputRef.current).toBe(input);expect(input.value).toBe('nested value');expect([input.selectionStart,input.selectionEnd]).toEqual(selection);await user.keyboard('{Escape}');await waitFor(()=>expect(screen.queryByRole('listbox')).toBe(null));expect(document.activeElement).toBe(trigger);}
 await user.keyboard('{Escape}');await waitFor(()=>expect(screen.queryByRole('dialog')).toBe(null));expect(contentRef.current).toBe(null);expect(document.activeElement).toBe(screen.getByText('First nested open'));
 }finally{globalThis.ResizeObserver=previous;HTMLElement.prototype.scrollIntoView=scroll;}
});
test.each([true,false])('open portal cleans removed scope/native variables with changing callback ref=%s',async changing=>{
 const user=userEvent.setup(),inputRef=createRef<HTMLInputElement>(),calls:(HTMLDivElement|null)[]=[],callbackIdentities:unknown[]=[],stableRef=(node:HTMLDivElement|null)=>{calls.push(node);};
 function Owner({values,style}:{values:Record<`--${string}`,string>;style:CSSProperties}){const callback=(node:HTMLDivElement|null)=>{calls.push(node);console.info('CORE08_REF_CALLBACK',JSON.stringify({changing,scopeNote:values['--owner-note']??null,isNull:node===null}));};callbackIdentities.push(callback);return <Theme values={values}><Dialog><DialogTrigger asChild><Button>Cleanup open</Button></DialogTrigger><DialogContent ref={changing?callback:stableRef} style={style}><DialogTitle>Cleanup title</DialogTitle><DialogDescription>Cleanup description</DialogDescription><Input ref={inputRef} aria-label="Cleanup input" defaultValue="kept value"/></DialogContent></Dialog></Theme>;}
 const native={'--caller-note':'keep',fontStyle:'italic'} as CSSProperties;const {rerender}=render(<Owner values={{'--owner-note':'parent','--g-surface':'#123456'}} style={native}/>);await user.click(screen.getByText('Cleanup open'));const content=screen.getByRole('dialog'),input=screen.getByLabelText('Cleanup input') as HTMLInputElement;expect(content.style.getPropertyValue('--owner-note')).toBe('parent');expect(document.activeElement).toBe(input);await user.keyboard('{Home}{Shift>}{ArrowRight}{ArrowRight}{/Shift}');const selection=[input.selectionStart,input.selectionEnd];const priorCalls=calls.length;console.info('CORE08_REF_BEFORE',JSON.stringify({changing,priorCalls,initialOwnerNote:content.style.getPropertyValue('--owner-note')}));
 rerender(<Owner values={{'--g-surface':'#654321'}} style={native}/>);console.info('CORE08_REF_AFTER',JSON.stringify({changing,totalCalls:calls.length,ownerNote:content.style.getPropertyValue('--owner-note'),differentCallbacks:callbackIdentities[0]!==callbackIdentities.at(-1)}));await waitFor(()=>expect(content.style.getPropertyValue('--owner-note')).toBe(''));expect(screen.getByRole('dialog')).toBe(content);expect(content.style.getPropertyValue('--g-surface')).toBe('#654321');expect(content.style.getPropertyValue('--caller-note')).toBe('keep');expect(content.style.fontStyle).toBe('italic');expect(inputRef.current).toBe(input);expect(input.value).toBe('kept value');expect([input.selectionStart,input.selectionEnd]).toEqual(selection);expect(document.activeElement).toBe(input);if(changing){expect(calls.slice(priorCalls)).toContain(null);expect(calls.at(-1)).toBe(content);}
 rerender(<Owner values={{'--owner-note':'parent-again','--g-surface':'#654321'}} style={{...native,'--owner-note':'caller','--g-surface':'#abcdef'} as CSSProperties}/>);expect(content.style.getPropertyValue('--owner-note')).toBe('caller');expect(content.style.getPropertyValue('--g-surface')).toBe('#abcdef');
 rerender(<Owner values={{'--owner-note':'parent-final','--g-surface':'#654321'}} style={native}/>);await waitFor(()=>expect(content.style.getPropertyValue('--owner-note')).toBe('parent-final'));expect(content.style.getPropertyValue('--g-surface')).toBe('#654321');
 rerender(<Owner values={{'--g-surface':'#654321'}} style={{fontStyle:'italic'}}/>);await waitFor(()=>expect(content.style.getPropertyValue('--owner-note')).toBe(''));expect(content.style.getPropertyValue('--caller-note')).toBe('');expect(content.style.fontStyle).toBe('italic');expect(screen.getByLabelText('Cleanup input')).toBe(input);expect([input.selectionStart,input.selectionEnd]).toEqual(selection);expect(document.activeElement).toBe(input);
 console.info('CORE08_REF_CLEANUP',JSON.stringify({changing,sameContent:screen.getByRole('dialog')===content,ownerNote:content.style.getPropertyValue('--owner-note'),callerNote:content.style.getPropertyValue('--caller-note'),surface:content.style.getPropertyValue('--g-surface'),nativeFontStyle:content.style.fontStyle,sameInput:inputRef.current===input,value:input.value,selection,focusedInput:document.activeElement===input,refNullCalls:calls.filter(node=>node===null).length}));
 await user.keyboard('{Escape}');await waitFor(()=>expect(screen.queryByRole('dialog')).toBe(null));expect(calls.at(-1)).toBe(null);await user.click(screen.getByText('Cleanup open'));const reopened=screen.getByRole('dialog');expect(reopened).not.toBe(content);expect(reopened.style.getPropertyValue('--owner-note')).toBe('');expect(reopened.style.getPropertyValue('--caller-note')).toBe('');expect(reopened.style.getPropertyValue('--g-surface')).toBe('#654321');expect(calls.at(-1)).toBe(reopened);
});


const buttonCases = [
 ['primary','small','bg-g-action','px-3','text-g-small'],
 ['primary','medium','bg-g-action','px-g-control','text-g-body'],
 ['secondary','small','bg-g-surface','px-3','text-g-small'],
 ['secondary','medium','bg-g-surface','px-g-control','text-g-body'],
 ['quiet','small','bg-transparent','px-3','text-g-small'],
 ['quiet','medium','bg-transparent','px-g-control','text-g-body'],
] as const;
test.each(buttonCases)('Button public variant=%s size=%s retains native target and label', (variant,size,color,padding,text) => {
 const ref=createRef<HTMLButtonElement>();render(<Button ref={ref} variant={variant} size={size} id="owner-button" name="action" value="save" title="Owner title" aria-label="Owner button" data-owner="retained"><span>저장하기</span></Button>);
 const button=screen.getByRole('button',{name:'Owner button'}) as HTMLButtonElement;expect(button).toBeInstanceOf(HTMLButtonElement);expect(ref.current).toBe(button);expect(button.type).toBe('button');expect(button.id).toBe('owner-button');expect(button.name).toBe('action');expect(button.value).toBe('save');expect(button.title).toBe('Owner title');expect(button.getAttribute('data-owner')).toBe('retained');expect(button.textContent).toBe('저장하기');expect(button.disabled).toBe(false);expect(button.hasAttribute('aria-busy')).toBe(false);for(const token of ['min-h-11',color,padding,text])expect(button.classList.contains(token)).toBe(true);
});
test('Button defaults are primary medium and its ref detaches from the actual native button',()=>{
 const ref=createRef<HTMLButtonElement>();const {unmount}=render(<Button ref={ref}>기본값</Button>);const button=screen.getByRole('button',{name:'기본값'}) as HTMLButtonElement;expect(ref.current).toBe(button);expect(button.type).toBe('button');for(const token of ['bg-g-action','px-g-control','text-g-body'])expect(button.classList.contains(token)).toBe(true);unmount();expect(ref.current).toBe(null);
});
test('Button default type does not submit while explicit submit/reset keep native form events',async()=>{
 let submits=0,resets=0,clickTarget:HTMLButtonElement|null=null;const user=userEvent.setup();render(<form onSubmit={event=>{event.preventDefault();submits++;}} onReset={()=>{resets++;}}><input aria-label="Button form input" defaultValue="seed"/><Button onClick={event=>{clickTarget=event.currentTarget;}}>Default action</Button><Button type="submit">Submit action</Button><Button type="reset">Reset action</Button></form>);const input=screen.getByRole('textbox',{name:'Button form input'}) as HTMLInputElement;await user.clear(input);await user.type(input,'edited');await user.click(screen.getByRole('button',{name:'Default action'}));expect(clickTarget).toBe(screen.getByRole('button',{name:'Default action'}));expect(submits).toBe(0);expect(resets).toBe(0);await user.click(screen.getByRole('button',{name:'Submit action'}));expect(submits).toBe(1);expect(input.value).toBe('edited');await user.click(screen.getByRole('button',{name:'Reset action'}));expect(resets).toBe(1);expect(input.value).toBe('seed');
});
test.each([[false,false],[false,true],[true,false],[true,true]] as const)('Button loading=%s disabled=%s busy/removal and duplicate actions use native behavior',async(loading,disabled)=>{
 let actions=0;const user=userEvent.setup(),ref=createRef<HTMLButtonElement>();const owner=(busy:boolean,blocked:boolean)=><Button ref={ref} loading={busy} disabled={blocked} aria-label="Owner action" onClick={()=>actions++}><span data-testid="owner-label">그대로인 이름</span></Button>;const {rerender}=render(owner(loading,disabled));const button=screen.getByRole('button',{name:'Owner action'}) as HTMLButtonElement,label=screen.getByTestId('owner-label');expect(button.disabled).toBe(loading||disabled);expect(button.getAttribute('aria-busy')).toBe(loading?'true':null);expect(label.textContent).toBe('그대로인 이름');expect(button.querySelector('[aria-hidden="true"]')?.textContent??null).toBe(loading?'…':null);await user.dblClick(button);expect(actions).toBe(loading||disabled?0:2);
 const before=actions;rerender(owner(true,disabled));expect(ref.current).toBe(button);expect(screen.getByTestId('owner-label')).toBe(label);await user.dblClick(button);await user.keyboard('{Enter} ');expect(actions).toBe(before);expect(button.disabled).toBe(true);expect(button.getAttribute('aria-busy')).toBe('true');rerender(owner(false,disabled));expect(ref.current).toBe(button);expect(button.disabled).toBe(disabled);expect(button.hasAttribute('aria-busy')).toBe(false);expect(button.querySelector('[aria-hidden="true"]')).toBe(null);await user.click(button);expect(actions).toBe(before+(disabled?0:1));rerender(owner(false,false));expect(ref.current).toBe(button);expect(screen.getByTestId('owner-label')).toBe(label);expect(button.disabled).toBe(false);await user.click(button);expect(actions).toBe(before+(disabled?1:2));
});
test('Button className is last in semantic/native utility merging on the actual element',()=>{
 render(<Button size="small" className="px-8 rounded-none text-xl bg-red-500" data-testid="last-classes">Owner</Button>);const button=screen.getByTestId('last-classes');for(const token of ['px-8','rounded-none','text-xl','bg-red-500'])expect(button.classList.contains(token)).toBe(true);for(const token of ['px-3','rounded-g-control','text-g-small','bg-g-action'])expect(button.classList.contains(token)).toBe(false);
});
