import {afterEach,expect,test} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {createRef,useState} from 'react';
import {Input} from '../src/primitives/input';
import {Button} from '../src/primitives/button';
import {TextField} from '../src/components/text-field';
import {Select} from '../src/primitives/select';
afterEach(cleanup);
test('Input loading preserves node, value, focus and selection, native props/ref target input',()=>{
 const ref=createRef<HTMLInputElement>();const {rerender}=render(<Input ref={ref} name="field" aria-label="Field" defaultValue="가나다"/>);const input=screen.getByRole('textbox') as HTMLInputElement;input.focus();input.setSelectionRange(1,2);rerender(<Input loading ref={ref} name="field" aria-label="Field" defaultValue="가나다"/>);expect(ref.current).toBe(input);expect(input.value).toBe('가나다');expect(document.activeElement).toBe(input);expect([input.selectionStart,input.selectionEnd]).toEqual([1,2]);expect(input.getAttribute('aria-busy')).toBe('true');
});
test('Button type/native submit and loading guard',()=>{let submits=0;render(<form onSubmit={e=>{e.preventDefault();submits++;}}><Button>Ordinary</Button><Button type="submit">Submit</Button><Button type="submit" loading>Busy</Button></form>);fireEvent.click(screen.getByText('Ordinary'));expect(submits).toBe(0);fireEvent.click(screen.getByText('Submit'));expect(submits).toBe(1);fireEvent.click(screen.getByText('Busy'));expect(submits).toBe(1);});
test('controlled TextField clear and actual ref, uncontrolled reset restores default',async()=>{
 const ref=createRef<HTMLInputElement>();function Owner(){const [value,setValue]=useState('제어 값');return <form><TextField ref={ref} label="제어" value={value} onValueChange={setValue} clearable/><TextField label="비제어" defaultValue="처음" clearable/><Button type="reset">Reset</Button></form>;}
 render(<Owner/>);const controlled=screen.getByLabelText('제어');expect(ref.current).toBe(controlled);fireEvent.click(screen.getByRole('button',{name:'제어 지우기',exact:true}));expect((controlled as HTMLInputElement).value).toBe('');expect(document.activeElement).toBe(controlled);const uncontrolled=screen.getByLabelText('비제어') as HTMLInputElement;fireEvent.change(uncontrolled,{target:{value:'변경'}});expect(uncontrolled.value).toBe('변경');fireEvent.click(screen.getByText('Reset'));await waitFor(()=>expect(uncontrolled.value).toBe('처음'));expect(screen.getByLabelText('비제어')).toBe(uncontrolled);
});
test('Radix hidden select FormData/reset explicit controlled owner and ref type',async()=>{
 const ref=createRef<HTMLButtonElement>();function Owner(){const [value,setValue]=useState('first');const options=[{value:'first',label:'First'},{value:'second',label:'Second'}];return <form data-testid="form"><Select ref={ref} label="Controlled" name="controlled" required value={value} onValueChange={setValue} options={options}/><Select label="Uncontrolled" name="uncontrolled" defaultValue="first" options={options}/><Button onClick={()=>setValue('second')}>Owner second</Button><Button type="reset">Reset</Button></form>;}
 render(<Owner/>);const form=screen.getByTestId('form') as HTMLFormElement;expect(ref.current?.tagName).toBe('BUTTON');fireEvent.click(screen.getByText('Owner second'));await waitFor(()=>expect(new FormData(form).get('controlled')).toBe('second'));
 const hidden=form.querySelector('select[name="uncontrolled"]') as HTMLSelectElement;fireEvent.change(hidden,{target:{value:'second'}});await waitFor(()=>expect(new FormData(form).get('uncontrolled')).toBe('second'));
 fireEvent.click(screen.getByText('Reset'));await waitFor(()=>{expect(new FormData(form).get('uncontrolled')).toBe('first');expect(new FormData(form).get('controlled')).toBe('first');});
});

test('canceling native reset retains both controlled and uncontrolled fields',async()=>{
 function Owner(){const [value,setValue]=useState('second');return <form onReset={event=>event.preventDefault()}><Select label="Retained select" name="choice" value={value} onValueChange={setValue} options={[{value:'first',label:'First'},{value:'second',label:'Second'}]}/><TextField label="Retained input" defaultValue="original"/><Button type="reset">Cancel reset</Button></form>;}
 render(<Owner/>);const input=screen.getByLabelText('Retained input') as HTMLInputElement;fireEvent.change(input,{target:{value:'edited'}});fireEvent.click(screen.getByText('Cancel reset'));await new Promise(resolve=>queueMicrotask(resolve));expect(input.value).toBe('edited');expect(screen.getByRole('combobox',{name:'Retained select'}).textContent).toContain('Second');
});
import userEvent from '@testing-library/user-event';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '../src/primitives/tabs';
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription,DialogClose} from '../src/primitives/dialog';
import {Theme,type ThemeMode} from '../src/foundation/theme';
test('Radix manual Tabs uses keyboard focus and skips disabled trigger',async()=>{
 const user=userEvent.setup();render(<Tabs defaultValue="one" activationMode="manual"><TabsList><TabsTrigger value="one">One</TabsTrigger><TabsTrigger value="two">Two</TabsTrigger><TabsTrigger value="disabled" disabled>Disabled</TabsTrigger></TabsList><TabsContent value="one">First panel</TabsContent><TabsContent value="two">Second panel</TabsContent></Tabs>);screen.getByRole('tab',{name:'One'}).focus();await user.keyboard('{ArrowRight}');expect(document.activeElement).toBe(screen.getByRole('tab',{name:'Two'}));expect(screen.getByRole('tab',{name:'Two'}).getAttribute('aria-selected')).toBe('false');await user.keyboard('{Enter}');expect(screen.getByRole('tab',{name:'Two'}).getAttribute('aria-selected')).toBe('true');await user.keyboard('{ArrowRight}');expect(document.activeElement).toBe(screen.getByRole('tab',{name:'One'}));
});
test('Radix Dialog focus trap/return and installed themed Select portal update',async()=>{
 // JSDOM omits layout observation/scroll; this test proves behavior and attributes only.
 class Observer { observe(){} unobserve(){} disconnect(){} }
 const prior=globalThis.ResizeObserver;globalThis.ResizeObserver=Observer as unknown as typeof ResizeObserver;
 const scroll=HTMLElement.prototype.scrollIntoView;HTMLElement.prototype.scrollIntoView=()=>{};
 const user=userEvent.setup();function Owner({mode}:{mode:ThemeMode}){return <Theme mode={mode}><Dialog><DialogTrigger asChild><Button>Open</Button></DialogTrigger><DialogContent><DialogTitle>Title</DialogTitle><DialogDescription>Description</DialogDescription><Input aria-label="Dialog input"/><Select label="Dialog select" defaultValue="first" name="choice" options={[{value:'first',label:'First choice'},{value:'second',label:'Second choice'}]}/><DialogClose asChild><Button>Close</Button></DialogClose></DialogContent></Dialog></Theme>;}
 const {rerender}=render(<Owner mode="light"/>);await user.click(screen.getByText('Open'));const content=screen.getByRole('dialog');expect(content.contains(document.activeElement)).toBe(true);for(let i=0;i<6;i++){await user.keyboard('{Tab}');expect(content.contains(document.activeElement)).toBe(true);}const trigger=screen.getByRole('combobox',{name:'Dialog select'});trigger.focus();await user.keyboard('{ArrowDown}');const list=await screen.findByRole('listbox');expect(content.contains(list)).toBe(true);expect(list.getAttribute('data-theme')).toBe('light');rerender(<Owner mode="dark"/>);expect(screen.getByRole('dialog').getAttribute('data-theme')).toBe('dark');expect(screen.getByRole('listbox').getAttribute('data-theme')).toBe('dark');expect(list.closest('[aria-hidden="true"]')).toBe(null);await user.keyboard('{ArrowDown}{Enter}');expect(trigger.textContent).toContain('Second choice');await user.keyboard('{Escape}');await waitFor(()=>expect(screen.queryByRole('dialog')).toBe(null));expect(document.activeElement).toBe(screen.getByText('Open'));
 globalThis.ResizeObserver=prior;HTMLElement.prototype.scrollIntoView=scroll;
});
import {TaskExample} from '../../../apps/docs/src/task-example';
test('real task example search/empty/create/edit/cancel/error/loading flows',async()=>{
 const user=userEvent.setup();render(<TaskExample/>);const search=screen.getByRole('textbox',{name:'작업 검색'});await user.type(search,'찾을 수 없음');expect(screen.getByText('해당하는 작업이 없어요.')).toBeTruthy();await user.click(screen.getByRole('button',{name:'작업 검색 지우기'}));expect((search as HTMLInputElement).value).toBe('');expect(document.activeElement).toBe(search);
 await user.click(screen.getByRole('button',{name:'새 작업',exact:true}));const input=screen.getByRole('textbox',{name:'작업 이름'}) as HTMLInputElement;expect(document.activeElement).toBe(input);await user.click(screen.getByRole('button',{name:'저장',exact:true}));expect(screen.getByRole('alert').textContent).toContain('작업 이름을 입력해 주세요.');await user.type(input,'실제로 생성한 작업');await user.click(screen.getByRole('button',{name:'저장',exact:true}));expect(screen.getByRole('textbox',{name:'작업 이름'})).toBe(input);expect(input.value).toBe('실제로 생성한 작업');expect(input.getAttribute('aria-busy')).toBe('true');await waitFor(()=>expect(screen.queryByRole('dialog')).toBe(null));expect(screen.getByText('실제로 생성한 작업')).toBeTruthy();expect(document.activeElement?.textContent).toContain('새 작업');
 await user.click(screen.getByRole('button',{name:'실제로 생성한 작업 편집'}));await user.clear(screen.getByRole('textbox',{name:'작업 이름'}));await user.type(screen.getByRole('textbox',{name:'작업 이름'}),'실제로 편집한 작업');await user.click(screen.getByRole('button',{name:'저장',exact:true}));await waitFor(()=>expect(screen.queryByRole('dialog')).toBe(null));expect(screen.getByText('실제로 편집한 작업')).toBeTruthy();await user.click(screen.getByRole('button',{name:'실제로 편집한 작업 편집'}));await user.clear(screen.getByRole('textbox',{name:'작업 이름'}));await user.type(screen.getByRole('textbox',{name:'작업 이름'}),'취소할 작업');await user.click(screen.getByRole('button',{name:'취소',exact:true}));expect(screen.getByText('실제로 편집한 작업')).toBeTruthy();expect(screen.queryByText('취소할 작업')).toBe(null);
 await user.click(screen.getByRole('button',{name:'새로 고침',exact:true}));expect(screen.getByRole('status').textContent).toContain('불러오는 중');await waitFor(()=>expect(screen.getByText('실제로 편집한 작업')).toBeTruthy());
});
import DocsApp from '../../../apps/docs/src/App';
test('docs live/current Code/reset share state across panels and menu search',async()=>{
 const user=userEvent.setup();render(<DocsApp/>);await user.click(screen.getByRole('button',{name:'Input',exact:true}));const input=screen.getByRole('textbox',{name:'입력 예제'}) as HTMLInputElement;await user.clear(input);await user.type(input,'패널 이동에도 유지');await user.click(screen.getByRole('tab',{name:'Code',exact:true}));expect(input.value).toBe('패널 이동에도 유지');expect(screen.getByRole('tabpanel').textContent).toContain('패널 이동에도 유지');await user.click(screen.getByRole('tab',{name:'Docs',exact:true}));expect(screen.getByRole('textbox',{name:'입력 예제'})).toBe(input);expect(input.value).toBe('패널 이동에도 유지');await user.click(screen.getByRole('button',{name:'Reset',exact:true}));expect(input.value).toBe('읽고, 정리하고, 이어 가기');await user.type(screen.getByRole('textbox',{name:'문서 검색'}),'select');expect(screen.getByRole('button',{name:'Select',exact:true})).toBeTruthy();expect(screen.queryByRole('button',{name:'Button',exact:true})).toBe(null);
});
