import * as Primitive from '@radix-ui/react-alert-dialog';
import { useRef, useState, type ReactElement, type ReactNode } from 'react';
import { Button } from './button';
import { PortalContext, usePortalContainer, usePortalRef, usePortalTheme } from './portal';
export type ConfirmProps={trigger:ReactElement;title:string;description:ReactNode;onConfirm:()=>void|Promise<void>;confirmLabel?:string;cancelLabel?:string;open?:boolean;defaultOpen?:boolean;onOpenChange?:(open:boolean)=>void;disabled?:boolean};
export function Confirm({trigger,title,description,onConfirm,confirmLabel='확인',cancelLabel='취소',open,defaultOpen=false,onOpenChange,disabled=false}:ConfirmProps){
 const [internal,setInternal]=useState(defaultOpen),[pending,setPending]=useState(false),[error,setError]=useState('');const running=useRef(false);const shown=open??internal;
 const theme=usePortalTheme(),container=usePortalContainer(),contentRef=usePortalRef<HTMLDivElement>(),overlayRef=usePortalRef<HTMLDivElement>();const [destination,setDestination]=useState<HTMLDivElement|null>(null);
 const change=(next:boolean)=>{if(running.current&&!next)return;if(open===undefined)setInternal(next);if(next)setError('');onOpenChange?.(next);};
 const confirm=async()=>{if(disabled||running.current)return;running.current=true;setPending(true);setError('');try{await onConfirm();running.current=false;change(false);}catch{setError('작업을 완료하지 못했어요. 다시 시도하거나 취소해 주세요.');}finally{running.current=false;setPending(false);}};
 return <Primitive.Root open={shown} onOpenChange={change}><Primitive.Trigger asChild disabled={disabled}>{trigger}</Primitive.Trigger><Primitive.Portal container={container??undefined}><Primitive.Overlay {...theme} ref={overlayRef} className="fixed inset-0 z-40 bg-g-overlay"/><Primitive.Content {...theme} ref={contentRef} onEscapeKeyDown={event=>{if(running.current)event.preventDefault();}} className="fixed inset-x-4 top-8 z-50 mx-auto grid max-w-lg gap-5 rounded-g-panel border border-solid border-g-line bg-g-surface p-6 text-g-ink shadow-lg sm:top-24"><PortalContext.Provider value={destination}><Primitive.Title className="text-xl font-semibold">{title}</Primitive.Title><Primitive.Description className="break-words text-g-small text-g-soft">{description}</Primitive.Description>{error&&<p role="alert" className="text-g-small text-g-danger">{error}</p>}<div className="flex flex-wrap justify-end gap-3"><Primitive.Cancel asChild><Button variant="secondary" disabled={pending}>{cancelLabel}</Button></Primitive.Cancel><Primitive.Action asChild><Button variant="secondary" className="text-g-danger" loading={pending} disabled={disabled} onClick={event=>{event.preventDefault();void confirm();}}>{confirmLabel}</Button></Primitive.Action></div><div ref={setDestination} className="contents"/></PortalContext.Provider></Primitive.Content></Primitive.Portal></Primitive.Root>;
}
